/* ============================================================
   THEMATIC CATEGORIES - orthogonal to HSK level and part of speech.

   CATEGORIES     [id, display name, emoji]            - 17 parents
   SUBCATEGORIES  [id, display name]                   - id is "parent.sub"
   WORD_CATEGORY  hanzi -> id

   A word maps to a subcategory id ("food.drinks") where it has been
   grouped, or to a bare parent id ("food") where only the parent is
   known - the level-3 pool carried over from the first hand-written
   grouping. Keyed by hanzi and level-agnostic, so a word is themed the
   same wherever the HSK bands place it.

   HSK bands 1 and 2 are fully subcategorised. Later bands fill in.
   ============================================================ */
const CATEGORIES=[
["people","People & Relationships","👥"],
["body","Body & Health","❤"],
["emotion","Emotions & Personality","🙂"],
["time","Time & Seasons","📅"],
["place","Places & Directions","🗺"],
["nature","Nature & Weather","🌳"],
["food","Food & Dining","🍜"],
["clothing","Clothing & Objects","👕"],
["home","Home & Chores","🏠"],
["school","School & Study","📚"],
["work","Work & Business","💼"],
["transport","Transport & Travel","🚆"],
["tech","Tech & Communication","📱"],
["sport","Sports & Leisure","⚽"],
["society","Society & Culture","🏛"],
["concept","Actions & Ideas","💡"],
["grammar","Grammar & Measure Words","🔗"],
];

const SUBCATEGORIES=[
["people.family","Family & relatives"],
["people.social","Friends & people"],
["people.roles","Jobs & roles"],
["people.address","Names & pronouns"],
["people.greetings","Greetings & politeness"],
["body.parts","Body parts"],
["body.senses","Senses & movement"],
["body.illness","Illness & symptoms"],
["body.medicine","Medicine & hospital"],
["emotion.feelings","Feelings"],
["emotion.traits","Character traits"],
["emotion.attitudes","Attitudes & opinions"],
["time.clock","Clock & calendar"],
["time.tense","Days & when"],
["time.frequency","How often & how soon"],
["time.seasons","Seasons & festivals"],
["place.direction","Directions & position"],
["place.city","Around town"],
["place.countries","Countries & languages"],
["place.geography","Geography"],
["nature.weather","Weather"],
["nature.animals","Animals"],
["nature.plants","Plants"],
["nature.landscape","Elements & sky"],
["food.ingredients","Ingredients"],
["food.dishes","Dishes & meals"],
["food.drinks","Drinks"],
["food.cooking","Cooking & taste"],
["food.restaurant","Eating out"],
["clothing.clothes","Clothes & accessories"],
["clothing.colours","Colours & materials"],
["clothing.objects","Everyday objects"],
["home.rooms","Rooms & furniture"],
["home.housework","Housework"],
["home.living","Living & renting"],
["school.life","School life"],
["school.subjects","Subjects & exams"],
["school.literacy","Reading & writing"],
["school.learning","Learning & knowing"],
["school.idioms","Idioms & chengyu"],
["work.workplace","Jobs & workplace"],
["work.money","Money & banking"],
["work.trade","Buying & selling"],
["work.admin","Plans & admin"],
["transport.vehicles","Vehicles"],
["transport.traffic","Roads & traffic"],
["transport.travel","Travel & holidays"],
["transport.tickets","Tickets & stations"],
["tech.devices","Devices"],
["tech.internet","Internet & online"],
["tech.phone","Phone & messaging"],
["tech.media","Media & pictures"],
["sport.sports","Sports"],
["sport.games","Games & play"],
["sport.arts","Music & art"],
["sport.hobbies","Fun & hobbies"],
["society.civic","Law & society"],
["society.history","History & tradition"],
["society.customs","Customs & religion"],
["society.environment","People & environment"],
["concept.doing","Common actions"],
["concept.thinking","Thinking & speaking"],
["concept.change","Change & result"],
["concept.quantity","Quantity & degree"],
["concept.quality","Qualities & descriptions"],
["grammar.measure","Measure words"],
["grammar.particles","Particles & markers"],
["grammar.connectives","Connectives"],
["grammar.questions","Question words"],
];

const WORD_CATEGORY={
/* people.family - 47 */
"爸爸":"people.family","儿子":"people.family","家":"people.family","妈妈":"people.family","女儿":"people.family","弟弟":"people.family",
"哥哥":"people.family","姐姐":"people.family","妹妹":"people.family","妻子":"people.family","丈夫":"people.family","阿姨":"people.family",
"结婚":"people.family","奶奶":"people.family","叔叔":"people.family","爷爷":"people.family","父亲":"people.family","母亲":"people.family",
"亲戚":"people.family","孙子":"people.family","家人":"people.family","男朋友":"people.family","女朋友":"people.family","爱人":"people.family",
"家庭":"people.family","家长":"people.family","全家":"people.family","太太":"people.family","父母":"people.family","家属":"people.family",
"离婚":"people.family","亲":"people.family","亲人":"people.family","子女":"people.family","大哥":"people.family","大姐":"people.family",
"大妈":"people.family","大爷":"people.family","夫妇":"people.family","夫妻":"people.family","姐妹":"people.family","老公":"people.family",
"老婆":"people.family","孙女":"people.family","新郎":"people.family","新娘":"people.family","兄弟":"people.family",
/* people.social - 82 */
"朋友":"people.social","人":"people.social","认识":"people.social","同学":"people.social","大家":"people.social","孩子":"people.social",
"介绍":"people.social","男":"people.social","女":"people.social","别人":"people.social","男人":"people.social","女人":"people.social",
"关系":"people.social","客人":"people.social","邻居":"people.social","儿童":"people.social","年龄":"people.social","硕士":"people.social",
"咸":"people.social","性别":"people.social","邀请":"people.social","友谊":"people.social","约会":"people.social","病人":"people.social",
"老人":"people.social","男孩儿":"people.social","女孩儿":"people.social","网友":"people.social","小孩儿":"people.social","小朋友":"people.social",
"大人":"people.social","好人":"people.social","坏人":"people.social","交朋友":"people.social","老朋友":"people.social","青少年":"people.social",
"人们":"people.social","少年":"people.social","小组":"people.social","有人":"people.social","成员":"people.social","对方":"people.social",
"个人":"people.social","姑娘":"people.social","华人":"people.social","会员":"people.social","交往":"people.social","接待":"people.social",
"老百姓":"people.social","老太太":"people.social","老头儿":"people.social","民间":"people.social","男子":"people.social","女子":"people.social",
"亲自":"people.social","全场":"people.social","人才":"people.social","人民":"people.social","人群":"people.social","熟人":"people.social",
"做客":"people.social","宝宝":"people.social","冰":"people.social","成人":"people.social","大众":"people.social","夫人":"people.social",
"个体":"people.social","好友":"people.social","伙伴":"people.social","聚":"people.social","美女":"people.social","男女":"people.social",
"男士":"people.social","女士":"people.social","胖子":"people.social","青春":"people.social","穷人":"people.social","身高":"people.social",
"帅哥":"people.social","小伙子":"people.social","邯郸学步":"people.social","物是人非":"people.social",
/* people.roles - 72 */
"老师":"people.roles","学生":"people.roles","医生":"people.roles","服务员":"people.roles","博士":"people.roles","经理":"people.roles",
"司机":"people.roles","同事":"people.roles","校长":"people.roles","代表":"people.roles","大夫":"people.roles","顾客":"people.roles",
"护士":"people.roles","教授":"people.roles","警察":"people.roles","律师":"people.roles","师傅":"people.roles","售货员":"people.roles",
"研究生":"people.roles","职业":"people.roles","专门":"people.roles","作者":"people.roles","大学生":"people.roles","工人":"people.roles",
"后":"people.roles","男生":"people.roles","女生":"people.roles","小学生":"people.roles","中学生":"people.roles","班长":"people.roles",
"队长":"people.roles","教师":"people.roles","留学生":"people.roles","旅客":"people.roles","商人":"people.roles","市长":"people.roles",
"游客":"people.roles","院长":"people.roles","主人":"people.roles","组长":"people.roles","作家":"people.roles","班级":"people.roles",
"保安":"people.roles","代表团":"people.roles","读者":"people.roles","防止":"people.roles","歌迷":"people.roles","歌手":"people.roles",
"工程师":"people.roles","交警":"people.roles","老板":"people.roles","农民":"people.roles","人员":"people.roles","员工":"people.roles",
"职工":"people.roles","志愿者":"people.roles","专家":"people.roles","保守":"people.roles","兵":"people.roles","二手":"people.roles",
"行业":"people.roles","会计":"people.roles","录取":"people.roles","秘书":"people.roles","名人":"people.roles","诗人":"people.roles",
"士兵":"people.roles","守":"people.roles","王":"people.roles","战士":"people.roles","主席":"people.roles","总统":"people.roles",
/* people.address - 26 */
"名字":"people.address","你":"people.address","他":"people.address","她":"people.address","我":"people.address","我们":"people.address",
"先生":"people.address","小姐":"people.address","您":"people.address","姓":"people.address","报名":"people.address","你们":"people.address",
"他们":"people.address","她们":"people.address","名":"people.address","名称":"people.address","名单":"people.address","它们":"people.address",
"姓名":"people.address","咱":"people.address","自身":"people.address","登记":"people.address","点名":"people.address","身份":"people.address",
"想念":"people.address","买椟还珠":"people.address",
/* people.greetings - 23 */
"不客气":"people.greetings","对不起":"people.greetings","没关系":"people.greetings","请":"people.greetings","喂":"people.greetings","谢谢":"people.greetings",
"再见":"people.greetings","抱歉":"people.greetings","欢迎":"people.greetings","道歉":"people.greetings","感谢":"people.greetings","礼貌":"people.greetings",
"随便":"people.greetings","祝贺":"people.greetings","没什么":"people.greetings","请进":"people.greetings","请问":"people.greetings","请坐":"people.greetings",
"晚安":"people.greetings","迎接":"people.greetings","招呼":"people.greetings","空谷足音":"people.greetings","顾影自怜":"people.greetings",
/* body.parts - 78 */
"身体":"body.parts","眼睛":"body.parts","鼻子":"body.parts","耳朵":"body.parts","脚":"body.parts","脸":"body.parts",
"胖":"body.parts","头发":"body.parts","腿":"body.parts","肚子":"body.parts","汗":"body.parts","交":"body.parts",
"理发":"body.parts","力气":"body.parts","皮肤":"body.parts","算":"body.parts","握手":"body.parts","血":"body.parts",
"样子":"body.parts","嘴":"body.parts","毛":"body.parts","身上":"body.parts","手":"body.parts","举手":"body.parts",
"面":"body.parts","全身":"body.parts","身边":"body.parts","头":"body.parts","心里":"body.parts","眼":"body.parts",
"表面":"body.parts","部长":"body.parts","付":"body.parts","面对":"body.parts","内心":"body.parts","皮":"body.parts",
"手指":"body.parts","所长":"body.parts","铁":"body.parts","头脑":"body.parts","武器":"body.parts","现象":"body.parts",
"心":"body.parts","眼前":"body.parts","一方面":"body.parts","整体":"body.parts","主任":"body.parts","步行":"body.parts",
"尺":"body.parts","顶":"body.parts","骨头":"body.parts","含":"body.parts","泪":"body.parts","泪水":"body.parts",
"面临":"body.parts","摸":"body.parts","脑袋":"body.parts","器官":"body.parts","前头":"body.parts","赏":"body.parts",
"手里":"body.parts","刷牙":"body.parts","体重":"body.parts","挑":"body.parts","箱子":"body.parts","胸部":"body.parts",
"牙":"body.parts","眼泪":"body.parts","眼里":"body.parts","腰":"body.parts","造型":"body.parts","嘴巴":"body.parts",
"龟裂":"body.parts","齉":"body.parts","胼手胝足":"body.parts","言犹在耳":"body.parts","言不由衷":"body.parts","一语中的":"body.parts",
/* body.senses - 75 */
"看":"body.senses","看见":"body.senses","睡觉":"body.senses","听":"body.senses","坐":"body.senses","跑步":"body.senses",
"休息":"body.senses","走":"body.senses","抱":"body.senses","抽烟":"body.senses","见面":"body.senses","骑":"body.senses",
"声音":"body.senses","遇到":"body.senses","尝":"body.senses","动作":"body.senses","感动":"body.senses","鼓掌":"body.senses",
"起来":"body.senses","散步":"body.senses","躺":"body.senses","味道":"body.senses","响":"body.senses","醒":"body.senses",
"指":"body.senses","飞":"body.senses","见":"body.senses","看到":"body.senses","跑":"body.senses","睡":"body.senses",
"听到":"body.senses","听见":"body.senses","走路":"body.senses","坐下":"body.senses","点头":"body.senses","见到":"body.senses",
"碰":"body.senses","碰到":"body.senses","碰见":"body.senses","听说":"body.senses","闻":"body.senses","午睡":"body.senses",
"站住":"body.senses","走过":"body.senses","走开":"body.senses","步":"body.senses","观察":"body.senses","观看":"body.senses",
"拍":"body.senses","缺":"body.senses","收看":"body.senses","收听":"body.senses","跳":"body.senses","跳高":"body.senses",
"跳远":"body.senses","显得":"body.senses","主张":"body.senses","独立":"body.senses","呼吸":"body.senses","看不起":"body.senses",
"看望":"body.senses","梦见":"body.senses","期待":"body.senses","色":"body.senses","睡着":"body.senses","弯":"body.senses",
"味儿":"body.senses","吸":"body.senses","吸烟":"body.senses","寻找":"body.senses","研究":"body.senses","彳亍":"body.senses",
"踽踽独行":"body.senses","振聋发聩":"body.senses","画龙点睛":"body.senses",
/* body.illness - 23 */
"累":"body.illness","生病":"body.illness","发烧":"body.illness","健康":"body.illness","疼":"body.illness","咳嗽":"body.illness",
"流行":"body.illness","难受":"body.illness","死":"body.illness","病":"body.illness","去世":"body.illness","伤":"body.illness",
"受伤":"body.illness","痛":"body.illness","痛苦":"body.illness","卫生":"body.illness","恶心":"body.illness","缓解":"body.illness",
"伤害":"body.illness","遗传":"body.illness","治疗":"body.illness","妊娠":"body.illness","痼疾":"body.illness",
/* body.medicine - 18 */
"医院":"body.medicine","药":"body.medicine","打针":"body.medicine","耐心":"body.medicine","看病":"body.medicine","出院":"body.medicine",
"西医":"body.medicine","药片":"body.medicine","药水":"body.medicine","中医":"body.medicine","住院":"body.medicine","轮椅":"body.medicine",
"内科":"body.medicine","手术":"body.medicine","体检":"body.medicine","药物":"body.medicine","医疗":"body.medicine","医学":"body.medicine",
/* emotion.feelings - 77 */
"爱":"emotion.feelings","高兴":"emotion.feelings","喜欢":"emotion.feelings","快乐":"emotion.feelings","笑":"emotion.feelings","担心":"emotion.feelings",
"放心":"emotion.feelings","害怕":"emotion.feelings","哭":"emotion.feelings","满意":"emotion.feelings","生气":"emotion.feelings","舒服":"emotion.feelings",
"像":"emotion.feelings","一样":"emotion.feelings","着急":"emotion.feelings","得意":"emotion.feelings","发":"emotion.feelings","烦恼":"emotion.feelings",
"感觉":"emotion.feelings","感情":"emotion.feelings","孤单":"emotion.feelings","害羞":"emotion.feelings","好像":"emotion.feelings","后悔":"emotion.feelings",
"紧张":"emotion.feelings","精神":"emotion.feelings","可怜":"emotion.feelings","可惜":"emotion.feelings","恐怕":"emotion.feelings","浪漫":"emotion.feelings",
"冷静":"emotion.feelings","流泪":"emotion.feelings","内容":"emotion.feelings","受不了":"emotion.feelings","讨厌":"emotion.feelings","同情":"emotion.feelings",
"羡慕":"emotion.feelings","笑话":"emotion.feelings","心情":"emotion.feelings","信心":"emotion.feelings","兴奋":"emotion.feelings","幸福":"emotion.feelings",
"压力":"emotion.feelings","愉快":"emotion.feelings","不好意思":"emotion.feelings","不满":"emotion.feelings","感到":"emotion.feelings","开心":"emotion.feelings",
"可怕":"emotion.feelings","怕":"emotion.feelings","不安":"emotion.feelings","动人":"emotion.feelings","福":"emotion.feelings","感受":"emotion.feelings",
"欢乐":"emotion.feelings","静":"emotion.feelings","乐":"emotion.feelings","迷":"emotion.feelings","情感":"emotion.feelings","热爱":"emotion.feelings",
"幸运":"emotion.feelings","爱国":"emotion.feelings","安":"emotion.feelings","表情":"emotion.feelings","刺激":"emotion.feelings","烦":"emotion.feelings",
"含量":"emotion.feelings","宁静":"emotion.feelings","平静":"emotion.feelings","亲爱":"emotion.feelings","舒适":"emotion.feelings","痛快":"emotion.feelings",
"微笑":"emotion.feelings","喜爱":"emotion.feelings","觊觎":"emotion.feelings","缱绻":"emotion.feelings","叶公好龙":"emotion.feelings",
/* emotion.traits - 62 */
"漂亮":"emotion.traits","聪明":"emotion.traits","笨":"emotion.traits","诚实":"emotion.traits","粗心":"emotion.traits","可爱":"emotion.traits",
"老":"emotion.traits","热情":"emotion.traits","认真":"emotion.traits","小心":"emotion.traits","成熟":"emotion.traits","活泼":"emotion.traits",
"积极":"emotion.traits","骄傲":"emotion.traits","懒":"emotion.traits","马虎":"emotion.traits","美丽":"emotion.traits","脾气":"emotion.traits",
"轻松":"emotion.traits","严格":"emotion.traits","严重":"emotion.traits","阳光":"emotion.traits","勇敢":"emotion.traits","友好":"emotion.traits",
"主动":"emotion.traits","仔细":"emotion.traits","难看":"emotion.traits","爱心":"emotion.traits","个性":"emotion.traits","好奇":"emotion.traits",
"紧":"emotion.traits","可靠":"emotion.traits","乐观":"emotion.traits","类":"emotion.traits","美":"emotion.traits","美好":"emotion.traits",
"亲切":"emotion.traits","热烈":"emotion.traits","文字":"emotion.traits","自觉":"emotion.traits","自主":"emotion.traits","不要紧":"emotion.traits",
"沉默":"emotion.traits","诚信":"emotion.traits","大方":"emotion.traits","高尚":"emotion.traits","角色":"emotion.traits","老实":"emotion.traits",
"类型":"emotion.traits","能干":"emotion.traits","品质":"emotion.traits","热心":"emotion.traits","善良":"emotion.traits","天真":"emotion.traits",
"调皮":"emotion.traits","新型":"emotion.traits","英勇":"emotion.traits","勇气":"emotion.traits","种类":"emotion.traits","魑魅魍魉":"emotion.traits",
"宵衣旰食":"emotion.traits","韶光易逝":"emotion.traits",
/* emotion.attitudes - 59 */
"希望":"emotion.attitudes","保证":"emotion.attitudes","表扬":"emotion.attitudes","猜":"emotion.attitudes","敢":"emotion.attitudes","认为":"emotion.attitudes",
"同意":"emotion.attitudes","要求":"emotion.attitudes","愿意":"emotion.attitudes","反对":"emotion.attitudes","方面":"emotion.attitudes","符合":"emotion.attitudes",
"鼓励":"emotion.attitudes","怀疑":"emotion.attitudes","坚持":"emotion.attitudes","接受":"emotion.attitudes","拒绝":"emotion.attitudes","批评":"emotion.attitudes",
"失望":"emotion.attitudes","收":"emotion.attitudes","态度":"emotion.attitudes","吸引":"emotion.attitudes","信任":"emotion.attitudes","意见":"emotion.attitudes",
"原谅":"emotion.attitudes","责任":"emotion.attitudes","支持":"emotion.attitudes","尊重":"emotion.attitudes","想法":"emotion.attitudes","订":"emotion.attitudes",
"否定":"emotion.attitudes","决心":"emotion.attitudes","批准":"emotion.attitudes","评价":"emotion.attitudes","确保":"emotion.attitudes","认可":"emotion.attitudes",
"受":"emotion.attitudes","愿望":"emotion.attitudes","爱护":"emotion.attitudes","不在乎":"emotion.attitudes","称赞":"emotion.attitudes","承受":"emotion.attitudes",
"担保":"emotion.attitudes","垃圾":"emotion.attitudes","没想到":"emotion.attitudes","确认":"emotion.attitudes","说服":"emotion.attitudes","投诉":"emotion.attitudes",
"依靠":"emotion.attitudes","应":"emotion.attitudes","在乎":"emotion.attitudes","赞成":"emotion.attitudes","赞赏":"emotion.attitudes","赞助":"emotion.attitudes",
"征求":"emotion.attitudes","祝福":"emotion.attitudes","龃龉":"emotion.attitudes","埋怨":"emotion.attitudes","自怨自艾":"emotion.attitudes",
/* time.clock - 58 */
"点":"time.clock","分钟":"time.clock","号":"time.clock","时候":"time.clock","中午":"time.clock","次":"time.clock",
"时间":"time.clock","小时":"time.clock","按时":"time.clock","倍":"time.clock","季节":"time.clock","久":"time.clock",
"当时":"time.clock","及时":"time.clock","来不及":"time.clock","来得及":"time.clock","平时":"time.clock","提前":"time.clock",
"现代":"time.clock","正好":"time.clock","准时":"time.clock","没事儿":"time.clock","日期":"time.clock","上次":"time.clock",
"下次":"time.clock","一下儿":"time.clock","半夜":"time.clock","那时候":"time.clock","日子":"time.clock","随时":"time.clock",
"有空儿":"time.clock","长期":"time.clock","当初":"time.clock","定期":"time.clock","古代":"time.clock","近期":"time.clock",
"空儿":"time.clock","目前":"time.clock","人生":"time.clock","时":"time.clock","时刻":"time.clock","武术":"time.clock",
"早已":"time.clock","度过":"time.clock","多次":"time.clock","季度":"time.clock","临时":"time.clock","闹钟":"time.clock",
"期间":"time.clock","期限":"time.clock","日历":"time.clock","学时":"time.clock","业余":"time.clock","蹉跎":"time.clock",
"韬光养晦":"time.clock","沧海桑田":"time.clock","白驹过隙":"time.clock","物换星移":"time.clock",
/* time.tense - 103 */
"今天":"time.tense","明天":"time.tense","年":"time.tense","上午":"time.tense","岁":"time.tense","下午":"time.tense",
"现在":"time.tense","星期":"time.tense","月":"time.tense","昨天":"time.tense","去年":"time.tense","日":"time.tense",
"晚上":"time.tense","已经":"time.tense","早上":"time.tense","本来":"time.tense","刚才":"time.tense","还是":"time.tense",
"礼物":"time.tense","年级":"time.tense","以后":"time.tense","以前":"time.tense","终于":"time.tense","周末":"time.tense",
"最近":"time.tense","刚刚":"time.tense","后来":"time.tense","将来":"time.tense","仍然":"time.tense","原来":"time.tense",
"最后":"time.tense","白天":"time.tense","半年":"time.tense","后天":"time.tense","今年":"time.tense","明年":"time.tense",
"前天":"time.tense","天":"time.tense","晚":"time.tense","星期日":"time.tense","星期天":"time.tense","早":"time.tense",
"不久":"time.tense","不一会儿":"time.tense","从小":"time.tense","今后":"time.tense","快要":"time.tense","老年":"time.tense",
"那会儿":"time.tense","前年":"time.tense","青年":"time.tense","全年":"time.tense","上周":"time.tense","下周":"time.tense",
"小时候":"time.tense","夜":"time.tense","夜里":"time.tense","一生":"time.tense","月份":"time.tense","早晨":"time.tense",
"这时候":"time.tense","中年":"time.tense","曾经":"time.tense","初":"time.tense","初步":"time.tense","从前":"time.tense",
"国庆":"time.tense","后年":"time.tense","年初":"time.tense","年底":"time.tense","年纪":"time.tense","前后":"time.tense",
"日常":"time.tense","时代":"time.tense","始终":"time.tense","已":"time.tense","以来":"time.tense","整天":"time.tense",
"直到":"time.tense","至今":"time.tense","曾":"time.tense","潮流":"time.tense","从此":"time.tense","纷纷":"time.tense",
"既":"time.tense","近代":"time.tense","前途":"time.tense","如今":"time.tense","上个月":"time.tense","事先":"time.tense",
"童年":"time.tense","未来":"time.tense","下个月":"time.tense","学年":"time.tense","依然":"time.tense","月底":"time.tense",
"之后":"time.tense","之间":"time.tense","之前":"time.tense","最初":"time.tense","耄耋":"time.tense","焚膏继晷":"time.tense",
"望洋兴叹":"time.tense",
/* time.frequency - 50 */
"还":"time.frequency","就":"time.frequency","再":"time.frequency","迟到":"time.frequency","重新":"time.frequency","从来":"time.frequency",
"经常":"time.frequency","马上":"time.frequency","突然":"time.frequency","先":"time.frequency","又":"time.frequency","总是":"time.frequency",
"到底":"time.frequency","忽然":"time.frequency","偶尔":"time.frequency","却":"time.frequency","往往":"time.frequency","永远":"time.frequency",
"暂时":"time.frequency","逐渐":"time.frequency","常":"time.frequency","常常":"time.frequency","有时候":"time.frequency","重":"time.frequency",
"重复":"time.frequency","好久":"time.frequency","急":"time.frequency","快点儿":"time.frequency","老是":"time.frequency","同时":"time.frequency",
"早就":"time.frequency","不断":"time.frequency","反复":"time.frequency","赶到":"time.frequency","赶快":"time.frequency","紧急":"time.frequency",
"立刻":"time.frequency","连忙":"time.frequency","连续":"time.frequency","慢慢":"time.frequency","仍":"time.frequency","急忙":"time.frequency",
"渐渐":"time.frequency","立即":"time.frequency","陆续":"time.frequency","迫切":"time.frequency","迅速":"time.frequency","一再":"time.frequency",
"再三":"time.frequency","逐步":"time.frequency",
/* time.seasons - 23 */
"生日":"time.seasons","春":"time.seasons","冬":"time.seasons","节日":"time.seasons","秋":"time.seasons","夏":"time.seasons",
"放暑假":"time.seasons","寒假":"time.seasons","弹":"time.seasons","新年":"time.seasons","春节":"time.seasons","春天":"time.seasons",
"冬天":"time.seasons","过年":"time.seasons","秋天":"time.seasons","夏天":"time.seasons","周年":"time.seasons","春季":"time.seasons",
"冬季":"time.seasons","季":"time.seasons","秋季":"time.seasons","暑假":"time.seasons","夏季":"time.seasons",
/* place.direction - 110 */
"后面":"place.direction","里":"place.direction","那":"place.direction","前面":"place.direction","上":"place.direction","下":"place.direction",
"这":"place.direction","近":"place.direction","旁边":"place.direction","外":"place.direction","右边":"place.direction","远":"place.direction",
"左边":"place.direction","北方":"place.direction","东":"place.direction","附近":"place.direction","南":"place.direction","西":"place.direction",
"一边":"place.direction","中间":"place.direction","当地":"place.direction","到处":"place.direction","底":"place.direction","对面":"place.direction",
"方向":"place.direction","究竟":"place.direction","困":"place.direction","内":"place.direction","其中":"place.direction","剩":"place.direction",
"相反":"place.direction","周围":"place.direction","北":"place.direction","北边":"place.direction","东边":"place.direction","后边":"place.direction",
"里边":"place.direction","楼上":"place.direction","楼下":"place.direction","那边":"place.direction","那里":"place.direction","那儿":"place.direction",
"那些":"place.direction","南边":"place.direction","前":"place.direction","前边":"place.direction","上边":"place.direction","外边":"place.direction",
"西边":"place.direction","下边":"place.direction","右":"place.direction","这边":"place.direction","这里":"place.direction","这儿":"place.direction",
"这些":"place.direction","中":"place.direction","左":"place.direction","边":"place.direction","东北":"place.direction","东方":"place.direction",
"东南":"place.direction","里头":"place.direction","面前":"place.direction","那样":"place.direction","南方":"place.direction","问路":"place.direction",
"西北":"place.direction","西方":"place.direction","西南":"place.direction","以上":"place.direction","以外":"place.direction","以下":"place.direction",
"这样":"place.direction","中级":"place.direction","中小学":"place.direction","中心":"place.direction","背后":"place.direction","当中":"place.direction",
"底下":"place.direction","东部":"place.direction","里面":"place.direction","领先":"place.direction","落后":"place.direction","全面":"place.direction",
"上面":"place.direction","双方":"place.direction","外面":"place.direction","围":"place.direction","下面":"place.direction","指导":"place.direction",
"中部":"place.direction","转":"place.direction","左右":"place.direction","此":"place.direction","地位":"place.direction","地下":"place.direction",
"后头":"place.direction","两边":"place.direction","零食":"place.direction","没错":"place.direction","内部":"place.direction","暖气":"place.direction",
"权利":"place.direction","五颜六色":"place.direction","引导":"place.direction","转动":"place.direction","转弯":"place.direction","旮旯":"place.direction",
"熨帖":"place.direction","寄人篱下":"place.direction",
/* place.city - 83 */
"饭店":"place.city","商店":"place.city","宾馆":"place.city","火车站":"place.city","机场":"place.city","路":"place.city",
"超市":"place.city","城市":"place.city","地方":"place.city","电梯":"place.city","参观":"place.city","厕所":"place.city",
"放":"place.city","公园":"place.city","街道":"place.city","图书馆":"place.city","洗手间":"place.city","站":"place.city",
"代替":"place.city","地址":"place.city","加油站":"place.city","农村":"place.city","桥":"place.city","热闹":"place.city",
"入口":"place.city","市场":"place.city","首都":"place.city","首先":"place.city","抬":"place.city","网站":"place.city",
"车站":"place.city","打车":"place.city","地点":"place.city","电影院":"place.city","教学楼":"place.city","路口":"place.city",
"路上":"place.city","马路":"place.city","商场":"place.city","书店":"place.city","出口":"place.city","道":"place.city",
"道路":"place.city","地铁站":"place.city","店":"place.city","动物园":"place.city","公路":"place.city","广场":"place.city",
"街":"place.city","酒店":"place.city","路边":"place.city","市":"place.city","停车场":"place.city","药店":"place.city",
"场所":"place.city","城":"place.city","村":"place.city","电视台":"place.city","电台":"place.city","房屋":"place.city",
"放到":"place.city","家乡":"place.city","剧场":"place.city","旅馆":"place.city","所":"place.city","卫生间":"place.city",
"安置":"place.city","处":"place.city","大楼":"place.city","堵":"place.city","方":"place.city","酒吧":"place.city",
"老家":"place.city","平方":"place.city","设施":"place.city","市区":"place.city","替":"place.city","推销":"place.city",
"网址":"place.city","位置":"place.city","销售":"place.city","预订":"place.city","鳞次栉比":"place.city",
/* place.countries - 40 */
"北京":"place.countries","汉语":"place.countries","中国":"place.countries","国家":"place.countries","普通话":"place.countries","世界":"place.countries",
"大使馆":"place.countries","翻译":"place.countries","国际":"place.countries","京剧":"place.countries","留学":"place.countries","民族":"place.countries",
"人民币":"place.countries","亚洲":"place.countries","语言":"place.countries","中文":"place.countries","国":"place.countries","国外":"place.countries",
"话":"place.countries","外国":"place.countries","外语":"place.countries","出国":"place.countries","回国":"place.countries","全国":"place.countries",
"外地":"place.countries","英文":"place.countries","英语":"place.countries","白菜":"place.countries","各地":"place.countries","国内":"place.countries",
"联合国":"place.countries","美元":"place.countries","世界杯":"place.countries","外文":"place.countries","中华民族":"place.countries","资金":"place.countries",
"口语":"place.countries","外汇":"place.countries","县":"place.countries","之乎者也":"place.countries",
/* place.geography - 36 */
"地图":"place.geography","河":"place.geography","爬山":"place.geography","长江":"place.geography","地球":"place.geography","风景":"place.geography",
"海洋":"place.geography","森林":"place.geography","专业":"place.geography","地上":"place.geography","山":"place.geography","大海":"place.geography",
"海":"place.geography","海边":"place.geography","湖":"place.geography","星星":"place.geography","地区":"place.geography","海关":"place.geography",
"景色":"place.geography","理由":"place.geography","面积":"place.geography","区":"place.geography","天空":"place.geography","土":"place.geography",
"操场":"place.geography","大陆":"place.geography","登山":"place.geography","地面":"place.geography","海水":"place.geography","汇":"place.geography",
"江":"place.geography","降落":"place.geography","陆地":"place.geography","土地":"place.geography","旖旎":"place.geography","逶迤":"place.geography",
/* nature.weather - 44 */
"冷":"nature.weather","热":"nature.weather","天气":"nature.weather","下雨":"nature.weather","晴":"nature.weather","雪":"nature.weather",
"阴":"nature.weather","感冒":"nature.weather","刮":"nature.weather","太阳":"nature.weather","干燥":"nature.weather","辣":"nature.weather",
"凉快":"nature.weather","暖和":"nature.weather","气候":"nature.weather","湿润":"nature.weather","汤":"nature.weather","温度":"nature.weather",
"风":"nature.weather","雨":"nature.weather","吹":"nature.weather","多云":"nature.weather","凉":"nature.weather","零下":"nature.weather",
"气温":"nature.weather","晴天":"nature.weather","下雪":"nature.weather","阴天":"nature.weather","程度":"nature.weather","凉水":"nature.weather",
"难度":"nature.weather","温暖":"nature.weather","预报":"nature.weather","预计":"nature.weather","薄":"nature.weather","冰雪":"nature.weather",
"潮":"nature.weather","潮湿":"nature.weather","打雷":"nature.weather","寒冷":"nature.weather","晒":"nature.weather","闪电":"nature.weather",
"湿":"nature.weather","预测":"nature.weather",
/* nature.animals - 22 */
"狗":"nature.animals","猫":"nature.animals","鱼":"nature.animals","动物":"nature.animals","马":"nature.animals","鸟":"nature.animals",
"熊猫":"nature.animals","猴子":"nature.animals","老虎":"nature.animals","狮子":"nature.animals","猪":"nature.animals","鸡":"nature.animals",
"养":"nature.animals","龙":"nature.animals","牛":"nature.animals","羊":"nature.animals","虫子":"nature.animals","负担":"nature.animals",
"闪":"nature.animals","尾巴":"nature.animals","饕餮":"nature.animals","貔貅":"nature.animals",
/* nature.plants - 23 */
"草":"nature.plants","花":"nature.plants","蓝":"nature.plants","树":"nature.plants","种":"nature.plants","叶子":"nature.plants",
"植物":"nature.plants","草地":"nature.plants","部门":"nature.plants","录":"nature.plants","种子":"nature.plants","茶叶":"nature.plants",
"刺":"nature.plants","果实":"nature.plants","开花":"nature.plants","收获":"nature.plants","树林":"nature.plants","树叶":"nature.plants",
"松":"nature.plants","松树":"nature.plants","鲜花":"nature.plants","玉米":"nature.plants","种植":"nature.plants",
/* nature.landscape - 37 */
"水":"nature.landscape","灯":"nature.landscape","环境":"nature.landscape","空调":"nature.landscape","月亮":"nature.landscape","光":"nature.landscape",
"火":"nature.landscape","空气":"nature.landscape","轻":"nature.landscape","性格":"nature.landscape","自然":"nature.landscape","大自然":"nature.landscape",
"气":"nature.landscape","天上":"nature.landscape","播出":"nature.landscape","光明":"nature.landscape","金":"nature.landscape","沙子":"nature.landscape",
"石头":"nature.landscape","照":"nature.landscape","准":"nature.landscape","宝石":"nature.landscape","冲":"nature.landscape","纯净水":"nature.landscape",
"灯光":"nature.landscape","电灯":"nature.landscape","高潮":"nature.landscape","开水":"nature.landscape","矿泉水":"nature.landscape","浅":"nature.landscape",
"燃烧":"nature.landscape","性质":"nature.landscape","摇":"nature.landscape","影子":"nature.landscape","着火":"nature.landscape","资源":"nature.landscape",
"爨":"nature.landscape",
/* food.ingredients - 28 */
"菜":"food.ingredients","米饭":"food.ingredients","苹果":"food.ingredients","水果":"food.ingredients","鸡蛋":"food.ingredients","面条":"food.ingredients",
"西瓜":"food.ingredients","羊肉":"food.ingredients","果汁":"food.ingredients","面包":"food.ingredients","葡萄":"food.ingredients","糖":"food.ingredients",
"香蕉":"food.ingredients","巧克力":"food.ingredients","西红柿":"food.ingredients","盐":"food.ingredients","饭":"food.ingredients","面条儿":"food.ingredients",
"肉":"food.ingredients","蛋":"food.ingredients","方便面":"food.ingredients","油":"food.ingredients","石油":"food.ingredients","豆腐":"food.ingredients",
"瓜":"food.ingredients","海鲜":"food.ingredients","黄瓜":"food.ingredients","粮食":"food.ingredients",
/* food.dishes - 26 */
"蛋糕":"food.dishes","包子":"food.dishes","饼干":"food.dishes","新鲜":"food.dishes","干":"food.dishes","饺子":"food.dishes",
"请客":"food.dishes","食品":"food.dishes","吃饭":"food.dishes","晚饭":"food.dishes","午饭":"food.dishes","早饭":"food.dishes",
"快餐":"food.dishes","食物":"food.dishes","外卖":"food.dishes","晚餐":"food.dishes","午餐":"food.dishes","西餐":"food.dishes",
"早餐":"food.dishes","中餐":"food.dishes","做饭":"food.dishes","美食":"food.dishes","盘":"food.dishes","套餐":"food.dishes",
"消化":"food.dishes","小吃":"food.dishes",
/* food.drinks - 17 */
"茶":"food.drinks","喝":"food.drinks","咖啡":"food.drinks","牛奶":"food.drinks","渴":"food.drinks","啤酒":"food.drinks",
"干杯":"food.drinks","饮料":"food.drinks","奶":"food.drinks","酒":"food.drinks","红茶":"food.drinks","红酒":"food.drinks",
"绿茶":"food.drinks","奶茶":"food.drinks","汽水":"food.drinks","酸奶":"food.drinks","饮鸩止渴":"food.drinks",
/* food.cooking - 15 */
"吃":"food.cooking","好吃":"food.cooking","饱":"food.cooking","厨房":"food.cooking","饿":"food.cooking","甜":"food.cooking",
"苦":"food.cooking","酸":"food.cooking","香":"food.cooking","熟":"food.cooking","营养":"food.cooking","淡":"food.cooking",
"切":"food.cooking","烧":"food.cooking","填":"food.cooking",
/* food.restaurant - 22 */
"杯子":"food.restaurant","菜单":"food.restaurant","餐厅":"food.restaurant","饭馆":"food.restaurant","筷子":"food.restaurant","盘子":"food.restaurant",
"碗":"food.restaurant","戴":"food.restaurant","刀":"food.restaurant","排列":"food.restaurant","瓶子":"food.restaurant","收拾":"food.restaurant",
"顺序":"food.restaurant","瓶":"food.restaurant","发出":"food.restaurant","整":"food.restaurant","钟":"food.restaurant","布置":"food.restaurant",
"单":"food.restaurant","发票":"food.restaurant","食堂":"food.restaurant","吸管":"food.restaurant",
/* clothing.clothes - 28 */
"衣服":"clothing.clothes","穿":"clothing.clothes","衬衫":"clothing.clothes","打扮":"clothing.clothes","换":"clothing.clothes","裤子":"clothing.clothes",
"帽子":"clothing.clothes","裙子":"clothing.clothes","瘦":"clothing.clothes","鞋":"clothing.clothes","适合":"clothing.clothes","袜子":"clothing.clothes",
"大衣":"clothing.clothes","球鞋":"clothing.clothes","装":"clothing.clothes","衬衣":"clothing.clothes","短裤":"clothing.clothes","服装":"clothing.clothes",
"上衣":"clothing.clothes","系":"clothing.clothes","衣架":"clothing.clothes","穿上":"clothing.clothes","口袋":"clothing.clothes","毛衣":"clothing.clothes",
"模特儿":"clothing.clothes","手套":"clothing.clothes","外套":"clothing.clothes","围巾":"clothing.clothes",
/* clothing.colours - 26 */
"白":"clothing.colours","黑":"clothing.colours","红":"clothing.colours","颜色":"clothing.colours","材料":"clothing.colours","黄":"clothing.colours",
"绿":"clothing.colours","塑料袋":"clothing.colours","白色":"clothing.colours","黑色":"clothing.colours","红色":"clothing.colours","黄色":"clothing.colours",
"蓝色":"clothing.colours","绿色":"clothing.colours","彩色":"clothing.colours","教材":"clothing.colours","银":"clothing.colours","银牌":"clothing.colours",
"红包":"clothing.colours","黄金":"clothing.colours","色彩":"clothing.colours","塑料":"clothing.colours","图案":"clothing.colours","鲜":"clothing.colours",
"玉":"clothing.colours","原料":"clothing.colours",
/* clothing.objects - 49 */
"东西":"clothing.objects","手表":"clothing.objects","包":"clothing.objects","节目":"clothing.objects","伞":"clothing.objects","刷":"clothing.objects",
"眼镜":"clothing.objects","反映":"clothing.objects","工具":"clothing.objects","盒子":"clothing.objects","镜子":"clothing.objects","看法":"clothing.objects",
"毛巾":"clothing.objects","洗衣机":"clothing.objects","牙膏":"clothing.objects","钥匙":"clothing.objects","钱包":"clothing.objects","事":"clothing.objects",
"表":"clothing.objects","纸":"clothing.objects","板":"clothing.objects","办理":"clothing.objects","处理":"clothing.objects","对象":"clothing.objects",
"环":"clothing.objects","机器":"clothing.objects","皮包":"clothing.objects","设备":"clothing.objects","玩具":"clothing.objects","线":"clothing.objects",
"烟":"clothing.objects","邮箱":"clothing.objects","证件":"clothing.objects","宝":"clothing.objects","宝贝":"clothing.objects","袋":"clothing.objects",
"对付":"clothing.objects","盖":"clothing.objects","论文":"clothing.objects","模型":"clothing.objects","情景":"clothing.objects","圈":"clothing.objects",
"试卷":"clothing.objects","事物":"clothing.objects","刷子":"clothing.objects","项目":"clothing.objects","牙刷":"clothing.objects","针":"clothing.objects",
"口是心非":"clothing.objects",
/* home.rooms - 40 */
"椅子":"home.rooms","桌子":"home.rooms","房间":"home.rooms","门":"home.rooms","搬":"home.rooms","层":"home.rooms",
"表格":"home.rooms","长城":"home.rooms","窗户":"home.rooms","花园":"home.rooms","楼":"home.rooms","家具":"home.rooms",
"乒乓球":"home.rooms","墙":"home.rooms","沙发":"home.rooms","床":"home.rooms","房子":"home.rooms","关上":"home.rooms",
"回家":"home.rooms","家里":"home.rooms","门口":"home.rooms","在家":"home.rooms","出门":"home.rooms","大门":"home.rooms",
"院":"home.rooms","院子":"home.rooms","搬家":"home.rooms","被子":"home.rooms","厂":"home.rooms","房租":"home.rooms",
"故乡":"home.rooms","室":"home.rooms","书架":"home.rooms","屋子":"home.rooms","窗台":"home.rooms","窗子":"home.rooms",
"关闭":"home.rooms","空间":"home.rooms","楼梯":"home.rooms","阳台":"home.rooms",
/* home.housework - 14 */
"洗":"home.housework","打扫":"home.housework","擦":"home.housework","干净":"home.housework","垃圾桶":"home.housework","修":"home.housework",
"整理":"home.housework","补":"home.housework","定":"home.housework","固定":"home.housework","家务":"home.housework","扫":"home.housework",
"修理":"home.housework","装修":"home.housework",
/* home.living - 17 */
"住":"home.living","活动":"home.living","激动":"home.living","生活":"home.living","生命":"home.living","印象":"home.living",
"租":"home.living","出租":"home.living","住房":"home.living","调":"home.living","房东":"home.living","活":"home.living",
"直播":"home.living","居民":"home.living","居住":"home.living","移":"home.living","移动":"home.living",
/* school.life - 30 */
"学校":"school.life","教室":"school.life","课":"school.life","班":"school.life","毕业":"school.life","词语":"school.life",
"作业":"school.life","大学":"school.life","放学":"school.life","上课":"school.life","上学":"school.life","书包":"school.life",
"下课":"school.life","小学":"school.life","学院":"school.life","中学":"school.life","高中":"school.life","开学":"school.life",
"课堂":"school.life","校园":"school.life","学期":"school.life","初中":"school.life","短期":"school.life","派":"school.life",
"毕业生":"school.life","奖学金":"school.life","培训班":"school.life","期末":"school.life","幼儿园":"school.life","独树一帜":"school.life",
/* school.subjects - 55 */
"考试":"school.subjects","成绩":"school.subjects","当然":"school.subjects","电子":"school.subjects","极":"school.subjects","历史":"school.subjects",
"数学":"school.subjects","高级":"school.subjects","过程":"school.subjects","合格":"school.subjects","结果":"school.subjects","科学":"school.subjects",
"任务":"school.subjects","试":"school.subjects","效果":"school.subjects","预习":"school.subjects","质量":"school.subjects","考":"school.subjects",
"分数":"school.subjects","级":"school.subjects","考生":"school.subjects","科":"school.subjects","成果":"school.subjects","初级":"school.subjects",
"得分":"school.subjects","功课":"school.subjects","话题":"school.subjects","考验":"school.subjects","科技":"school.subjects","课程":"school.subjects",
"理论":"school.subjects","实验":"school.subjects","实验室":"school.subjects","试题":"school.subjects","试验":"school.subjects","题目":"school.subjects",
"提问":"school.subjects","文学":"school.subjects","需求":"school.subjects","专题":"school.subjects","资格":"school.subjects","本科":"school.subjects",
"比分":"school.subjects","测试":"school.subjects","工程":"school.subjects","规律":"school.subjects","及格":"school.subjects","检测":"school.subjects",
"讲座":"school.subjects","期中":"school.subjects","心理":"school.subjects","学分":"school.subjects","学术":"school.subjects","研制":"school.subjects",
"主题":"school.subjects",
/* school.literacy - 60 */
"读":"school.literacy","书":"school.literacy","写":"school.literacy","字":"school.literacy","报纸":"school.literacy","铅笔":"school.literacy",
"笔记本":"school.literacy","词典":"school.literacy","段":"school.literacy","黑板":"school.literacy","句子":"school.literacy","信":"school.literacy",
"字典":"school.literacy","日记":"school.literacy","台":"school.literacy","文章":"school.literacy","小说":"school.literacy","语法":"school.literacy",
"阅读":"school.literacy","杂志":"school.literacy","本子":"school.literacy","读书":"school.literacy","汉字":"school.literacy","记":"school.literacy",
"课本":"school.literacy","课文":"school.literacy","听写":"school.literacy","笔":"school.literacy","词":"school.literacy","读音":"school.literacy",
"日报":"school.literacy","生词":"school.literacy","晚报":"school.literacy","音节":"school.literacy","作文":"school.literacy","报":"school.literacy",
"标题":"school.literacy","发表":"school.literacy","念":"school.literacy","通信":"school.literacy","写作":"school.literacy","信封":"school.literacy",
"词汇":"school.literacy","符号":"school.literacy","记载":"school.literacy","经典":"school.literacy","括号":"school.literacy","诗":"school.literacy",
"童话":"school.literacy","语音":"school.literacy","著作":"school.literacy","字母":"school.literacy","佶屈聱牙":"school.literacy","朝三暮四":"school.literacy",
"字字珠玑":"school.literacy","妙笔生花":"school.literacy","言外之意":"school.literacy","微言大义":"school.literacy","言而无信":"school.literacy","言必有中":"school.literacy",
/* school.learning - 73 */
"学习":"school.learning","懂":"school.learning","题":"school.learning","问":"school.learning","问题":"school.learning","知道":"school.learning",
"错误":"school.learning","答案":"school.learning","回答":"school.learning","才":"school.learning","复习":"school.learning","记得":"school.learning",
"讲":"school.learning","教":"school.learning","接":"school.learning","练习":"school.learning","了解":"school.learning","水平":"school.learning",
"忘记":"school.learning","兴趣":"school.learning","回忆":"school.learning","教育":"school.learning","解释":"school.learning","经历":"school.learning",
"经验":"school.learning","理解":"school.learning","流利":"school.learning","能力":"school.learning","实际":"school.learning","熟悉":"school.learning",
"说明":"school.learning","误会":"school.learning","正确":"school.learning","知识":"school.learning","总结":"school.learning","记住":"school.learning",
"忘":"school.learning","学":"school.learning","查":"school.learning","答应":"school.learning","懂得":"school.learning","教学":"school.learning",
"练":"school.learning","请求":"school.learning","听讲":"school.learning","本领":"school.learning","本事":"school.learning","才能":"school.learning",
"打听":"school.learning","工夫":"school.learning","集中":"school.learning","纪念":"school.learning","开业":"school.learning","请教":"school.learning",
"认出":"school.learning","认得":"school.learning","体会":"school.learning","体验":"school.learning","听力":"school.learning","参考":"school.learning",
"常识":"school.learning","改正":"school.learning","概括":"school.learning","怀念":"school.learning","技巧":"school.learning","教训":"school.learning",
"考察":"school.learning","熟练":"school.learning","学问":"school.learning","疑问":"school.learning","智力":"school.learning","专心":"school.learning",
"造诣":"school.learning",
/* school.idioms - 29 */
"虚与委蛇":"school.idioms","暴虎冯河":"school.idioms","醍醐灌顶":"school.idioms","味同嚼蜡":"school.idioms","筚路蓝缕":"school.idioms","睚眦必报":"school.idioms",
"怙恶不悛":"school.idioms","鞭辟入里":"school.idioms","荷枪实弹":"school.idioms","拾级而上":"school.idioms","形而上":"school.idioms","形而下":"school.idioms",
"东施效颦":"school.idioms","杞人忧天":"school.idioms","塞翁失马":"school.idioms","越俎代庖":"school.idioms","世事无常":"school.idioms","形单影只":"school.idioms",
"自食其果":"school.idioms","大相径庭":"school.idioms","南辕北辙式":"school.idioms","余音绕梁":"school.idioms","入木三分":"school.idioms","咬文嚼字":"school.idioms",
"无病呻吟":"school.idioms","矫揉造作":"school.idioms","阳奉阴违":"school.idioms","不落窠臼":"school.idioms","别具匠心":"school.idioms",
/* work.workplace - 65 */
"工作":"work.workplace","公司":"work.workplace","忙":"work.workplace","上班":"work.workplace","办公室":"work.workplace","锻炼":"work.workplace",
"出差":"work.workplace","会议":"work.workplace","举行":"work.workplace","用":"work.workplace","加班":"work.workplace","陪":"work.workplace",
"使用":"work.workplace","填空":"work.workplace","招聘":"work.workplace","组织":"work.workplace","做生意":"work.workplace","开会":"work.workplace",
"下班":"work.workplace","打工":"work.workplace","服务":"work.workplace","干活儿":"work.workplace","实习":"work.workplace","报到":"work.workplace",
"部":"work.workplace","采用":"work.workplace","工厂":"work.workplace","公务员":"work.workplace","工业":"work.workplace","加工":"work.workplace",
"坚决":"work.workplace","经营":"work.workplace","就业":"work.workplace","农业":"work.workplace","人工":"work.workplace","商业":"work.workplace",
"生意":"work.workplace","事业":"work.workplace","团体":"work.workplace","退休":"work.workplace","邮件":"work.workplace","值":"work.workplace",
"作品":"work.workplace","办事":"work.workplace","采访":"work.workplace","操作":"work.workplace","大会":"work.workplace","担任":"work.workplace",
"分手":"work.workplace","合同":"work.workplace","机构":"work.workplace","坚固":"work.workplace","简历":"work.workplace","名片":"work.workplace",
"企业":"work.workplace","散":"work.workplace","失业":"work.workplace","手工":"work.workplace","义务":"work.workplace","营业":"work.workplace",
"邮局":"work.workplace","召开":"work.workplace","制订":"work.workplace","转移":"work.workplace","洛阳纸贵":"work.workplace",
/* work.money - 47 */
"块":"work.money","钱":"work.money","贵":"work.money","便宜":"work.money","差":"work.money","存":"work.money",
"银行":"work.money","注意":"work.money","丰富":"work.money","富":"work.money","工资":"work.money","价格":"work.money",
"奖金":"work.money","免费":"work.money","穷":"work.money","省":"work.money","信用卡":"work.money","银行卡":"work.money",
"费":"work.money","费用":"work.money","关注":"work.money","记录":"work.money","价钱":"work.money","交费":"work.money",
"票价":"work.money","收费":"work.money","退":"work.money","退出":"work.money","现金":"work.money","消费":"work.money",
"学费":"work.money","支付":"work.money","财产":"work.money","财富":"work.money","待遇":"work.money","付出":"work.money",
"高价":"work.money","汇报":"work.money","汇率":"work.money","货":"work.money","讲究":"work.money","降价":"work.money",
"美金":"work.money","收益":"work.money","特价":"work.money","投资":"work.money","拮据":"work.money",
/* work.trade - 18 */
"买":"work.trade","卖":"work.trade","打折":"work.trade","购物":"work.trade","经济":"work.trade","提供":"work.trade",
"交易":"work.trade","商品":"work.trade","百货":"work.trade","产品":"work.trade","出售":"work.trade","促销":"work.trade",
"供应":"work.trade","购买":"work.trade","进口":"work.trade","商务":"work.trade","引进":"work.trade","中介":"work.trade",
/* work.admin - 57 */
"打算":"work.admin","安排":"work.admin","标准":"work.admin","决定":"work.admin","报道":"work.admin","调查":"work.admin",
"复印":"work.admin","管理":"work.admin","规定":"work.admin","计划":"work.admin","禁止":"work.admin","梦":"work.admin",
"弄":"work.admin","申请":"work.admin","帅":"work.admin","证明":"work.admin","主意":"work.admin","组成":"work.admin",
"办":"work.admin","组":"work.admin","报告":"work.admin","飞行":"work.admin","规范":"work.admin","集体":"work.admin",
"牌子":"work.admin","取消":"work.admin","任":"work.admin","设计":"work.admin","身份证":"work.admin","手续":"work.admin",
"谈判":"work.admin","推动":"work.admin","文件":"work.admin","形成":"work.admin","形式":"work.admin","形象":"work.admin",
"形状":"work.admin","应用":"work.admin","邮票":"work.admin","证":"work.admin","主持":"work.admin","摆":"work.admin",
"标志":"work.admin","程序":"work.admin","登录":"work.admin","方案":"work.admin","方针":"work.admin","构成":"work.admin",
"规则":"work.admin","列":"work.admin","批":"work.admin","通知书":"work.admin","透":"work.admin","效率":"work.admin",
"用途":"work.admin","治":"work.admin","圭臬":"work.admin",
/* transport.vehicles - 32 */
"出租车":"transport.vehicles","飞机":"transport.vehicles","公共汽车":"transport.vehicles","船":"transport.vehicles","地铁":"transport.vehicles","自行车":"transport.vehicles",
"车":"transport.vehicles","车票":"transport.vehicles","车上":"transport.vehicles","火车":"transport.vehicles","开车":"transport.vehicles","汽车":"transport.vehicles",
"上车":"transport.vehicles","下车":"transport.vehicles","车辆":"transport.vehicles","公交车":"transport.vehicles","骑车":"transport.vehicles","停车":"transport.vehicles",
"划船":"transport.vehicles","训练":"transport.vehicles","巴士":"transport.vehicles","大巴":"transport.vehicles","倒车":"transport.vehicles","电动车":"transport.vehicles",
"航空":"transport.vehicles","列车":"transport.vehicles","轮":"transport.vehicles","轮船":"transport.vehicles","轮子":"transport.vehicles","培训":"transport.vehicles",
"培育":"transport.vehicles","燃料":"transport.vehicles",
/* transport.traffic - 18 */
"乘坐":"transport.traffic","堵车":"transport.traffic","交通":"transport.traffic","速度":"transport.traffic","加油":"transport.traffic","行人":"transport.traffic",
"高速":"transport.traffic","高速公路":"transport.traffic","加快":"transport.traffic","快速":"transport.traffic","路线":"transport.traffic","事故":"transport.traffic",
"铁路":"transport.traffic","现场":"transport.traffic","意外":"transport.traffic","高铁":"transport.traffic","汽油":"transport.traffic","途中":"transport.traffic",
/* transport.travel - 18 */
"旅游":"transport.travel","出发":"transport.travel","护照":"transport.travel","行李箱":"transport.travel","导游":"transport.travel","访问":"transport.travel",
"逛":"transport.travel","签证":"transport.travel","放假":"transport.travel","假期":"transport.travel","旅行":"transport.travel","休假":"transport.travel",
"一路平安":"transport.travel","一路顺风":"transport.travel","带领":"transport.travel","旅行社":"transport.travel","行李":"transport.travel","上门":"transport.travel",
/* transport.tickets - 11 */
"票":"transport.tickets","离开":"transport.tickets","航班":"transport.tickets","座位":"transport.tickets","机票":"transport.tickets","门票":"transport.tickets",
"到达":"transport.tickets","赶紧":"transport.tickets","台阶":"transport.tickets","延期":"transport.tickets","龘":"transport.tickets",
/* tech.devices - 25 */
"电脑":"tech.devices","电视":"tech.devices","手机":"tech.devices","冰箱":"tech.devices","打印":"tech.devices","照相机":"tech.devices",
"传真":"tech.devices","技术":"tech.devices","电":"tech.devices","电话":"tech.devices","电视机":"tech.devices","关机":"tech.devices",
"计算机":"tech.devices","相机":"tech.devices","发明":"tech.devices","收音机":"tech.devices","影视":"tech.devices","自动":"tech.devices",
"充电":"tech.devices","充电器":"tech.devices","电源":"tech.devices","耳机":"tech.devices","光盘":"tech.devices","镜头":"tech.devices",
"装置":"tech.devices",
/* tech.internet - 12 */
"电子邮件":"tech.internet","上网":"tech.internet","密码":"tech.internet","网上":"tech.internet","网":"tech.internet","互联网":"tech.internet",
"结合":"tech.internet","输入":"tech.internet","数据":"tech.internet","网络":"tech.internet","下载":"tech.internet","智能":"tech.internet",
/* tech.phone - 9 */
"打电话":"tech.phone","联系":"tech.phone","留":"tech.phone","提醒":"tech.phone","短信":"tech.phone","信号":"tech.phone",
"发送":"tech.phone","微信":"tech.phone","相处":"tech.phone",
/* tech.media - 31 */
"电影":"tech.media","新闻":"tech.media","照片":"tech.media","观众":"tech.media","广播":"tech.media","广告":"tech.media",
"记者":"tech.media","消息":"tech.media","画儿":"tech.media","图片":"tech.media","信息":"tech.media","影片":"tech.media",
"播放":"tech.media","布":"tech.media","传播":"tech.media","导演":"tech.media","电视剧":"tech.media","纪录":"tech.media",
"连续剧":"tech.media","录音":"tech.media","媒体":"tech.media","听众":"tech.media","图":"tech.media","图画":"tech.media",
"宣布":"tech.media","唱片":"tech.media","动画片":"tech.media","拍照":"tech.media","系列":"tech.media","相片":"tech.media",
"罄竹难书":"tech.media",
/* sport.sports - 49 */
"打篮球":"sport.sports","踢足球":"sport.sports","游泳":"sport.sports","运动":"sport.sports","比赛":"sport.sports","踢":"sport.sports",
"体育":"sport.sports","越":"sport.sports","竞争":"sport.sports","网球":"sport.sports","赢":"sport.sports","羽毛球":"sport.sports",
"打球":"sport.sports","球":"sport.sports","队":"sport.sports","篮球":"sport.sports","爬":"sport.sports","排球":"sport.sports",
"球场":"sport.sports","球队":"sport.sports","体育场":"sport.sports","体育馆":"sport.sports","对手":"sport.sports","队员":"sport.sports",
"教练":"sport.sports","金牌":"sport.sports","决赛":"sport.sports","目标":"sport.sports","球迷":"sport.sports","人类":"sport.sports",
"胜":"sport.sports","胜利":"sport.sports","选手":"sport.sports","游":"sport.sports","足球":"sport.sports","败":"sport.sports",
"打败":"sport.sports","划":"sport.sports","获奖":"sport.sports","激烈":"sport.sports","健身":"sport.sports","奖":"sport.sports",
"体操":"sport.sports","赢得":"sport.sports","运动会":"sport.sports","运动员":"sport.sports","战胜":"sport.sports","追求":"sport.sports",
"南辕北辙":"sport.sports",
/* sport.games - 11 */
"玩":"sport.games","游戏":"sport.games","开玩笑":"sport.games","拉":"sport.games","演出":"sport.games","玩儿":"sport.games",
"话剧":"sport.games","牌":"sport.games","气球":"sport.games","亚运会":"sport.games","中奖":"sport.games",
/* sport.arts - 27 */
"唱歌":"sport.arts","跳舞":"sport.arts","表演":"sport.arts","画":"sport.arts","文化":"sport.arts","音乐":"sport.arts",
"演员":"sport.arts","艺术":"sport.arts","唱":"sport.arts","歌":"sport.arts","画家":"sport.arts","明星":"sport.arts",
"音乐会":"sport.arts","歌声":"sport.arts","功夫":"sport.arts","美术":"sport.arts","舞台":"sport.arts","演唱":"sport.arts",
"演唱会":"sport.arts","乐队":"sport.arts","制定":"sport.arts","尺子":"sport.arts","抽":"sport.arts","抽奖":"sport.arts",
"阶段":"sport.arts","台上":"sport.arts","引":"sport.arts",
/* sport.hobbies - 16 */
"爱好":"sport.hobbies","无聊":"sport.hobbies","幽默":"sport.hobbies","有趣":"sport.hobbies","好玩儿":"sport.hobbies","晚会":"sport.hobbies",
"笑话儿":"sport.hobbies","有意思":"sport.hobbies","对待":"sport.hobbies","可乐":"sport.hobbies","庆祝":"sport.hobbies","放松":"sport.hobbies",
"聚会":"sport.hobbies","乐趣":"sport.hobbies","利息":"sport.hobbies","利益":"sport.hobbies",
/* society.civic - 39 */
"法律":"society.civic","判断":"society.civic","情况":"society.civic","社会":"society.civic","正式":"society.civic","公平":"society.civic",
"平等":"society.civic","自由":"society.civic","公布":"society.civic","公共":"society.civic","公民":"society.civic","合法":"society.civic",
"和平":"society.civic","声明":"society.civic","团结":"society.civic","外交":"society.civic","证据":"society.civic","制度":"society.civic",
"状况":"society.civic","状态":"society.civic","敌人":"society.civic","法":"society.civic","法官":"society.civic","法院":"society.civic",
"风俗":"society.civic","官":"society.civic","官方":"society.civic","纪律":"society.civic","交际":"society.civic","统一":"society.civic",
"外交官":"society.civic","战斗":"society.civic","战争":"society.civic","征服":"society.civic","政府":"society.civic","政治":"society.civic",
"总理":"society.civic","囹圄":"society.civic","桎梏":"society.civic",
/* society.history - 7 */
"世纪":"society.history","改造":"society.history","古":"society.history","年代":"society.history","文明":"society.history","传统":"society.history",
"遗产":"society.history",
/* society.customs - 8 */
"习惯":"society.customs","祝":"society.customs","好事":"society.customs","传说":"society.customs","命运":"society.customs","婚礼":"society.customs",
"神话":"society.customs","暴殄天物":"society.customs",
/* society.environment - 13 */
"保护":"society.environment","节约":"society.environment","浪费":"society.environment","污染":"society.environment","人口":"society.environment","保":"society.environment",
"防":"society.environment","环保":"society.environment","开发":"society.environment","精力":"society.environment","维修":"society.environment","移民":"society.environment",
"资料":"society.environment",
/* concept.doing - 315 */
"回":"concept.doing","会":"concept.doing","叫":"concept.doing","开":"concept.doing","来":"concept.doing","没有":"concept.doing",
"能":"concept.doing","去":"concept.doing","是":"concept.doing","有":"concept.doing","做":"concept.doing","帮助":"concept.doing",
"出":"concept.doing","到":"concept.doing","等":"concept.doing","给":"concept.doing","进":"concept.doing","可以":"concept.doing",
"起床":"concept.doing","让":"concept.doing","事情":"concept.doing","送":"concept.doing","要":"concept.doing","找":"concept.doing",
"准备":"concept.doing","办法":"concept.doing","帮忙":"concept.doing","必须":"concept.doing","参加":"concept.doing","带":"concept.doing",
"不得不":"concept.doing","吃惊":"concept.doing","出生":"concept.doing","打扰":"concept.doing","没":"concept.doing","为":"concept.doing",
"分":"concept.doing","关":"concept.doing","关心":"concept.doing","过去":"concept.doing","检查":"concept.doing","借":"concept.doing",
"经过":"concept.doing","拿":"concept.doing","洗澡":"concept.doing","需要":"concept.doing","选择":"concept.doing","应该":"concept.doing",
"照顾":"concept.doing","吵":"concept.doing","掉":"concept.doing","丢":"concept.doing","断":"concept.doing","方法":"concept.doing",
"放弃":"concept.doing","负责":"concept.doing","挂":"concept.doing","获得":"concept.doing","集合":"concept.doing","寄":"concept.doing",
"交流":"concept.doing","进行":"concept.doing","举办":"concept.doing","距离":"concept.doing","肯定":"concept.doing","连":"concept.doing",
"骗":"concept.doing","起飞":"concept.doing","敲":"concept.doing","请假":"concept.doing","取":"concept.doing","扔":"concept.doing",
"伤心":"concept.doing","失败":"concept.doing","收入":"concept.doing","受到":"concept.doing","输":"concept.doing","推":"concept.doing",
"推迟":"concept.doing","脱":"concept.doing","无":"concept.doing","允许":"concept.doing","值得":"concept.doing","只好":"concept.doing",
"制造":"concept.doing","重视":"concept.doing","赚":"concept.doing","撞":"concept.doing","帮":"concept.doing","不用":"concept.doing",
"出去":"concept.doing","打":"concept.doing","打开":"concept.doing","得到":"concept.doing","动":"concept.doing","回到":"concept.doing",
"回来":"concept.doing","回去":"concept.doing","进来":"concept.doing","进去":"concept.doing","来到":"concept.doing","找到":"concept.doing",
"背":"concept.doing","笔记":"concept.doing","不要":"concept.doing","称":"concept.doing","带来":"concept.doing","倒":"concept.doing",
"等到":"concept.doing","等于":"concept.doing","放下":"concept.doing","分开":"concept.doing","该":"concept.doing","过来":"concept.doing",
"见过":"concept.doing","交给":"concept.doing","接到":"concept.doing","接下来":"concept.doing","进入":"concept.doing","就要":"concept.doing",
"举":"concept.doing","靠":"concept.doing","来自":"concept.doing","留下":"concept.doing","拿出":"concept.doing","拿到":"concept.doing",
"能够":"concept.doing","排队":"concept.doing","求":"concept.doing","取得":"concept.doing","生":"concept.doing","收到":"concept.doing",
"送到":"concept.doing","送给":"concept.doing","提":"concept.doing","通":"concept.doing","行动":"concept.doing","行为":"concept.doing",
"选":"concept.doing","占":"concept.doing","找出":"concept.doing","照相":"concept.doing","走进":"concept.doing","做法":"concept.doing",
"安装":"concept.doing","按":"concept.doing","把握":"concept.doing","保持":"concept.doing","保留":"concept.doing","表现":"concept.doing",
"不必":"concept.doing","采取":"concept.doing","产生":"concept.doing","吵架":"concept.doing","称为":"concept.doing","传":"concept.doing",
"创造":"concept.doing","从事":"concept.doing","存在":"concept.doing","打破":"concept.doing","等待":"concept.doing","发言":"concept.doing",
"方式":"concept.doing","分配":"concept.doing","分组":"concept.doing","否认":"concept.doing","赶":"concept.doing","公开":"concept.doing",
"管":"concept.doing","合":"concept.doing","合作":"concept.doing","建成":"concept.doing","建设":"concept.doing","接近":"concept.doing",
"解开":"concept.doing","进一步":"concept.doing","进展":"concept.doing","救":"concept.doing","具有":"concept.doing","开放":"concept.doing",
"克服":"concept.doing","利用":"concept.doing","联合":"concept.doing","领":"concept.doing","领导":"concept.doing","满足":"concept.doing",
"配":"concept.doing","配合":"concept.doing","破坏":"concept.doing","普及":"concept.doing","前进":"concept.doing","前往":"concept.doing",
"上来":"concept.doing","上去":"concept.doing","失去":"concept.doing","实行":"concept.doing","适用":"concept.doing","属于":"concept.doing",
"随":"concept.doing","推进":"concept.doing","推开":"concept.doing","下来":"concept.doing","下去":"concept.doing","显示":"concept.doing",
"相关":"concept.doing","宣传":"concept.doing","压":"concept.doing","应当":"concept.doing","有的是":"concept.doing","预防":"concept.doing",
"约":"concept.doing","运输":"concept.doing","造":"concept.doing","造成":"concept.doing","展开":"concept.doing","争":"concept.doing",
"争取":"concept.doing","制作":"concept.doing","抓":"concept.doing","抓住":"concept.doing","追":"concept.doing","组合":"concept.doing",
"摆动":"concept.doing","摆脱":"concept.doing","包裹":"concept.doing","保密":"concept.doing","被迫":"concept.doing","避":"concept.doing",
"避免":"concept.doing","编":"concept.doing","参与":"concept.doing","测":"concept.doing","测量":"concept.doing","抄":"concept.doing",
"抄写":"concept.doing","沉":"concept.doing","承担":"concept.doing","出席":"concept.doing","措施":"concept.doing","倒闭":"concept.doing",
"翻":"concept.doing","非":"concept.doing","分布":"concept.doing","分散":"concept.doing","奋斗":"concept.doing","封闭":"concept.doing",
"复制":"concept.doing","感兴趣":"concept.doing","隔":"concept.doing","隔开":"concept.doing","光临":"concept.doing","归":"concept.doing",
"忽视":"concept.doing","获":"concept.doing","获取":"concept.doing","即将":"concept.doing","降":"concept.doing","交换":"concept.doing",
"结":"concept.doing","节省":"concept.doing","紧密":"concept.doing","尽力":"concept.doing","具备":"concept.doing","卷":"concept.doing",
"拉开":"concept.doing","量":"concept.doing","疗养":"concept.doing","列入":"concept.doing","列为":"concept.doing","流传":"concept.doing",
"落":"concept.doing","没法儿":"concept.doing","密切":"concept.doing","面试":"concept.doing","亲密":"concept.doing","上楼":"concept.doing",
"设置":"concept.doing","实施":"concept.doing","收回":"concept.doing","率先":"concept.doing","挑选":"concept.doing","挑战":"concept.doing",
"贴":"concept.doing","投":"concept.doing","投入":"concept.doing","维持":"concept.doing","维护":"concept.doing","位于":"concept.doing",
"问候":"concept.doing","无所谓":"concept.doing","下降":"concept.doing","下楼":"concept.doing","演讲":"concept.doing","遇":"concept.doing",
"遇见":"concept.doing","运用":"concept.doing","在于":"concept.doing","折":"concept.doing","针对":"concept.doing","指挥":"concept.doing",
"抓紧":"concept.doing","自信":"concept.doing","阻止":"concept.doing","作出":"concept.doing","做梦":"concept.doing","踟蹰":"concept.doing",
"婆娑":"concept.doing","商榷":"concept.doing","掣肘":"concept.doing","沆瀣一气":"concept.doing","铩羽而归":"concept.doing","文以载道":"concept.doing",
"咎由自取":"concept.doing","江郎才尽":"concept.doing","切中肯綮":"concept.doing",
/* concept.thinking - 77 */
"说":"concept.thinking","想":"concept.thinking","告诉":"concept.thinking","觉得":"concept.thinking","说话":"concept.thinking","意思":"concept.thinking",
"表示":"concept.thinking","根据":"concept.thinking","故事":"concept.thinking","其实":"concept.thinking","以为":"concept.thinking","云":"concept.thinking",
"表达":"concept.thinking","对话":"concept.thinking","考虑":"concept.thinking","理想":"concept.thinking","聊天":"concept.thinking","目的":"concept.thinking",
"难道":"concept.thinking","商量":"concept.thinking","实在":"concept.thinking","谈":"concept.thinking","讨论":"concept.thinking","通知":"concept.thinking",
"至少":"concept.thinking","道理":"concept.thinking","观点":"concept.thinking","喊":"concept.thinking","讲话":"concept.thinking","角度":"concept.thinking",
"叫作":"concept.thinking","例子":"concept.thinking","提出":"concept.thinking","提到":"concept.thinking","想到":"concept.thinking","想起":"concept.thinking",
"小声":"concept.thinking","心中":"concept.thinking","创新":"concept.thinking","概念":"concept.thinking","观念":"concept.thinking","建议":"concept.thinking",
"较":"concept.thinking","据说":"concept.thinking","看起来":"concept.thinking","强调":"concept.thinking","实际上":"concept.thinking","事实":"concept.thinking",
"事实上":"concept.thinking","思想":"concept.thinking","谈话":"concept.thinking","意义":"concept.thinking","指出":"concept.thinking","志愿":"concept.thinking",
"暗示":"concept.thinking","辩论":"concept.thinking","承认":"concept.thinking","促进":"concept.thinking","含义":"concept.thinking","回复":"concept.thinking",
"结论":"concept.thinking","看来":"concept.thinking","快递":"concept.thinking","来源":"concept.thinking","梦想":"concept.thinking","描述":"concept.thinking",
"描写":"concept.thinking","说不定":"concept.thinking","思考":"concept.thinking","想象":"concept.thinking","形容":"concept.thinking","议论":"concept.thinking",
"原则":"concept.thinking","争论":"concept.thinking","转告":"concept.thinking","不刊之论":"concept.thinking","弦外之音":"concept.thinking",
/* concept.change - 107 */
"开始":"concept.change","完":"concept.change","变化":"concept.change","出现":"concept.change","成功":"concept.change","成为":"concept.change",
"发现":"concept.change","结束":"concept.change","解决":"concept.change","使":"concept.change","提高":"concept.change","完成":"concept.change",
"影响":"concept.change","作用":"concept.change","发生":"concept.change","发展":"concept.change","改变":"concept.change","积累":"concept.change",
"继续":"concept.change","减少":"concept.change","降低":"concept.change","扩大":"concept.change","适应":"concept.change","停止":"concept.change",
"养成":"concept.change","引起":"concept.change","原因":"concept.change","增加":"concept.change","增长":"concept.change","出来":"concept.change",
"起":"concept.change","变":"concept.change","变成":"concept.change","成":"concept.change","得出":"concept.change","改":"concept.change",
"接着":"concept.change","开机":"concept.change","流":"concept.change","实现":"concept.change","停":"concept.change","长大":"concept.change",
"做到":"concept.change","保存":"concept.change","变为":"concept.change","补充":"concept.change","成就":"concept.change","成立":"concept.change",
"成长":"concept.change","持续":"concept.change","创业":"concept.change","创作":"concept.change","达到":"concept.change","代":"concept.change",
"带动":"concept.change","动力":"concept.change","发动":"concept.change","反应":"concept.change","改进":"concept.change","功能":"concept.change",
"后果":"concept.change","加强":"concept.change","建":"concept.change","建立":"concept.change","进步":"concept.change","开展":"concept.change",
"看上去":"concept.change","上升":"concept.change","设立":"concept.change","升":"concept.change","生产":"concept.change","生存":"concept.change",
"生长":"concept.change","事件":"concept.change","体现":"concept.change","调整":"concept.change","推广":"concept.change","完整":"concept.change",
"危害":"concept.change","消失":"concept.change","修改":"concept.change","演":"concept.change","有效":"concept.change","转变":"concept.change",
"促使":"concept.change","导致":"concept.change","动摇":"concept.change","发挥":"concept.change","改善":"concept.change","加入":"concept.change",
"减":"concept.change","降温":"concept.change","扩展":"concept.change","末":"concept.change","培养":"concept.change","破产":"concept.change",
"趋势":"concept.change","缩短":"concept.change","缩小":"concept.change","替代":"concept.change","停下":"concept.change","吸收":"concept.change",
"延长":"concept.change","延续":"concept.change","一蹴而就":"concept.change","附庸风雅":"concept.change","刻舟求剑":"concept.change",
/* concept.quantity - 176 */
"八":"concept.quantity","都":"concept.quantity","多":"concept.quantity","多少":"concept.quantity","二":"concept.quantity","很":"concept.quantity",
"几":"concept.quantity","九":"concept.quantity","六":"concept.quantity","七":"concept.quantity","三":"concept.quantity","少":"concept.quantity",
"十":"concept.quantity","四":"concept.quantity","太":"concept.quantity","五":"concept.quantity","些":"concept.quantity","一":"concept.quantity",
"百":"concept.quantity","第一":"concept.quantity","非常":"concept.quantity","两":"concept.quantity","零":"concept.quantity","每":"concept.quantity",
"千":"concept.quantity","真":"concept.quantity","最":"concept.quantity","矮":"concept.quantity","半":"concept.quantity","比较":"concept.quantity",
"短":"concept.quantity","百分之":"concept.quantity","部分":"concept.quantity","差不多":"concept.quantity","超过":"concept.quantity","多么":"concept.quantity",
"更":"concept.quantity","几乎":"concept.quantity","双":"concept.quantity","万":"concept.quantity","一定":"concept.quantity","一共":"concept.quantity",
"包括":"concept.quantity","大概":"concept.quantity","大约":"concept.quantity","范围":"concept.quantity","各":"concept.quantity","个子":"concept.quantity",
"够":"concept.quantity","估计":"concept.quantity","果然":"concept.quantity","号码":"concept.quantity","极其":"concept.quantity","减肥":"concept.quantity",
"俩":"concept.quantity","满":"concept.quantity","千万":"concept.quantity","全部":"concept.quantity","确实":"concept.quantity","稍微":"concept.quantity",
"甚至":"concept.quantity","十分":"concept.quantity","数量":"concept.quantity","数字":"concept.quantity","所有":"concept.quantity","完全":"concept.quantity",
"限制":"concept.quantity","许多":"concept.quantity","也许":"concept.quantity","一切":"concept.quantity","尤其":"concept.quantity","半天":"concept.quantity",
"别的":"concept.quantity","不大":"concept.quantity","一半":"concept.quantity","一点儿":"concept.quantity","一块儿":"concept.quantity","一些":"concept.quantity",
"有的":"concept.quantity","有些":"concept.quantity","真的":"concept.quantity","不太":"concept.quantity","不够":"concept.quantity","不少":"concept.quantity",
"不一定":"concept.quantity","大部分":"concept.quantity","大大":"concept.quantity","大量":"concept.quantity","大小":"concept.quantity","多数":"concept.quantity",
"好多":"concept.quantity","加":"concept.quantity","全":"concept.quantity","全体":"concept.quantity","人数":"concept.quantity","少数":"concept.quantity",
"数":"concept.quantity","一部分":"concept.quantity","一点点":"concept.quantity","有点儿":"concept.quantity","越来越":"concept.quantity","这么":"concept.quantity",
"只能":"concept.quantity","北部":"concept.quantity","比例":"concept.quantity","不光":"concept.quantity","超级":"concept.quantity","充满":"concept.quantity",
"分别":"concept.quantity","告别":"concept.quantity","各位":"concept.quantity","各种":"concept.quantity","各自":"concept.quantity","更加":"concept.quantity",
"共有":"concept.quantity","基本上":"concept.quantity","计算":"concept.quantity","简直":"concept.quantity","将近":"concept.quantity","仅":"concept.quantity",
"仅仅":"concept.quantity","尽量":"concept.quantity","力":"concept.quantity","力量":"concept.quantity","某":"concept.quantity","南部":"concept.quantity",
"排名":"concept.quantity","全球":"concept.quantity","实力":"concept.quantity","西部":"concept.quantity","相比":"concept.quantity","相当":"concept.quantity",
"整个":"concept.quantity","整整":"concept.quantity","只是":"concept.quantity","足够":"concept.quantity","包含":"concept.quantity","尺寸":"concept.quantity",
"充分":"concept.quantity","处于":"concept.quantity","大多":"concept.quantity","单独":"concept.quantity","登":"concept.quantity","的确":"concept.quantity",
"独自":"concept.quantity","对比":"concept.quantity","多年":"concept.quantity","多种":"concept.quantity","分为":"concept.quantity","格外":"concept.quantity",
"个别":"concept.quantity","各个":"concept.quantity","规模":"concept.quantity","过分":"concept.quantity","含有":"concept.quantity","或许":"concept.quantity",
"巨大":"concept.quantity","平均":"concept.quantity","身材":"concept.quantity","使劲":"concept.quantity","数码":"concept.quantity","似乎":"concept.quantity",
"统计":"concept.quantity","未必":"concept.quantity","无数":"concept.quantity","无限":"concept.quantity","小型":"concept.quantity","一般来说":"concept.quantity",
"以内":"concept.quantity","有限":"concept.quantity","之一":"concept.quantity","重量":"concept.quantity","综合":"concept.quantity","总共":"concept.quantity",
"作为":"concept.quantity","高屋建瓴":"concept.quantity",
/* concept.quality - 243 */
"大":"concept.quality","好":"concept.quality","小":"concept.quality","长":"concept.quality","错":"concept.quality","高":"concept.quality",
"可能":"concept.quality","快":"concept.quality","慢":"concept.quality","新":"concept.quality","安静":"concept.quality","安全":"concept.quality",
"棒":"concept.quality","低":"concept.quality","方便":"concept.quality","坏":"concept.quality","机会":"concept.quality","简单":"concept.quality",
"旧":"concept.quality","明白":"concept.quality","难":"concept.quality","难过":"concept.quality","年轻":"concept.quality","努力":"concept.quality",
"奇怪":"concept.quality","清楚":"concept.quality","容易":"concept.quality","特别":"concept.quality","相同":"concept.quality","相信":"concept.quality",
"一般":"concept.quality","一直":"concept.quality","有名":"concept.quality","重要":"concept.quality","主要":"concept.quality","暗":"concept.quality",
"复杂":"concept.quality","共同":"concept.quality","故意":"concept.quality","关键":"concept.quality","好处":"concept.quality","合适":"concept.quality",
"厚":"concept.quality","基础":"concept.quality","假":"concept.quality","精彩":"concept.quality","竟然":"concept.quality","宽":"concept.quality",
"困难":"concept.quality","厉害":"concept.quality","亮":"concept.quality","乱":"concept.quality","麻烦":"concept.quality","破":"concept.quality",
"普遍":"concept.quality","区别":"concept.quality","缺点":"concept.quality","缺少":"concept.quality","软":"concept.quality","深":"concept.quality",
"顺便":"concept.quality","顺利":"concept.quality","特点":"concept.quality","条件":"concept.quality","挺":"concept.quality","危险":"concept.quality",
"详细":"concept.quality","辛苦":"concept.quality","硬":"concept.quality","优点":"concept.quality","优秀":"concept.quality","圆":"concept.quality",
"脏":"concept.quality","窄":"concept.quality","真正":"concept.quality","整齐":"concept.quality","正常":"concept.quality","直接":"concept.quality",
"重点":"concept.quality","著名":"concept.quality","准确":"concept.quality","最好":"concept.quality","不对":"concept.quality","好看":"concept.quality",
"好听":"concept.quality","有用":"concept.quality","正":"concept.quality","不错":"concept.quality","不如":"concept.quality","不同":"concept.quality",
"不行":"concept.quality","常见":"concept.quality","常用":"concept.quality","大多数":"concept.quality","大声":"concept.quality","刚":"concept.quality",
"坏处":"concept.quality","卡":"concept.quality","难题":"concept.quality","难听":"concept.quality","平":"concept.quality","平安":"concept.quality",
"平常":"concept.quality","普通":"concept.quality","挺好":"concept.quality","同样":"concept.quality","保险":"concept.quality","必然":"concept.quality",
"必要":"concept.quality","表明":"concept.quality","长处":"concept.quality","场合":"concept.quality","短处":"concept.quality","发达":"concept.quality",
"风险":"concept.quality","根本":"concept.quality","广大":"concept.quality","好好":"concept.quality","合理":"concept.quality","基本":"concept.quality",
"价值":"concept.quality","坚强":"concept.quality","结实":"concept.quality","具体":"concept.quality","绝对":"concept.quality","客观":"concept.quality",
"空":"concept.quality","类似":"concept.quality","毛病":"concept.quality","没用":"concept.quality","明确":"concept.quality","明显":"concept.quality",
"木头":"concept.quality","能不能":"concept.quality","齐":"concept.quality","强":"concept.quality","强大":"concept.quality","强烈":"concept.quality",
"巧":"concept.quality","确定":"concept.quality","深刻":"concept.quality","深入":"concept.quality","生动":"concept.quality","属":"concept.quality",
"特色":"concept.quality","通常":"concept.quality","突出":"concept.quality","团":"concept.quality","完美":"concept.quality","完善":"concept.quality",
"伟大":"concept.quality","先进":"concept.quality","显然":"concept.quality","现实":"concept.quality","相似":"concept.quality","优势":"concept.quality",
"有利":"concept.quality","真实":"concept.quality","直":"concept.quality","重大":"concept.quality","总":"concept.quality","矮小":"concept.quality",
"宝贵":"concept.quality","背景":"concept.quality","长途":"concept.quality","彻底":"concept.quality","沉重":"concept.quality","出色":"concept.quality",
"纯":"concept.quality","粗":"concept.quality","大规模":"concept.quality","大型":"concept.quality","单纯":"concept.quality","单调":"concept.quality",
"典型":"concept.quality","独特":"concept.quality","多样":"concept.quality","反":"concept.quality","肥":"concept.quality","风格":"concept.quality",
"公元":"concept.quality","共":"concept.quality","构造":"concept.quality","怪":"concept.quality","黑暗":"concept.quality","机遇":"concept.quality",
"结构":"concept.quality","尽快":"concept.quality","局":"concept.quality","宽广":"concept.quality","离不开":"concept.quality","良好":"concept.quality",
"了不起":"concept.quality","密":"concept.quality","秘密":"concept.quality","名牌儿":"concept.quality","默默":"concept.quality","难免":"concept.quality",
"闹":"concept.quality","浓":"concept.quality","片面":"concept.quality","平稳":"concept.quality","清醒":"concept.quality","轻易":"concept.quality",
"弱":"concept.quality","善于":"concept.quality","深厚":"concept.quality","神秘":"concept.quality","实用":"concept.quality","随手":"concept.quality",
"特殊":"concept.quality","特征":"concept.quality","透明":"concept.quality","稳":"concept.quality","稳定":"concept.quality","无法":"concept.quality",
"细":"concept.quality","细节":"concept.quality","系统":"concept.quality","细致":"concept.quality","鲜明":"concept.quality","显著":"concept.quality",
"型":"concept.quality","型号":"concept.quality","形势":"concept.quality","严":"concept.quality","一律":"concept.quality","一致":"concept.quality",
"优良":"concept.quality","优美":"concept.quality","有劲儿":"concept.quality","圆满":"concept.quality","运气":"concept.quality","龌龊":"concept.quality",
"邋遢":"concept.quality","璀璨":"concept.quality","症结":"concept.quality","参差":"concept.quality","良莠不齐":"concept.quality","管窥蠡测":"concept.quality",
"曲高和寡":"concept.quality","殊途同归":"concept.quality","一针见血":"concept.quality",
/* grammar.measure - 23 */
"本":"grammar.measure","件":"grammar.measure","一下":"grammar.measure","遍":"grammar.measure","场":"grammar.measure","公斤":"grammar.measure",
"元":"grammar.measure","张":"grammar.measure","杯":"grammar.measure","间":"grammar.measure","单位":"grammar.measure","度":"grammar.measure",
"封":"grammar.measure","节":"grammar.measure","斤":"grammar.measure","句":"grammar.measure","克":"grammar.measure","排":"grammar.measure",
"片":"grammar.measure","千克":"grammar.measure","套":"grammar.measure","周":"grammar.measure","单元":"grammar.measure",
/* grammar.particles - 104 */
"不":"grammar.particles","的":"grammar.particles","个":"grammar.particles","了":"grammar.particles","吗":"grammar.particles","呢":"grammar.particles",
"在":"grammar.particles","吧":"grammar.particles","比":"grammar.particles","别":"grammar.particles","从":"grammar.particles","得":"grammar.particles",
"对":"grammar.particles","过":"grammar.particles","离":"grammar.particles","它":"grammar.particles","往":"grammar.particles","着":"grammar.particles",
"正在":"grammar.particles","把":"grammar.particles","被":"grammar.particles","不但":"grammar.particles","地":"grammar.particles","爱情":"grammar.particles",
"按照":"grammar.particles","并且":"grammar.particles","不仅":"grammar.particles","向":"grammar.particles","啊":"grammar.particles","跟":"grammar.particles",
"关于":"grammar.particles","角":"grammar.particles","刻":"grammar.particles","口":"grammar.particles","辆":"grammar.particles","米":"grammar.particles",
"条":"grammar.particles","位":"grammar.particles","为了":"grammar.particles","只":"grammar.particles","自己":"grammar.particles","当":"grammar.particles",
"顿":"grammar.particles","朵":"grammar.particles","分之":"grammar.particles","份":"grammar.particles","公里":"grammar.particles","既然":"grammar.particles",
"棵":"grammar.particles","另外":"grammar.particles","篇":"grammar.particles","其次":"grammar.particles","群":"grammar.particles","任何":"grammar.particles",
"随着":"grammar.particles","通过":"grammar.particles","行":"grammar.particles","页":"grammar.particles","以":"grammar.particles","亿":"grammar.particles",
"因此":"grammar.particles","由":"grammar.particles","由于":"grammar.particles","于是":"grammar.particles","之":"grammar.particles","座":"grammar.particles",
"第":"grammar.particles","们":"grammar.particles","子":"grammar.particles","正是":"grammar.particles","不论":"grammar.particles","传来":"grammar.particles",
"哈哈":"grammar.particles","化":"grammar.particles","架":"grammar.particles","就是":"grammar.particles","另一方面":"grammar.particles","期":"grammar.particles",
"束":"grammar.particles","性":"grammar.particles","员":"grammar.particles","支":"grammar.particles","只有":"grammar.particles","自从":"grammar.particles",
"对于":"grammar.particles","而是":"grammar.particles","根":"grammar.particles","毫米":"grammar.particles","毫升":"grammar.particles","户":"grammar.particles",
"伙":"grammar.particles","可见":"grammar.particles","厘米":"grammar.particles","其余":"grammar.particles","人家":"grammar.particles","首":"grammar.particles",
"晚点":"grammar.particles","箱":"grammar.particles","项":"grammar.particles","以及":"grammar.particles","阵":"grammar.particles","转身":"grammar.particles",
"自":"grammar.particles","总之":"grammar.particles",
/* grammar.connectives - 50 */
"和":"grammar.connectives","虽然":"grammar.connectives","也":"grammar.connectives","一起":"grammar.connectives","因为":"grammar.connectives","除了":"grammar.connectives",
"比如":"grammar.connectives","不管":"grammar.connectives","不过":"grammar.connectives","但是":"grammar.connectives","所以":"grammar.connectives","而且":"grammar.connectives",
"或者":"grammar.connectives","其他":"grammar.connectives","然后":"grammar.connectives","如果":"grammar.connectives","一会儿":"grammar.connectives","而":"grammar.connectives",
"否则":"grammar.connectives","互相":"grammar.connectives","即使":"grammar.connectives","尽管":"grammar.connectives","可是":"grammar.connectives","例如":"grammar.connectives",
"然而":"grammar.connectives","趟":"grammar.connectives","无论":"grammar.connectives","呀":"grammar.connectives","与":"grammar.connectives","咱们":"grammar.connectives",
"只要":"grammar.connectives","还有":"grammar.connectives","比如说":"grammar.connectives","但":"grammar.connectives","的话":"grammar.connectives","或":"grammar.connectives",
"那么":"grammar.connectives","并":"grammar.connectives","朝":"grammar.connectives","反正":"grammar.connectives","相互":"grammar.connectives","要是":"grammar.connectives",
"者":"grammar.connectives","不然":"grammar.connectives","此外":"grammar.connectives","反而":"grammar.connectives","假如":"grammar.connectives","哪怕":"grammar.connectives",
"似的":"grammar.connectives","万一":"grammar.connectives",
/* grammar.questions - 18 */
"哪":"grammar.questions","谁":"grammar.questions","什么":"grammar.questions","怎么":"grammar.questions","怎么样":"grammar.questions","为什么":"grammar.questions",
"干什么":"grammar.questions","哪里":"grammar.questions","哪儿":"grammar.questions","哪些":"grammar.questions","是不是":"grammar.questions","多久":"grammar.questions",
"什么样":"grammar.questions","怎么办":"grammar.questions","怎样":"grammar.questions","干吗":"grammar.questions","如何":"grammar.questions","是否":"grammar.questions",
};
