/* ============================================================
   WORD DATA v2 - HSK 3.0 additions
   [character, pinyin (tone numbers), english, HSK level, part of speech]

   Same entry shape as WORDS in data.js. These are the words in HSK 3.0
   bands 1-4 that are NOT already present anywhere in WORDS, so the two
   lists can be concatenated without producing duplicates.

   Standard:  HSK 3.0, CTI exam syllabus published November 2025
              (pilot 31 Jan 2026, full rollout expected July 2026).
              Cumulative band sizes: 300 / 500 / 1000 / 2000.
              Supersedes HSK 2.0 (150/300/600/1200), which is what
              WORDS in data.js is built on.

   Sources:   band membership + glosses - hskstory.com band PDFs
              pinyin / part of speech   - github.com/drkameleon/
                                          complete-hsk-vocabulary (MIT)

   Caveat:    the source band lists run slightly short of the official
              counts (300/197/493/990 against 300/200/500/1000) because
              variant forms are de-duplicated.

   See RELEVEL_V2 at the foot of this file for words already in WORDS
   whose band changed under HSK 3.0.
   ============================================================ */
const WORDS_V2=[
/* ---- HSK 1 v2 - 93 words absent from data.js (band 1: 300 listed, 300 cumulative) ---- */
["一些","yi1xie1","some / a few",1,"function"],["一半","yi1ban4","half",1,"function"],
["一点儿","yi1dian3r5","a bit / a little bit",1,"function"],
["上学","shang4xue2","to go to school / to attend school",1,"verb"],
["上课","shang4ke4","to go to class / to attend class",1,"verb"],
["下班","xia4ban1","to finish work / to get off work",1,"verb"],
["下课","xia4ke4","to finish class / to get out of class",1,"verb"],["不要","bu4yao4","don't! / must not",1,"adv"],
["中学","zhong1xue2","middle school",1,"noun"],["中学生","zhong1xue2sheng1","middle-school student",1,"noun"],
["中文","zhong1wen2","Chinese language",1,"noun"],["书店","shu1dian4","bookstore",1,"noun"],
["事","shi4","matter / thing",1,"noun"],["今年","jin1nian2","this year",1,"noun"],
["他们","ta1men5","they / them",1,"pronoun"],
["们","men5","plural marker for pronouns, and nouns referring",1,"function"],["你们","ni3men5","you",1,"pronoun"],
["你好","ni3hao3","hello / hi",1,"noun"],["做饭","zuo4fan4","to prepare a meal / to cook",1,"verb"],
["元","yuan2","currency unit / first",1,"function"],["分","fen1","to divide / to separate",1,"verb"],
["前","qian2","front / forward",1,"noun"],["午饭","wu3fan4","lunch",1,"noun"],["口","kou3","mouth",1,"function"],
["只","zhi3","only / merely",1,"adv"],["后","hou4","empress / queen",1,"noun"],["听见","ting1jian4","to hear",1,"verb"],
["哪个","na3ge5","which / who",1,"noun"],["哪些","na3xie1","which ones? / who?",1,"pronoun"],
["哪儿","na3r5","where? / wherever",1,"pronoun"],["哪里","na3li3","where? / somewhere",1,"pronoun"],
["唱","chang4","to sing / to call loudly",1,"verb"],["国","guo2","country / nation",1,"noun"],
["外边","wai4bian5","outside / outer surface",1,"noun"],["大学","da4xue2","university / college",1,"noun"],
["大学生","da4xue2sheng1","university student",1,"noun"],["天","tian1","day / sky",1,"noun"],
["女士","nv3shi4","lady / madam",1,"noun"],["女朋友","nv3peng2you5","girlfriend",1,"noun"],
["她们","ta1men5","they / them",1,"pronoun"],["好听","hao3ting1","pleasant to hear",1,"adj"],
["好玩儿","hao3wan2r5","amusing",1,"adj"],["好看","hao3kan4","good-looking / nice-looking",1,"adj"],
["学","xue2","to learn / to study",1,"verb"],["它们","ta1men5","they / them",1,"pronoun"],
["家人","jia1ren2","family member / servant",1,"noun"],["小学","xiao3xue2","elementary school / primary school",1,"noun"],
["小学生","xiao3xue2sheng1","primary school student",1,"noun"],["小朋友","xiao3peng2you3","child",1,"noun"],
["店","dian4","inn / old-style hotel",1,"noun"],["开车","kai1che1","to drive a car",1,"verb"],
["早","zao3","early / morning",1,"adj"],["早饭","zao3fan4","breakfast",1,"noun"],
["明年","ming2nian2","next year",1,"noun"],["星期天","xing1qi1tian1","Sunday",1,"noun"],
["星期日","xing1qi1ri4","Sunday",1,"noun"],["晚","wan3","evening / night",1,"noun"],
["晚饭","wan3fan4","evening meal / dinner",1,"noun"],["有点儿","you3dian3r5","slightly / a little",1,"noun"],
["有些","you3xie1","some / somewhat",1,"pronoun"],["有的","you3de5","(there are) some / some",1,"pronoun"],
["歌","ge1","song / to sing",1,"noun"],["汉字","han4zi4","Chinese character",1,"noun"],
["没事","mei2shi4","it's not important",1,"noun"],["火车","huo3che1","train",1,"noun"],
["电影院","dian4ying3yuan4","cinema / movie theater",1,"noun"],["电话","dian4hua4","telephone / phone call",1,"noun"],
["男朋友","nan2peng2you5","boyfriend",1,"noun"],["病","bing4","illness / disease",1,"noun"],
["白天","bai2tian1","daytime / during the day",1,"noun"],
["看病","kan4bing4","to visit a doctor / to see a patient",1,"verb"],["睡","shui4","to sleep / to lie down",1,"verb"],
["第","di4","grades in which successful candidates in the imp",1,"function"],["见","jian4","to see / to meet",1,"verb"],
["请问","qing3wen4","Excuse me, may I ask...?",1,"verb"],["读书","du2shu1","to read a book / to study",1,"verb"],
["车","che1","car / vehicle",1,"noun"],["边","bian1","side / edge",1,"function"],
["这个","zhe4ge5","(pronoun) this / (adjective) this",1,"noun"],["这些","zhe4xie1","these",1,"pronoun"],
["这儿","zhe4r5","here",1,"pronoun"],["这边","zhe4bian1","this side / here",1,"pronoun"],
["这里","zhe4li3","here",1,"pronoun"],["那个","na4ge5","that one / that thing",1,"noun"],
["那些","na4xie1","those",1,"pronoun"],["那儿","na4r5","there",1,"pronoun"],
["那边","na4bian5","over there / yonder",1,"pronoun"],["那里","na4li5","there / that place",1,"pronoun"],
["雨","yu3","rain",1,"noun"],["面包","mian4bao1","bread",1,"noun"],["面条儿","mian4tiao2r5","noodles",1,"noun"],
["饭","fan4","cooked rice / meal",1,"noun"],["饺子","jiao3zi5","dumpling / pot-sticker",1,"noun"],
/* ---- HSK 2 v2 - 117 words absent from data.js (band 2: 197 listed, 500 cumulative) ---- */
["一会儿","yi1hui4r5","a moment / a while",2,"function"],["万","wan4","ten thousand / a great number",2,"function"],
["上去","shang4qu4","to go up",2,"verb"],["上来","shang4lai2","to come up / to approach",2,"verb"],
["上网","shang4wang3","to go online / to connect to the Internet",2,"verb"],
["上面","shang4mian4","on top of / above-mentioned",2,"noun"],["下去","xia4qu4","to go down / to descend",2,"verb"],
["下来","xia4lai5","to come down / (completed action marker)",2,"verb"],["下面","xia4mian4","below / under",2,"noun"],
["不好意思","bu4hao3yi4si5","to feel embarrassed",2,"verb"],["不错","bu4cuo4","correct / right",2,"adj"],
["个子","ge4zi5","stature / height",2,"noun"],["书包","shu1bao1","schoolbag / satchel",2,"noun"],
["从小","cong2xiao3","from childhood / from a young age",2,"adv"],["但","dan4","but / yet",2,"function"],
["但是","dan4shi4","but / however",2,"function"],["位","wei4","position / location",2,"function"],
["公交车","gong1jiao1che1","public transport vehicle",2,"noun"],["出去","chu1qu4","to go out",2,"verb"],
["出国","chu1guo2","to go abroad / to leave the country",2,"verb"],["出来","chu1lai2","to come out / to appear",2,"verb"],
["出门","chu1men2","to go out / to leave home",2,"verb"],["动","dong4","(of sth) to move / to set in movement",2,"verb"],
["右","you4","right / right-hand side",2,"noun"],["名","ming2","name / noun",2,"function"],
["周","zhou1","to make a circuit / to circle",2,"verb"],
["商场","shang1chang3","shopping mall / shopping center",2,"noun"],
["啊","a5","modal particle ending sentence, showing affirmat",2,"function"],
["回去","hui2qu5","to return / to go back",2,"verb"],["回来","hui2lai5","to return / to come back",2,"verb"],
["坏","huai4","bad / spoiled",2,"adj"],["外国","wai4guo2","foreign country",2,"noun"],
["外面","wai4mian4","outside / surface",2,"noun"],["头","tou2","head / hair style",2,"noun"],
["女孩儿","nv3hai2r5","girl",2,"noun"],["奶奶","nai3nai5","(informal) grandma",2,"noun"],
["奶茶","nai3cha2","milk tea",2,"noun"],["姓名","xing4ming2","full name",2,"noun"],["小孩儿","xiao3hai2r5","child",2,"noun"],
["小时候","xiao3shi2hou5","in one's childhood",2,"noun"],["左","zuo3","left / the Left",2,"noun"],
["帮","bang1","to help / to assist",2,"verb"],["床","chuang2","bed",2,"noun"],
["开学","kai1xue2","(of a student) to start school",2,"verb"],["忘","wang4","to forget / to overlook",2,"verb"],
["快要","kuai4yao4","nearly at the point of",2,"adv"],["所以","suo3yi3","therefore / as a result",2,"function"],
["手","shou3","hand / (formal) to hold",2,"noun"],
["打","da3","a semantically light, transitive verb that is co",2,"verb"],["打开","da3kai1","to open / to show",2,"verb"],
["打车","da3che1","to take a taxi / to hitch a lift",2,"verb"],["拿","na2","to hold / to seize",2,"verb"],
["教","jiao4","to teach / to instruct",2,"verb"],["时","shi2","o'clock / time",2,"noun"],
["有意思","you3yi4si5","interesting / meaningful",2,"noun"],["有时","you3shi2","sometimes / now and then",2,"adv"],
["本子","ben3zi5","book / notebook",2,"noun"],["机票","ji1piao4","plane ticket / airline ticket",2,"noun"],
["条","tiao2","strip / item",2,"function"],["楼","lou2","house with more than 1 story",2,"noun"],
["正","zheng4","straight / upright",2,"adv"],["没意思","mei2yi4si5","boring / of no interest",2,"noun"],
["洗手间","xi3shou3jian1","toilet / lavatory",2,"noun"],["游","you2","to swim",2,"verb"],
["爷爷","ye2ye5","paternal grandfather",2,"noun"],["球","qiu2","ball used for playing games",2,"noun"],
["男孩儿","nan2hai2r5","boy",2,"noun"],["画","hua4","to draw / to paint",2,"verb"],
["疼","teng2","(it) hurts / sore",2,"adj"],["白色","bai2se4","white / fig. reactionary",2,"noun"],
["站","zhan4","station / to stand",2,"verb"],["笔","bi3","writing brush",2,"function"],
["篮球","lan2qiu2","basketball",2,"noun"],["红色","hong2se4","red / revolutionary",2,"noun"],
["红茶","hong2cha2","black tea",2,"noun"],["经常","jing1chang2","frequently / constantly",2,"adv"],
["绿色","lv4se4","green",2,"noun"],["绿茶","lv4cha2","green tea",2,"noun"],["网上","wang3shang4","online",2,"noun"],
["考","kao3","to beat / to hit",2,"verb"],["肉","rou4","meat / flesh",2,"noun"],
["自己","zi4ji3","oneself / one's own",2,"pronoun"],["舒服","shu1fu5","comfortable / feeling well",2,"adj"],
["花","hua1","flower / blossom",2,"adj"],["药店","yao4dian4","pharmacy / drugstore",2,"noun"],
["裤子","ku4zi5","pants / trousers",2,"noun"],["记得","ji4de5","to remember",2,"verb"],
["词","ci2","word / statement",2,"noun"],["走路","zou3lu4","to walk / to go on foot",2,"verb"],
["起来","qi3lai5","to stand up / to get up",2,"verb"],["足球","zu2qiu2","soccer / football",2,"noun"],
["跑","pao3","to run / to run away",2,"verb"],["跟","gen1","heel / to follow closely",2,"function"],
["路上","lu4shang5","on the road / on the way",2,"noun"],["踢","ti1","to kick / to play",2,"verb"],
["车站","che1zhan4","rail station / bus stop",2,"noun"],["过去","guo4qu4","(in the) past / former",2,"verb"],
["过年","guo4nian2","to celebrate the Chinese New Year",2,"verb"],["过来","guo4lai2","to come over / to manage",2,"verb"],
["还是","hai2shi5","still / had better",2,"function"],["这么","zhe4me5","so much / this much",2,"pronoun"],
["这样","zhe4yang4","this kind of / so",2,"pronoun"],["进去","jin4qu4","to go in",2,"verb"],
["进来","jin4lai2","to come in",2,"verb"],["那么","na4me5","like that / in that way",2,"pronoun"],
["那样","na4yang4","that kind / that sort",2,"pronoun"],["酒店","jiu3dian4","wine shop / pub",2,"noun"],
["里面","li3mian4","inside / interior",2,"noun"],["门口","men2kou3","doorway / gate",2,"noun"],
["门票","men2piao4","ticket",2,"noun"],["间","jian1","between / among",2,"function"],
["面","mian4","face / side",2,"noun"],["飞","fei1","to fly",2,"verb"],["饭馆","fan4guan3","restaurant",2,"noun"],
["高中","gao1zhong1","senior high school",2,"noun"],["鸟","niao3","bird",2,"noun"],["黑色","hei1se4","black",2,"noun"],
/* ---- HSK 3 v2 - 435 words absent from data.js (band 3: 493 listed, 1000 cumulative) ---- */
["一共","yi1gong4","in total / altogether",3,"adv"],["一块儿","yi1kuai4r5","a piece / a chunk",3,"adv"],
["一定","yi1ding4","surely / certainly",3,"adv"],["一样","yi1yang4","same / like",3,"function"],
["一直","yi1zhi2","straight / continuously",3,"adv"],["一般","yi1ban1","same / ordinary",3,"adj"],
["一边","yi1bian1","one side / either side",3,"adv"],["上衣","shang4yi1","jacket / upper outer garment",3,"noun"],
["不久","bu4jiu3","not long / before too long",3,"function"],["不同","bu4tong2","different / distinct",3,"adj"],
["不用","bu4yong4","need not",3,"adv"],["不行","bu4xing2","won't do / be out of the question",3,"adj"],
["不见","bu4jian4","not to see / not to meet",3,"verb"],["世界","shi4jie4","world",3,"noun"],
["东北","dong1bei3","northeast / Northeast China",3,"noun"],["东南","dong1nan2","southeast",3,"noun"],
["东方","dong1fang1","east / the East",3,"noun"],["丢","diu1","to lose / to put aside",3,"verb"],
["中","zhong1","within / among",3,"noun"],["中间","zhong1jian1","the middle / the inside",3,"noun"],
["为","wei4","because of / for",3,"function"],["为了","wei4le5","for / for the purpose of",3,"function"],
["主要","zhu3yao4","main / principal",3,"adj"],["久","jiu3","(of a period of time) long",3,"adj"],
["习惯","xi2guan4","habit / custom",3,"noun"],["了解","liao3jie3","to understand / to realize",3,"verb"],
["以上","yi3shang4","that level or higher",3,"noun"],["以下","yi3xia4","that level or lower",3,"noun"],
["以为","yi3wei2","to think",3,"verb"],["以前","yi3qian2","before / formerly",3,"noun"],
["以后","yi3hou4","after / later",3,"noun"],["以外","yi3wai4","apart from / other than",3,"noun"],
["休假","xiu1jia4","to go on vacation / to have a holiday",3,"verb"],["会议","hui4yi4","meeting / conference",3,"noun"],
["伞","san3","umbrella / parasol",3,"noun"],["住院","zhu4yuan4","to stay in hospital",3,"verb"],
["体育","ti3yu4","sports / physical education",3,"noun"],["体育馆","ti3yu4guan3","gym / gymnasium",3,"noun"],
["作业","zuo4ye4","school assignment / homework",3,"noun"],["信","xin4","letter / mail",3,"noun"],
["信用卡","xin4yong4ka3","credit card",3,"noun"],["借","jie4","to borrow",3,"verb"],["假期","jia4qi1","vacation",3,"noun"],
["做客","zuo4ke4","to be a guest or visitor",3,"verb"],["健康","jian4kang1","health / healthy",3,"adj"],
["像","xiang4","to resemble / to be like",3,"verb"],["先","xian1","beforehand / first",3,"adv"],
["公园","gong1yuan2","park",3,"noun"],["公斤","gong1jin1","kilogram",3,"function"],
["关","guan1","mountain pass / to close",3,"verb"],["关于","guan1yu2","pertaining to / concerning",3,"function"],
["关心","guan1xin1","to be concerned about",3,"verb"],
["关机","guan1ji1","to turn off / to finish shooting a film",3,"verb"],
["关注","guan1zhu4","to pay attention to",3,"verb"],["关系","guan1xi5","relation / relationship",3,"noun"],
["兴趣","xing4qu4","interest / interest",3,"noun"],["其他","qi2ta1","other / (sth or sb) else",3,"pronoun"],
["其实","qi2shi2","actually / in fact",3,"adv"],["养","yang3","to raise / to bring up",3,"verb"],
["冬天","dong1tian1","winter",3,"noun"],["冰","bing1","ice / to chill sth",3,"noun"],
["冰激凌","bing1ji1ling2","ice cream",3,"noun"],["决定","jue2ding4","to decide / to resolve",3,"verb"],
["凉快","liang2kuai5","pleasantly cool / to cool oneself",3,"adj"],["几乎","ji1hu1","almost / nearly",3,"adv"],
["出院","chu1yuan4","to leave hospital",3,"verb"],["分开","fen1kai1","to separate / to part",3,"verb"],
["刚","gang1","hard / firm",3,"adv"],["刚刚","gang1gang5","just recently / just a moment ago",3,"adv"],
["刚才","gang1cai2","just now / a moment ago",3,"noun"],["初中","chu1zhong1","junior high school",3,"noun"],
["别的","bie2de5","else / other",3,"pronoun"],["刮","gua1","to scrape / to blow",3,"verb"],
["到处","dao4chu4","everywhere",3,"adv"],["刷","shua1","a brush / to paint",3,"verb"],
["刻","ke4","quarter / moment",3,"verb"],["前天","qian2tian1","the day before yesterday",3,"noun"],
["前年","qian2nian2","the year before last",3,"noun"],["办","ban4","to take care of / to deal with",3,"verb"],
["加","jia1","to add / (math.) plus",3,"verb"],["动物园","dong4wu4yuan2","zoo",3,"noun"],
["努力","nu3li4","to make an effort / to try hard",3,"verb"],["勺子","shao2zi5","spoon / ladle",3,"noun"],
["北","bei3","north / (classical) to be defeated",3,"noun"],
["半天","ban4tian1","half of the day / a long time",3,"function"],["南","nan2","south",3,"adj"],
["南方","nan2fang1","south / southern direction",3,"noun"],["卡","ka3","to stop / to block",3,"verb"],
["卫生间","wei4sheng1jian1","bathroom / toilet",3,"noun"],["历史","li4shi3","history",3,"noun"],
["又","you4","(once) again / also",3,"adv"],["双","shuang1","two / double",3,"function"],
["发","fa1","to send out / to show",3,"verb"],["发展","fa1zhan3","development / growth",3,"verb"],
["发烧","fa1shao1","to have a high temperature",3,"verb"],["发现","fa1xian4","to notice / to become aware of",3,"verb"],
["发生","fa1sheng1","to happen / to occur",3,"verb"],["叔叔","shu1shu5","father's younger brother",3,"noun"],
["受","shou4","to receive / to accept",3,"verb"],["受到","shou4dao4","to receive",3,"verb"],
["变","bian4","to change / to become different",3,"verb"],
["变成","bian4cheng2","to change into / to turn into",3,"verb"],["句","ju4","sentence / clause",3,"function"],
["句子","ju4zi5","sentence",3,"noun"],["只是","zhi3shi4","merely / only",3,"adv"],
["只有","zhi3you3","only have ... / there is only ...",3,"function"],
["只能","zhi3neng2","can only / obliged to do sth",3,"verb"],["只要","zhi3yao4","so long as / provided",3,"function"],
["可","ke3","(prefix) can / may",3,"verb"],["可是","ke3shi4","but / however",3,"function"],
["可爱","ke3ai4","adorable / cute",3,"adj"],["号码","hao4ma3","number",3,"noun"],
["司机","si1ji1","chauffeur / driver",3,"noun"],["合适","he2shi4","suitable / fitting",3,"adj"],
["同事","tong2shi4","colleague / co-worker",3,"noun"],["同意","tong2yi4","to agree / to consent",3,"verb"],
["名人","ming2ren2","personage / celebrity",3,"noun"],["名单","ming2dan1","list of names",3,"noun"],
["后天","hou4tian1","the day after tomorrow",3,"noun"],["后年","hou4nian2","the year after next",3,"noun"],
["后来","hou4lai2","afterwards / later",3,"noun"],["向","xiang4","towards / to face",3,"function"],
["听说","ting1shuo1","to hear / one hears",3,"verb"],
["员","yuan2","person engaged in a certain field of activity",3,"function"],["周末","zhou1mo4","weekend",3,"noun"],
["咱们","zan2men5","we or us (including both the speaker and the per",3,"pronoun"],
["哭","ku1","to cry / to weep",3,"verb"],["啤酒","pi2jiu3","beer",3,"noun"],["喜爱","xi3ai4","to like / to love",3,"verb"],
["嘴","zui3","mouth / beak",3,"noun"],["四季","si4ji4","the four seasons",3,"noun"],
["回答","hui2da2","to reply / to answer",3,"verb"],["园","yuan2","land used for growing plants",3,"noun"],
["国家","guo2jia1","country / nation",3,"noun"],["图书馆","tu2shu1guan3","library",3,"noun"],
["地点","di4dian3","place / site",3,"noun"],["坚持","jian1chi2","to persevere with / to persist in",3,"verb"],
["声","sheng1","sound / voice",3,"noun"],["声音","sheng1yin1","voice / sound",3,"noun"],
["复习","fu4xi2","to review / revision",3,"verb"],["夏天","xia4tian1","summer",3,"noun"],
["外卖","wai4mai4","(of a restaurant) to provide a takeout or home d",3,"noun"],
["外地","wai4di4","parts of the country other than where one is",3,"noun"],["外语","wai4yu3","foreign language",3,"noun"],
["大人","da4ren5","adult / grownup",3,"noun"],["大小","da4xiao3","large and small / size",3,"noun"],
["大概","da4gai4","roughly / probably",3,"adv"],["大熊猫","da4xiong2mao1","giant panda",3,"noun"],
["大衣","da4yi1","overcoat / topcoat",3,"noun"],["太阳","tai4yang5","sun / sunlight",3,"noun"],
["夫妻","fu1qi1","husband and wife / married couple",3,"noun"],["头发","tou2fa5","hair",3,"noun"],
["奇怪","qi2guai4","strange / odd",3,"adj"],["女人","nv3ren2","woman",3,"noun"],
["女生","nv3sheng1","schoolgirl / female student",3,"noun"],["好久","hao3jiu3","quite a while",3,"function"],
["好像","hao3xiang4","as if / to seem like",3,"verb"],["好多","hao3duo1","many / quite a lot",3,"function"],
["如果","ru2guo3","if / in case",3,"function"],["姐妹","jie3mei4","sisters / siblings",3,"noun"],
["子","zi5","(noun suffix)",3,"function"],
["字典","zi4dian3","Chinese character dictionary (containing entries",3,"noun"],
["季","ji4","season / the last month of a season",3,"function"],["季节","ji4jie2","time / season",3,"noun"],
["学期","xue2qi1","term / semester",3,"noun"],["完成","wan2cheng2","to complete / to accomplish",3,"verb"],
["客人","ke4ren2","visitor / guest",3,"noun"],["室","shi4","room / work unit",3,"noun"],
["害怕","hai4pa4","to be afraid / to be scared",3,"verb"],["容易","rong2yi4","easy / straightforward",3,"adj"],
["对话","dui4hua4","to talk / dialogue",3,"verb"],["封","feng1","to confer / to grant",3,"verb"],
["小区","xiao3qu1","housing estate / community",3,"noun"],["小心","xiao3xin1","to be careful / to take care",3,"verb"],
["尝","chang2","to taste / to try",3,"verb"],["屋子","wu1zi5","house / room",3,"noun"],
["山","shan1","mountain / hill",3,"noun"],["工作日","gong1zuo4ri4","workday / working day",3,"noun"],
["市","shi4","market / city",3,"noun"],["常","chang2","always / ever",3,"adv"],
["常常","chang2chang2","frequently / often",3,"adv"],["常用","chang2yong4","in common usage",3,"adj"],
["常见","chang2jian4","commonly seen / common",3,"adj"],["干","gan4","tree trunk / main part of sth",3,"adj"],
["干净","gan1jing4","clean / neat",3,"adj"],["平时","ping2shi2","ordinarily / in normal times",3,"noun"],
["年级","nian2ji2","grade / year",3,"noun"],["年轻","nian2qing1","young",3,"adj"],
["应该","ying1gai1","ought to / should",3,"verb"],["开会","kai1hui4","to hold a meeting / to attend a meeting",3,"verb"],
["开心","kai1xin1","to feel happy / to rejoice",3,"verb"],["开机","kai1ji1","to start an engine",3,"verb"],
["开花","kai1hua1","to bloom / to blossom",3,"verb"],["张","zhang1","to open up / to spread",3,"verb"],
["影响","ying3xiang3","influence / effect",3,"verb"],["得分","de2fen1","to score a point / score",3,"verb"],
["得到","de2dao4","to get / to obtain",3,"verb"],["心里","xin1li5","chest / heart",3,"noun"],
["忘记","wang4ji4","to forget",3,"verb"],["怎么办","zen3me5ban4","what's to be done",3,"pronoun"],
["怎样","zen3yang4","how / what kind",3,"pronoun"],["怕","pa4","to be afraid / to fear",3,"verb"],
["急","ji2","urgent / pressing",3,"adj"],["总","zong3","general / overall",3,"adv"],["总是","zong3shi4","always",3,"adv"],
["感兴趣","gan3xing4qu4","to be interested",3,"verb"],["感冒","gan3mao4","to catch cold / (common) cold",3,"verb"],
["感到","gan3dao4","to feel / to sense",3,"verb"],["愿意","yuan4yi4","to wish / to want",3,"verb"],
["懂得","dong3de5","to understand / to know",3,"verb"],["或","huo4","maybe / perhaps",3,"function"],
["或者","huo4zhe3","or / possibly",3,"function"],["房子","fang2zi5","house / building",3,"noun"],
["才","cai2","ability / talent",3,"adv"],["扫","sao3","to sweep / to sweep away",3,"verb"],
["护照","hu4zhao4","passport",3,"noun"],["拍照","pai1zhao4","to take a picture",3,"verb"],
["挺","ting3","straight / erect",3,"adv"],["换","huan4","to exchange / to change",3,"verb"],
["接","jie1","to receive / to answer",3,"verb"],["提高","ti2gao1","to raise / to increase",3,"verb"],
["搬家","ban1jia1","to move house / to relocate",3,"verb"],["收","shou1","to receive / to accept",3,"verb"],
["收到","shou1dao4","to receive",3,"verb"],["放","fang4","to put / to place",3,"verb"],
["放假","fang4jia4","to have a holiday or vacation",3,"verb"],
["放学","fang4xue2","to dismiss students at the end of the school day",3,"verb"],
["放心","fang4xin1","to feel relieved / to feel reassured",3,"verb"],["故事","gu4shi4","old practice",3,"noun"],
["数学","shu4xue2","mathematics",3,"noun"],["文化","wen2hua4","culture / civilization",3,"noun"],
["斤","jin1","catty / (PRC) weight equal to 500 g",3,"function"],["新年","xin1nian2","New Year",3,"noun"],
["新闻","xin1wen2","news",3,"noun"],["新鲜","xin1xian1","fresh / freshness",3,"adj"],
["方便","fang1bian4","convenient / suitable",3,"adj"],["方便面","fang1bian4mian4","instant noodles",3,"noun"],
["方向","fang1xiang4","direction / orientation",3,"noun"],["方法","fang1fa3","method / way",3,"noun"],
["旧","jiu4","old / used",3,"adj"],["明白","ming2bai5","clear / obvious",3,"adj"],["春天","chun1tian1","spring",3,"noun"],
["晚会","wan3hui4","evening party",3,"noun"],["晚点","wan3dian3","(of trains etc) late",3,"verb"],
["更","geng4","more / even more",3,"adv"],["最后","zui4hou4","final / last",3,"noun"],
["最好","zui4hao3","best / had better ...",3,"adv"],["最近","zui4jin4","recently / soon",3,"noun"],
["月亮","yue4liang5","the moon",3,"noun"],["有一点儿","you3yi1dian3r5","a bit / a little",3,"noun"],
["有关","you3guan1","to have sth to do with",3,"verb"],["有名","you3ming2","famous / well-known",3,"adj"],
["有时候","you3shi2hou5","sometimes",3,"adv"],["有用","you3yong4","useful",3,"adj"],
["服务","fu2wu4","to serve / service",3,"verb"],["机会","ji1hui4","opportunity / chance",3,"noun"],
["来自","lai2zi4","to come from / From:",3,"verb"],["极","ji2","extremely / pole",3,"adv"],
["查","cha2","to research / to check",3,"verb"],["树","shu4","tree / to cultivate",3,"noun"],
["校园","xiao4yuan2","campus",3,"noun"],["校长","xiao4zhang3","(college, university) president",3,"noun"],
["根据","gen1ju4","according to / based on",3,"function"],["检查","jian3cha2","inspection / to examine",3,"verb"],
["检票","jian3piao4","to inspect a ticket",3,"verb"],["楼梯","lou2ti1","stair / staircase",3,"noun"],
["欢迎","huan1ying2","to welcome / welcome",3,"verb"],["毛","mao2","hair / feather",3,"noun"],
["水平","shui3ping2","horizontal / level",3,"noun"],["汽车","qi4che1","car / automobile",3,"noun"],
["沙发","sha1fa1","sofa",3,"noun"],["河","he2","river / the Yellow River",3,"noun"],
["注意","zhu4yi4","to take note of / to pay attention to",3,"verb"],
["洗澡","xi3zao3","to bathe / to take a shower",3,"verb"],["洗衣机","xi3yi1ji1","washing machine / washer",3,"noun"],
["海","hai3","ocean / sea",3,"noun"],["清楚","qing1chu5","clear / distinct",3,"adj"],["渴","ke3","thirsty",3,"adj"],
["游客","you2ke4","traveler / tourist",3,"noun"],["游戏","you2xi4","game / to play",3,"noun"],
["满意","man3yi4","satisfied / pleased",3,"verb"],["热情","re4qing2","cordial / enthusiastic",3,"noun"],
["然后","ran2hou4","then / after that",3,"function"],["照","zhao4","to shine / to illuminate",3,"verb"],
["照片","zhao4pian4","photograph / picture",3,"noun"],["照相","zhao4xiang4","to take a photograph",3,"verb"],
["照顾","zhao4gu5","to take care of / to show consideration",3,"verb"],["爬","pa2","to crawl / to climb",3,"verb"],
["爱人","ai4ren5","spouse / lover",3,"noun"],["牙","ya2","tooth / ivory",3,"noun"],
["牙刷","ya2shua1","toothbrush",3,"noun"],["牛","niu2","ox / cow",3,"noun"],["特别","te4bie2","unusual / special",3,"adv"],
["环境","huan2jing4","environment / circumstances",3,"noun"],["班级","ban1ji2","class / grade",3,"noun"],
["球场","qiu2chang3","stadium / sports ground",3,"noun"],["瓶子","ping2zi5","bottle",3,"noun"],
["甜","tian2","sweet",3,"adj"],["生气","sheng1qi4","to get angry / to be furious",3,"verb"],
["生活","sheng1huo2","to live / life",3,"verb"],["用","yong4","to use / to make use of",3,"verb"],
["电","dian4","lightning / electricity",3,"noun"],["电子书","dian4zi3shu1","electronic book / e-book",3,"noun"],
["男人","nan2ren2","a man / a male",3,"noun"],["男生","nan2sheng1","schoolboy / male student",3,"noun"],
["画家","hua4jia1","painter",3,"noun"],["留学","liu2xue2","to study abroad",3,"verb"],
["留学生","liu2xue2sheng1","student studying abroad",3,"noun"],["病人","bing4ren2","sick person / patient",3,"noun"],
["瘦","shou4","thin / to lose weight",3,"adj"],["的话","de5hua4","if (coming after a conditional clause)",3,"function"],
["盘子","pan2zi5","tray / plate",3,"noun"],["直到","zhi2dao4","until",3,"verb"],
["相信","xiang1xin4","to believe / to be convinced",3,"verb"],
["相机","xiang4ji1","camera / at the opportune moment",3,"noun"],
["看来","kan4lai5","apparently / it seems that",3,"verb"],["着急","zhao2ji2","to worry / to feel anxious",3,"verb"],
["短裤","duan3ku4","short pants / shorts",3,"noun"],["矿泉水","kuang4quan2shui3","mineral water",3,"noun"],
["碗","wan3","bowl / cup",3,"noun"],["礼物","li3wu4","gift / present",3,"noun"],
["离开","li2kai1","to depart / to leave",3,"verb"],["秋天","qiu1tian1","autumn",3,"noun"],
["种","zhong3","seed / species",3,"function"],["空调","kong1tiao2","air conditioning / air conditioner",3,"noun"],
["突然","tu1ran2","sudden / abrupt",3,"adj"],["笔记","bi3ji4","to take down / notes",3,"verb"],
["筷子","kuai4zi5","chopsticks",3,"noun"],["简单","jian3dan1","simple / not complicated",3,"adj"],
["箱子","xiang1zi5","suitcase / chest",3,"noun"],["米","mi3","uncooked rice / meter",3,"noun"],
["糖","tang2","sugar / sweets",3,"noun"],["红绿灯","hong2lv4deng1","traffic light / traffic signal",3,"noun"],
["纸","zhi3","paper",3,"noun"],["练","lian4","to practice / to train",3,"verb"],
["练习","lian4xi2","to practice / exercise",3,"verb"],["终于","zhong1yu2","at last / in the end",3,"adv"],
["经理","jing1li3","manager / director",3,"noun"],["经过","jing1guo4","to pass / to go through",3,"verb"],
["结婚","jie2hun1","to marry / to get married",3,"verb"],["结束","jie2shu4","termination / to finish",3,"verb"],
["网球","wang3qiu2","tennis / tennis ball",3,"noun"],["网站","wang3zhan4","website",3,"noun"],
["羊","yang2","sheep / goat",3,"noun"],["羽毛球","yu3mao2qiu2","badminton / shuttlecock",3,"noun"],
["老","lao3","prefix used before the surname of a person or a",3,"adj"],
["老人","lao3ren2","old man or woman / the elderly",3,"noun"],["而且","er2qie3","(not only ...) but also",3,"function"],
["耳朵","er3duo5","ear / handle",3,"noun"],["耳机","er3ji1","headphones / earphones",3,"noun"],
["聊","liao2","to chat / temporarily",3,"verb"],["聊天儿","liao2tian1r5","to chat",3,"verb"],
["胖","pang4","fat / plump",3,"adj"],["脏","zang4","viscera / (anatomy) organ",3,"adj"],
["脚","jiao3","foot / leg",3,"noun"],["脸","lian3","face",3,"noun"],["腿","tui3","leg",3,"noun"],
["自行车","zi4xing2che1","bicycle / bike",3,"noun"],["节","jie2","joint / node",3,"noun"],
["节日","jie2ri4","holiday / festival",3,"noun"],["节目","jie2mu4","(TV or radio) program",3,"noun"],
["花园","hua1yuan2","garden / (landscaped) park",3,"noun"],["草地","cao3di4","lawn / meadow",3,"noun"],
["蓝","lan2","blue / indigo plant",3,"adj"],["行","xing2","to walk / to go",3,"verb"],
["行李","xing2li5","luggage",3,"noun"],["街","jie1","street",3,"noun"],["裙子","qun2zi5","skirt",3,"noun"],
["西","xi1","west",3,"noun"],["西北","xi1bei3","northwest / Northwest China",3,"noun"],
["西南","xi1nan2","southwest",3,"noun"],["西方","xi1fang1","the West / the Occident",3,"noun"],
["要求","yao1qiu2","to request / to require",3,"verb"],["见面","jian4mian4","to meet / to see each other",3,"verb"],
["角","jiao3","angle / corner",3,"noun"],["解决","jie3jue2","to solve / to resolve",3,"verb"],
["认为","ren4wei2","to believe / to think",3,"verb"],["认得","ren4de5","to recognize",3,"verb"],
["认真","ren4zhen1","conscientious / earnest",3,"adj"],["记","ji4","to record / to note",3,"verb"],
["讲","jiang3","to speak / to explain",3,"verb"],["试","shi4","to test / to try",3,"verb"],
["该","gai1","should / ought to",3,"verb"],["语言","yu3yan2","language",3,"noun"],
["请假","qing3jia4","to request leave of absence",3,"verb"],["请客","qing3ke4","to give a dinner party",3,"verb"],
["课文","ke4wen2","text",3,"noun"],["课本","ke4ben3","textbook",3,"noun"],["起","qi3","to rise / to raise",3,"verb"],
["起飞","qi3fei1","(of an aircraft or rocket) to take off",3,"verb"],["越","yue4","to exceed / to climb over",3,"verb"],
["路口","lu4kou3","crossing / intersection",3,"noun"],["路边","lu4bian1","curb / roadside",3,"noun"],
["跳","tiao4","to jump / to hop",3,"verb"],["身边","shen1bian1","at one's side / on hand",3,"noun"],
["身高","shen1gao1","(a person's) height",3,"noun"],["辆","liang4","classifier for vehicles",3,"function"],
["过节","guo4jie2","to celebrate a festival",3,"verb"],["运动会","yun4dong4hui4","sports competition",3,"noun"],
["运动员","yun4dong4yuan2","athlete",3,"noun"],["选","xuan3","to choose / to pick",3,"verb"],
["选择","xuan3ze2","to select / to pick",3,"verb"],["遇到","yu4dao4","to meet / to run into",3,"verb"],
["遇见","yu4jian4","to meet",3,"verb"],["邮件","you2jian4","mail / post",3,"noun"],
["邮箱","you2xiang1","mailbox / post office box",3,"noun"],["邻居","lin2ju1","neighbor",3,"noun"],
["酒","jiu3","wine / liquor",3,"noun"],["重要","zhong4yao4","important / significant",3,"adj"],
["银行","yin2hang2","bank",3,"noun"],["银行卡","yin2hang2ka3","bank card",3,"noun"],
["附近","fu4jin4","nearby / neighboring",3,"noun"],["难","nan2","difficult / problem",3,"adj"],
["难听","nan2ting1","unpleasant to hear",3,"adj"],["难看","nan2kan4","ugly / unsightly",3,"adj"],
["难过","nan2guo4","to feel sad / to feel unwell",3,"verb"],["难题","nan2ti2","difficult problem",3,"noun"],
["雨衣","yu3yi1","raincoat",3,"noun"],["需要","xu1yao4","to need / to want",3,"verb"],
["面前","mian4qian2","in front of / facing",3,"noun"],["鞋","xie2","shoe",3,"noun"],["音乐","yin1yue4","music",3,"noun"],
["页","ye4","page / leaf",3,"function"],["风","feng1","wind / news",3,"noun"],
["饮料","yin3liao4","drink / beverage",3,"noun"],["饿","e4","hungry / to starve",3,"adj"],
["香蕉","xiang1jiao1","banana",3,"noun"],["马","ma3","horse",3,"noun"],["马上","ma3shang4","at once / right away",3,"adv"],
["马路","ma3lu4","street / road",3,"noun"],["骑","qi2","to sit astride / to ride",3,"verb"],
["高铁","gao1tie3","high speed rail",3,"noun"],["鸡","ji1","fowl / chicken",3,"noun"],
["黄色","huang2se4","yellow / vulgar",3,"noun"],["黑板","hei1ban3","blackboard",3,"noun"],
/* ---- HSK 4 v2 - 938 words absent from data.js (band 4: 990 listed, 2000 cumulative) ---- */
["一切","yi1qie4","everything / every",4,"pronoun"],
["一生","yi1sheng1","all one's life / throughout one's life",4,"noun"],
["上门","shang4men2","to drop in / to visit",4,"verb"],["下降","xia4jiang4","to decline / to drop",4,"verb"],
["不便","bu4bian4","inconvenient / inappropriate",4,"noun"],
["不光","bu4guang1","not the only one / not only",4,"function"],["不够","bu4gou4","not enough / insufficient",4,"adj"],
["不如","bu4ru2","not equal to / not as good as",4,"verb"],["不必","bu4bi4","need not / does not have to",4,"adv"],
["不断","bu4duan4","unceasing / uninterrupted",4,"adv"],["不满","bu4man3","dissatisfied / discontented",4,"noun"],
["不论","bu4lun4","whatever / no matter what",4,"function"],["与","yu3","and / to give",4,"function"],
["专业","zhuan1ye4","specialty / specialized field",4,"noun"],["专门","zhuan1men2","specialized / dedicated",4,"adv"],
["世纪","shi4ji4","century",4,"noun"],["东部","dong1bu4","the east / eastern part",4,"noun"],
["严格","yan2ge2","strict / stringent",4,"adj"],["严重","yan2zhong4","grave / serious",4,"adj"],
["中年","zhong1nian2","middle age",4,"noun"],["中餐","zhong1can1","lunch / Chinese meal",4,"noun"],
["丰富","feng1fu4","to enrich / rich",4,"verb"],["主意","zhu3yi5","plan / idea",4,"noun"],
["举","ju3","to lift / to hold up",4,"verb"],["举例","ju3li4","to give an example",4,"verb"],
["举办","ju3ban4","to conduct / to hold",4,"verb"],["举行","ju3xing2","to hold",4,"verb"],
["之","zhi1","(possessive particle)",4,"function"],["之中","zhi1zhong1","inside / among",4,"noun"],
["之前","zhi1qian2","before / prior to",4,"noun"],["之后","zhi1hou4","after / behind",4,"noun"],
["之间","zhi1jian1","(after a noun) between",4,"noun"],["乒乓球","ping1pang1qiu2","table tennis / ping-pong",4,"noun"],
["乘","cheng2","to ride / to mount",4,"verb"],["乘客","cheng2ke4","passenger",4,"noun"],
["也许","ye3xu3","perhaps / maybe",4,"adv"],["乱","luan4","in confusion or disorder",4,"adv"],
["于是","yu2shi4","thereupon / as a result",4,"noun"],["云","yun2","(classical) to say",4,"noun"],
["互相","hu4xiang1","each other / mutually",4,"adv"],["互联网","hu4lian2wang3","Internet",4,"noun"],
["亚洲","ya4zhou1","Asia",4,"noun"],["交","jiao1","to hand over / to deliver",4,"verb"],
["交流","jiao1liu2","to exchange / exchange",4,"verb"],["交警","jiao1jing3","traffic police",4,"noun"],
["交通","jiao1tong1","to be connected / traffic",4,"verb"],
["产生","chan3sheng1","to arise / to come into being",4,"verb"],["京剧","jing1ju4","Beijing opera",4,"noun"],
["亮","liang4","bright / light",4,"adj"],["亲戚","qin1qi5","a relative",4,"noun"],
["人员","ren2yuan2","staff / crew",4,"noun"],["人数","ren2shu4","number of people",4,"noun"],
["人生","ren2sheng1","life",4,"noun"],["仅","jin3","barely / only",4,"adv"],["仅仅","jin3jin3","barely / only",4,"adv"],
["今后","jin1hou4","hereafter / henceforth",4,"noun"],["仍","reng2","still / yet",4,"adv"],
["仍然","reng2ran2","still / as before",4,"adv"],["从中","cong2zhong1","from within / therefrom",4,"adv"],
["从此","cong2ci3","from now on / since then",4,"adv"],["仔细","zi3xi4","careful / attentive",4,"adj"],
["付","fu4","to pay / to hand over to",4,"verb"],["以内","yi3nei4","within / less than",4,"noun"],
["价格","jia4ge2","price",4,"noun"],["价钱","jia4qian5","price",4,"noun"],["任何","ren4he2","any / whatever",4,"pronoun"],
["任务","ren4wu5","mission / assignment",4,"noun"],
["份","fen4","classifier for gifts, newspaper, magazine, paper",4,"function"],
["优点","you1dian3","merit / benefit",4,"noun"],["优秀","you1xiu4","outstanding / excellent",4,"adj"],
["会员","hui4yuan2","member",4,"noun"],["伤心","shang1xin1","to grieve / to be broken-hearted",4,"verb"],
["估计","gu1ji4","to estimate / to assess",4,"verb"],["低","di1","low / beneath",4,"adj"],
["低于","di1yu2","to be lower than",4,"verb"],["低价","di1jia4","low price",4,"noun"],
["低温","di1wen1","low temperature",4,"noun"],["体检","ti3jian3","physical examination",4,"noun"],
["体温","ti3wen1","(body) temperature",4,"noun"],["体重","ti3zhong4","body weight",4,"noun"],
["作为","zuo4wei2","one's conduct / deed",4,"function"],["作品","zuo4pin3","work / opus",4,"noun"],
["作家","zuo4jia1","author",4,"noun"],["作文","zuo4wen2","to write an essay / composition",4,"verb"],
["作用","zuo4yong4","to act on / to affect",4,"verb"],["作者","zuo4zhe3","author / writer",4,"noun"],
["使","shi3","to make / to cause",4,"verb"],["使用","shi3yong4","to use / to employ",4,"verb"],
["使馆","shi3guan3","consulate / diplomatic mission",4,"noun"],["例如","li4ru2","for example / for instance",4,"verb"],
["例子","li4zi5","case / (for) instance",4,"noun"],["便于","bian4yu2","easy to / convenient for",4,"verb"],
["信号","xin4hao4","signal",4,"noun"],["信心","xin4xin1","confidence / faith",4,"noun"],
["信息","xin4xi1","information / news",4,"noun"],["俩","lia3","two / both",4,"function"],
["修","xiu1","to decorate / to embellish",4,"verb"],["修理","xiu1li3","to repair / to fix",4,"verb"],
["倒","dao4","to invert",4,"verb"],["值","zhi2","value / (to be) worth",4,"adj"],
["值得","zhi2de5","worth the money / to merit",4,"verb"],["假","jia3","fake / false",4,"adj"],
["假日","jia4ri4","a holiday / a day off",4,"noun"],["做梦","zuo4meng4","to dream / to have a dream",4,"verb"],
["做法","zuo4fa3","way of handling sth",4,"noun"],["停","ting2","to stop / to halt",4,"verb"],
["停止","ting2zhi3","to stop / to halt",4,"verb"],["停车","ting2che1","to pull up / to park",4,"verb"],
["停车场","ting2che1chang3","parking lot / car park",4,"noun"],["健身","jian4shen1","to exercise / to keep fit",4,"verb"],
["健身房","jian4shen1fang2","gym / fitness club",4,"noun"],["偶尔","ou3er3","occasionally / once in a while",4,"adv"],
["儿童","er2tong2","child",4,"noun"],["允许","yun3xu3","to permit / to allow",4,"verb"],
["兄弟","xiong1di4","brothers / younger brother",4,"noun"],["光","guang1","light / ray",4,"noun"],
["克","ke4","to be able to / to subdue",4,"verb"],["免费","mian3fei4","free",4,"verb"],
["入","ru4","to enter / to go into",4,"verb"],["入住","ru4zhu4","to check in / to move into",4,"verb"],
["入口","ru4kou3","entrance / to import",4,"noun"],["入学","ru4xue2","to enter a school or college",4,"verb"],
["全","quan2","all / whole",4,"adv"],["全球","quan2qiu2","the whole world / worldwide",4,"noun"],
["全身","quan2shen1","the whole body / (typography) em",4,"noun"],["全部","quan2bu4","whole / all",4,"function"],
["全都","quan2dou1","all / without exception",4,"adv"],["公共","gong1gong4","public / common",4,"adj"],
["公路","gong1lu4","highway / road",4,"noun"],["公里","gong1li3","kilometer",4,"function"],
["共","gong4","common / general",4,"adv"],["共同","gong4tong2","common / joint",4,"adv"],
["关键","guan1jian4","crucial point / crux",4,"noun"],["兴奋","xing1fen4","excited / excitement",4,"adj"],
["其中","qi2zhong1","among / in",4,"pronoun"],["其次","qi2ci4","next / secondly",4,"function"],
["养成","yang3cheng2","to cultivate / to raise",4,"verb"],["内","nei4","inside / inner",4,"noun"],
["内容","nei4rong2","content / substance",4,"noun"],["内心","nei4xin1","heart / innermost being",4,"noun"],
["再次","zai4ci4","once more / once again",4,"adv"],["再说","zai4shuo1","to say again",4,"verb"],
["农村","nong2cun1","rural area / village",4,"noun"],["冷静","leng3jing4","calm / cool-headed",4,"adj"],
["准","zhun3","to allow / to grant",4,"verb"],["准时","zhun3shi2","on time / punctual",4,"adj"],
["准确","zhun3que4","accurate / exact",4,"adj"],["凉","liang2","cool / cold",4,"adj"],
["减","jian3","to lower / to decrease",4,"verb"],["减少","jian3shao3","to lessen / to decrease",4,"verb"],
["减轻","jian3qing1","to lighten / to ease",4,"verb"],["出口","chu1kou3","an exit / to speak",4,"verb"],
["出租","chu1zu1","to rent",4,"verb"],["出行","chu1xing2","to go out somewhere",4,"verb"],
["刀","dao1","knife / blade",4,"noun"],["分为","fen1wei2","to divide sth into",4,"verb"],
["分数","fen1shu4","(exam) grade / mark",4,"noun"],["列","lie4","to arrange / to line up",4,"verb"],
["判断","pan4duan4","to judge / to determine",4,"verb"],["到底","dao4di3","finally / in the end",4,"adv"],
["到来","dao4lai2","to arrive / arrival",4,"verb"],["前后","qian2hou4","around / from beginning to end",4,"noun"],
["前方","qian2fang1","ahead / the front",4,"noun"],["剧院","ju4yuan4","theater",4,"noun"],
["剩","sheng4","to remain / to be left",4,"verb"],["力气","li4qi5","physical strength",4,"noun"],
["办事","ban4shi4","to handle / to work",4,"verb"],["办公","ban4gong1","to handle official business",4,"verb"],
["办理","ban4li3","to handle / to transact",4,"verb"],["功夫","gong1fu5","skill / art",4,"noun"],
["功课","gong1ke4","homework / assignment",4,"noun"],["加上","jia1shang4","plus / to put in",4,"verb"],
["加入","jia1ru4","to become a member",4,"verb"],["加强","jia1qiang2","to reinforce / to strengthen",4,"verb"],
["加快","jia1kuai4","to accelerate / to speed up",4,"verb"],
["加油","jia1you2","to add oil / to top up with gas",4,"verb"],["加油站","jia1you2zhan4","gas station",4,"noun"],
["加班","jia1ban1","to work overtime",4,"verb"],["动作","dong4zuo4","movement / motion",4,"noun"],
["动车","dong4che1","(PRC) (D- or C-class) high-speed train",4,"noun"],["勇敢","yong3gan3","brave / courageous",4,"adj"],
["北部","bei3bu4","northern part",4,"noun"],["区","qu1","area / region",4,"noun"],
["区别","qu1bie2","difference / to distinguish",4,"noun"],["十分","shi2fen1","very / completely",4,"adv"],
["十字路口","shi2zi4lu4kou3","crossroads / intersection",4,"noun"],
["千万","qian1wan4","ten million / countless",4,"function"],["千克","qian1ke4","kilogram",4,"function"],
["午餐","wu3can1","lunch / luncheon",4,"noun"],["单位","dan1wei4","unit / unit",4,"noun"],
["南部","nan2bu4","southern part",4,"noun"],["卫生","wei4sheng1","hygienic / sanitary",4,"noun"],
["印象","yin4xiang4","impression / a memory",4,"noun"],["危险","wei1xian3","danger / dangerous",4,"adj"],
["即使","ji2shi3","even if / even though",4,"function"],["却","que4","but / yet",4,"adv"],
["厂","chang3","factory / yard",4,"noun"],["厉害","li4hai5","(used to describe sb or sth that makes a very st",4,"adj"],
["压","ya1","to press / to push down",4,"verb"],["压力","ya1li4","pressure",4,"noun"],
["厚","hou4","thick / deep or profound",4,"adj"],["原因","yuan2yin1","cause / origin",4,"noun"],
["原来","yuan2lai2","original / former",4,"adv"],["原谅","yuan2liang4","to excuse / to forgive",4,"verb"],
["厨师","chu2shi1","cook / chef",4,"noun"],["参赛","can1sai4","to compete / to take part in a competition",4,"verb"],
["及时","ji2shi2","timely / at the right time",4,"adj"],["友好","you3hao3","friendly / amicable",4,"adj"],
["友情","you3qing2","friendly feelings / friendship",4,"noun"],["友谊","you3yi4","companionship / fellowship",4,"noun"],
["反对","fan3dui4","to oppose / to be against",4,"verb"],["发出","fa1chu1","to issue / to send out",4,"verb"],
["发送","fa1song4","to transmit / to dispatch",4,"verb"],["取","qu3","to take / to get",4,"verb"],
["取得","qu3de2","to acquire / to get",4,"verb"],["取消","qu3xiao1","to cancel / to call off",4,"verb"],
["受不了","shou4bu4liao3","unbearable / unable to endure",4,"noun"],["受伤","shou4shang1","to sustain injuries",4,"verb"],
["口语","kou3yu3","colloquial speech / spoken language",4,"noun"],["另","ling4","other / another",4,"pronoun"],
["另外","ling4wai4","additional / in addition",4,"pronoun"],
["只好","zhi3hao3","to have no other option but to ...",4,"verb"],["叫作","jiao4zuo4","to call / to be called",4,"verb"],
["可惜","ke3xi1","it is a pity / what a pity",4,"adj"],["台","tai2","(classical) you",4,"function"],
["叶子","ye4zi5","leaf / (slang) marijuana",4,"noun"],["各","ge4","each / every",4,"pronoun"],
["各个","ge4ge4","every / various",4,"pronoun"],["各位","ge4wei4","everybody / all",4,"pronoun"],
["各地","ge4di4","in all parts of / various regions",4,"pronoun"],
["各种","ge4zhong3","every kind of / all kinds of",4,"pronoun"],
["合格","he2ge2","to meet the standard required",4,"verb"],
["同时","tong2shi2","at the same time / simultaneously",4,"function"],["同样","tong2yang4","same / equal",4,"adj"],
["后悔","hou4hui3","to regret / to feel remorse",4,"verb"],["否则","fou3ze2","otherwise / if not",4,"function"],
["听众","ting1zhong4","audience / listeners",4,"noun"],["听力","ting1li4","hearing / listening ability",4,"noun"],
["吸","xi1","to breathe / to suck in",4,"verb"],["吸引","xi1yin3","to attract / to appeal to",4,"verb"],
["吹","chui1","to blow / to play a wind instrument",4,"verb"],["周围","zhou1wei2","environs / surroundings",4,"noun"],
["味","wei4","taste / smell",4,"noun"],["味道","wei4dao5","flavor / taste",4,"noun"],
["咳","hai1","sound of sighing",4,"verb"],["咳嗽","ke2sou5","to cough",4,"verb"],["咸","xian2","all / everyone",4,"adj"],
["响","xiang3","echo / sound",4,"adj"],["售票员","shou4piao4yuan2","ticket seller",4,"noun"],
["商品","shang1pin3","commodity / goods",4,"noun"],["商量","shang1liang5","to consult / to talk over",4,"verb"],
["喊","han3","to yell / to shout",4,"verb"],["嗯","n2","(a groaning sound)",4,"noun"],
["回信","hui2xin4","to reply / to write back",4,"verb"],["回复","hui2fu4","to recover / to revert",4,"verb"],
["回忆","hui2yi4","to recall / memories",4,"verb"],["因此","yin1ci3","thus / consequently",4,"function"],
["困","kun4","to trap / to surround",4,"verb"],["困难","kun4nan5","difficult / challenging",4,"adj"],
["国籍","guo2ji2","nationality",4,"noun"],["国际","guo2ji4","international",4,"noun"],
["图","tu2","diagram / picture",4,"noun"],["图片","tu2pian4","picture / photograph",4,"noun"],
["土","tu3","earth / dust",4,"noun"],["地址","di4zhi3","address",4,"noun"],["地球","di4qiu2","the earth",4,"noun"],
["坏处","huai4chu5","harm / troubles",4,"noun"],["垃圾","la1ji1","trash / refuse",4,"noun"],
["城","cheng2","city walls / city",4,"noun"],["基本","ji1ben3","basic / fundamental",4,"adj"],
["基本上","ji1ben3shang5","basically / on the whole",4,"adv"],["基础","ji1chu3","base / foundation",4,"noun"],
["堵车","du3che1","traffic jam",4,"verb"],["塑料","su4liao4","plastic / plastics",4,"noun"],
["填写","tian2xie3","to fill in a form / to write data in a box",4,"verb"],
["增加","zeng1jia1","to raise / to increase",4,"verb"],["增长","zeng1zhang3","to grow / to increase",4,"verb"],
["复印","fu4yin4","to photocopy / to duplicate a document",4,"verb"],["复杂","fu4za2","complicated / complex",4,"adj"],
["外出","wai4chu1","to go out / to go away",4,"verb"],["外套","wai4tao4","outer garment / jacket",4,"noun"],
["多么","duo1me5","how / what",4,"adv"],["多数","duo1shu4","majority / most",4,"function"],
["多样","duo1yang4","diverse / diversity",4,"function"],["夜","ye4","night",4,"noun"],["夜晚","ye4wan3","night",4,"noun"],
["够","gou4","enough / enough",4,"verb"],["大厅","da4ting1","hall / concourse",4,"noun"],
["大大","da4da4","greatly / enormously",4,"adv"],["大夫","da4fu1","senior official",4,"noun"],
["大巴","da4ba1","large bus / coach",4,"noun"],["大约","da4yue1","approximately / probably",4,"adv"],
["大自然","da4zi4ran2","nature",4,"noun"],["大赛","da4sai4","grand contest",4,"noun"],
["大量","da4liang4","great amount / large quantity",4,"function"],["失去","shi1qu4","to lose",4,"verb"],
["失望","shi1wang4","disappointed / to lose hope",4,"adj"],["失败","shi1bai4","to be defeated / to lose",4,"verb"],
["头痛","tou2tong4","to have a headache",4,"verb"],["奖","jiang3","prize / award",4,"noun"],
["奖学金","jiang3xue2jin1","scholarship",4,"noun"],["奖金","jiang3jin1","premium / award money",4,"noun"],
["女性","nv3xing4","woman / the female sex",4,"noun"],["好处","hao3chu3","easy to get along with",4,"noun"],
["好好","hao3hao3","well / carefully",4,"adv"],["好笑","hao3xiao4","laughable / funny",4,"noun"],
["姑娘","gu1niang5","girl / young woman",4,"noun"],["孙女","sun1nv3","son's daughter / granddaughter",4,"noun"],
["孙子","sun1zi5","grandson / son's son",4,"noun"],["学费","xue2fei4","tuition fee / tuition",4,"noun"],
["学院","xue2yuan4","college / educational institute",4,"noun"],
["安检","an1jian3","security check / to do a security check",4,"noun"],["完全","wan2quan2","complete / whole",4,"adj"],
["定","ding4","to fix / to set",4,"verb"],["实在","shi2zai4","really / actually",4,"adv"],
["实际","shi2ji4","reality / practice",4,"noun"],["实际上","shi2ji4shang4","in fact / in reality",4,"adv"],
["客厅","ke4ting1","living room / sitting room",4,"noun"],["客气","ke4qi5","polite / courteous",4,"adj"],
["害羞","hai4xiu1","shy / embarrassed",4,"noun"],["家乡","jia1xiang1","hometown / native place",4,"noun"],
["家具","jia1ju4","furniture",4,"noun"],["家庭","jia1ting2","family / household",4,"noun"],
["家长","jia1zhang3","head of a household",4,"noun"],["寄","ji4","to entrust / to place in sb's care",4,"verb"],
["密码","mi4ma3","cipher / secret code",4,"noun"],["寒假","han2jia4","winter vacation",4,"noun"],
["寒冷","han2leng3","cold / frigid",4,"adj"],["对于","dui4yu2","regarding / as far as (sth) is concerned",4,"function"],
["对方","dui4fang1","the other person / the other side",4,"noun"],["对面","dui4mian4","(sitting) opposite",4,"noun"],
["导游","dao3you2","tour guide / guidebook",4,"noun"],["将","jiang1","will / shall",4,"adv"],
["将来","jiang1lai2","in the future / future",4,"noun"],["将要","jiang1yao4","will / shall",4,"adv"],
["尊重","zun1zhong4","to esteem / to respect",4,"verb"],["小伙子","xiao3huo3zi5","young man / young guy",4,"noun"],
["小吃","xiao3chi1","street food / snack",4,"noun"],["小组","xiao3zu3","group",4,"noun"],
["小说","xiao3shuo1","novel / fiction",4,"noun"],["少年","shao4nian2","early youth / youngster",4,"noun"],
["少数","shao3shu4","small number / few",4,"function"],["少见","shao3jian4","rare / seldom seen",4,"noun"],
["少量","shao3liang4","a smidgen / a little bit",4,"noun"],["尤其","you2qi2","especially / particularly",4,"adv"],
["就是","jiu4shi4","exactly / precisely",4,"verb"],["尽管","jin3guan3","despite / although",4,"function"],
["工人","gong1ren2","worker",4,"noun"],["工厂","gong1chang3","factory",4,"noun"],["工资","gong1zi1","wages / pay",4,"noun"],
["左右","zuo3you4","left and right / nearby",4,"function"],["巧","qiao3","opportunely / coincidentally",4,"adj"],
["巧克力","qiao3ke4li4","(loanword) chocolate",4,"noun"],["差一点儿","cha4yi1dian3r5","almost",4,"adv"],
["已","yi3","already / to stop",4,"adv"],["市区","shi4qu1","urban district / downtown",4,"noun"],
["市场","shi4chang3","marketplace / market",4,"noun"],["帅","shuai4","commander-in-chief",4,"noun"],
["师傅","shi1fu5","master / qualified worker",4,"noun"],["师生","shi1sheng1","teachers and students",4,"noun"],
["帽子","mao4zi5","hat / cap",4,"noun"],["幅","fu2","width / roll",4,"function"],
["干杯","gan1bei1","to drink a toast / Cheers!",4,"verb"],["干活儿","gan4huo2r5","to work",4,"verb"],
["平常","ping2chang2","ordinary / common",4,"adj"],["年底","nian2di3","the end of the year",4,"noun"],
["年龄","nian2ling2","(a person's) age",4,"noun"],["并","bing4","and / furthermore",4,"adv"],
["幸福","xing4fu2","happiness / happy",4,"adj"],["幽默","you1mo4","(loanword) humor / humorous",4,"adj"],
["广告","guang3gao4","to advertise / a commercial",4,"verb"],["广播","guang3bo1","broadcast / broadcasting",4,"noun"],
["庆祝","qing4zhu4","to celebrate",4,"verb"],["应聘","ying4pin4","to accept a job offer",4,"verb"],
["底","di3","bottom / base",4,"noun"],["底下","di3xia5","the location below sth",4,"noun"],
["度假","du4jia4","to go on holidays",4,"verb"],["座","zuo4","seat / base",4,"function"],
["座位","zuo4wei4","seat",4,"noun"],["建议","jian4yi4","to propose / to suggest",4,"verb"],
["开玩笑","kai1wan2xiao4","to play a joke / to make fun of",4,"verb"],["弄","nong4","to do / to manage",4,"verb"],
["引起","yin3qi3","to give rise to / to lead to",4,"verb"],["弹","dan4","crossball / bullet",4,"verb"],
["强","qiang2","strong / powerful",4,"adj"],["当","dang1","dong / ding dong",4,"function"],
["当时","dang1shi2","then / at that time",4,"noun"],["往往","wang3wang3","usually / in many cases",4,"adv"],
["待","dai4","to wait / to treat",4,"verb"],["律师","lv4shi1","lawyer",4,"noun"],
["得意","de2yi4","proud of oneself / pleased with oneself",4,"adj"],["心","xin1","heart / mind",4,"noun"],
["心情","xin1qing2","mood / frame of mind",4,"noun"],["快递","kuai4di4","express delivery",4,"verb"],
["快速","kuai4su4","fast / high-speed",4,"adv"],["快餐","kuai4can1","fast food / snack",4,"noun"],
["忽然","hu1ran2","suddenly / all of a sudden",4,"adv"],["怀疑","huai2yi2","to doubt / to be skeptical of",4,"verb"],
["态度","tai4du5","manner / bearing",4,"noun"],["性","xing4","nature / character",4,"noun"],
["性别","xing4bie2","gender / sex",4,"noun"],["性格","xing4ge2","nature / disposition",4,"noun"],
["总结","zong3jie2","to sum up / to conclude",4,"verb"],["恐怕","kong3pa4","fear / to dread",4,"adv"],
["情况","qing2kuang4","circumstances / state of affairs",4,"noun"],
["想法","xiang3fa3","way of thinking / opinion",4,"noun"],["愉快","yu2kuai4","cheerful / happy",4,"adj"],
["意见","yi4jian4","idea / opinion",4,"noun"],["感","gan3","to feel / to move",4,"verb"],
["感人","gan3ren2","touching / moving",4,"adj"],["感动","gan3dong4","to move / to touch",4,"verb"],
["感受","gan3shou4","to sense / perception",4,"verb"],["感情","gan3qing2","emotion / sentiment",4,"noun"],
["感觉","gan3jue2","feeling / impression",4,"noun"],["感谢","gan3xie4","(express) thanks / gratitude",4,"verb"],
["懒","lan3","lazy",4,"adj"],["戴","dai4","to put on or wear / to respect",4,"verb"],
["房东","fang2dong1","landlord",4,"noun"],["房租","fang2zu1","rent for a room or house",4,"noun"],
["所有","suo3you3","all / to have",4,"adj"],["打印机","da3yin4ji1","printer",4,"noun"],
["打工","da3gong1","to work a temporary or casual job",4,"verb"],["打折","da3zhe2","to give a discount",4,"verb"],
["打招呼","da3zhao1hu5","to greet sb by word or action",4,"verb"],["打败","da3bai4","to defeat / to overpower",4,"verb"],
["打针","da3zhen1","to give or get an injection",4,"verb"],["扔","reng1","to throw / to throw away",4,"verb"],
["扫码","sao3ma3","to scan a QR code or barcode",4,"verb"],["批评","pi1ping2","to criticize / criticism",4,"verb"],
["技术","ji4shu4","technology / technique",4,"noun"],["护士","hu4shi5","nurse",4,"noun"],
["报名","bao4ming2","to sign up / to enter one's name",4,"verb"],
["报考","bao4kao3","to enter oneself for an examination",4,"verb"],["抬","tai2","to lift / to raise",4,"verb"],
["抬头","tai2tou2","to raise one's head",4,"verb"],["拉","la1","to pull / to play",4,"verb"],
["拍","pai1","to pat / to clap",4,"verb"],["拒绝","ju4jue2","to refuse / to decline",4,"verb"],
["招聘","zhao1pin4","to invite applications for a job",4,"verb"],["挂","gua4","to hang / to suspend",4,"verb"],
["指","zhi3","finger / to point at or to",4,"verb"],["指出","zhi3chu1","to indicate / to point out",4,"verb"],
["按","an4","to press / to push",4,"verb"],["换乘","huan4cheng2","to change train",4,"verb"],
["掉","diao4","to fall / to drop",4,"verb"],["排","pai2","a row / a line",4,"verb"],
["排球","pai2qiu2","volleyball",4,"noun"],["排队","pai2dui4","to line up",4,"verb"],
["接受","jie1shou4","to accept / to acquiesce",4,"verb"],["接着","jie1zhe5","to catch and hold on",4,"verb"],
["推","tui1","to push / to cut",4,"verb"],["推出","tui1chu1","to push out / to release",4,"verb"],
["推迟","tui1chi2","to postpone / to put off",4,"verb"],["提","ti2","to carry / to lift",4,"verb"],
["提供","ti2gong1","to offer / to supply",4,"verb"],["提出","ti2chu1","to raise / to propose",4,"verb"],
["提到","ti2dao4","to mention / to raise",4,"verb"],["提前","ti2qian2","to shift to an earlier date",4,"verb"],
["提醒","ti2xing3","to remind / to call attention to",4,"verb"],["摄氏度","she4shi4du4","°C (degrees Celsius)",4,"noun"],
["播放","bo1fang4","to broadcast / to transmit",4,"verb"],["操场","cao1chang3","playground / sports field",4,"noun"],
["支付","zhi1fu4","to pay",4,"verb"],["支持","zhi1chi2","to be in favor of / to support",4,"verb"],
["收入","shou1ru4","to take in / income",4,"verb"],["收听","shou1ting1","to listen to",4,"verb"],
["收拾","shou1shi5","to put in order / to tidy up",4,"verb"],["收费","shou1fei4","to charge a fee",4,"verb"],
["改","gai3","to change / to alter",4,"verb"],["改变","gai3bian4","to change / to alter",4,"verb"],
["放弃","fang4qi4","to renounce / to abandon",4,"verb"],["放松","fang4song1","to relax / to slacken",4,"verb"],
["故意","gu4yi4","deliberately / on purpose",4,"adv"],["效果","xiao4guo3","result / effect",4,"noun"],
["教学","jiao1xue2","to teach",4,"verb"],["教师","jiao4shi1","teacher",4,"noun"],
["教授","jiao4shou4","professor / to instruct",4,"noun"],["教练","jiao4lian4","to coach / to train",4,"verb"],
["教育","jiao4yu4","to educate / to teach",4,"verb"],["敢","gan3","to dare / daring",4,"verb"],
["散步","san4bu4","to take a walk / to go for a walk",4,"verb"],["数","shu4","number / figure",4,"function"],
["数字","shu4zi4","numeral / digit",4,"noun"],["数量","shu4liang4","amount / quantity",4,"noun"],
["敲","qiao1","to hit / to strike",4,"verb"],["整","zheng3","whole / complete",4,"function"],
["整个","zheng3ge4","whole / entire",4,"adj"],["整理","zheng3li3","to arrange / to tidy up",4,"verb"],
["文件","wen2jian4","document / file",4,"noun"],["文字","wen2zi4","character / script",4,"noun"],
["文章","wen2zhang1","article / essay",4,"noun"],["方式","fang1shi4","way / method",4,"noun"],
["方面","fang1mian4","respect / aspect",4,"noun"],["旅客","lv3ke4","traveler / tourist",4,"noun"],
["旅行","lv3xing2","to travel / journey",4,"verb"],["旅馆","lv3guan3","hotel",4,"noun"],
["无","wu2","not to have / no",4,"verb"],["无法","wu2fa3","unable to / incapable of",4,"verb"],
["无聊","wu2liao2","bored / boring",4,"adj"],["无论","wu2lun4","no matter what or how",4,"function"],
["既","ji4","already / since",4,"function"],["既然","ji4ran2","since / as",4,"function"],
["日子","ri4zi5","day / a (calendar) date",4,"noun"],["日常","ri4chang2","day-to-day / daily",4,"adj"],
["日期","ri4qi1","date",4,"noun"],["日记","ri4ji4","diary",4,"noun"],["早晨","zao3chen2","early morning",4,"noun"],
["早餐","zao3can1","breakfast",4,"noun"],["时间表","shi2jian1biao3","schedule / timetable",4,"noun"],
["星星","xing1xing5","a star / the stars in the sky",4,"noun"],["是否","shi4fou3","whether / if",4,"verb"],
["晚安","wan3an1","Good night! / Good evening!",4,"verb"],["晚餐","wan3can1","evening meal / dinner",4,"noun"],
["普通","pu3tong1","common / ordinary",4,"adj"],["普通话","pu3tong1hua4","Mandarin",4,"noun"],
["普遍","pu3bian4","universal / general",4,"adj"],["景区","jing3qu1","scenic area",4,"noun"],
["景点","jing3dian3","tourist attraction",4,"noun"],["景色","jing3se4","scenery / landscape",4,"noun"],
["暂停","zan4ting2","to suspend / time-out",4,"verb"],["暂时","zan4shi2","temporary / provisional",4,"adv"],
["暑假","shu3jia4","summer vacation",4,"noun"],["暖和","nuan3huo5","warm / nice and warm",4,"adj"],
["更加","geng4jia1","more / even more",4,"adv"],["最终","zui4zhong1","final / ultimate",4,"adv"],
["月份","yue4fen4","month",4,"noun"],["月饼","yue4bing3","mooncake",4,"noun"],
["有效","you3xiao4","effective / in effect",4,"adj"],["有着","you3zhe5","to have / to possess",4,"verb"],
["有趣","you3qu4","interesting / fascinating",4,"adj"],["期","qi1","period / cycle",4,"noun"],
["期中","qi1zhong1","interim / midterm",4,"noun"],["期末","qi1mo4","the end of a term or semester",4,"noun"],
["末","mo4","tip / end",4,"noun"],["本科","ben3ke1","undergraduate course",4,"noun"],
["杂志","za2zhi4","magazine",4,"noun"],["村","cun1","village / to scold",4,"noun"],
["条件","tiao2jian4","condition / circumstance",4,"noun"],["来不及","lai2bu5ji2","there's not enough time",4,"verb"],
["来得及","lai2de5ji2","to have enough time",4,"verb"],["果汁","guo3zhi1","fruit juice",4,"noun"],
["查找","cha2zhao3","to search for / to look up",4,"verb"],["查看","cha2kan4","to look over / to examine",4,"verb"],
["树林","shu4lin2","woods / grove",4,"noun"],["样子","yang4zi5","appearance / manner",4,"noun"],
["桥","qiao2","bridge",4,"noun"],["桶","tong3","bucket / (trash) can",4,"noun"],
["梦","meng4","dream / to dream",4,"noun"],["梦想","meng4xiang3","to dream of / dream",4,"verb"],
["森林","sen1lin2","forest",4,"noun"],["棵","ke1","classifier for trees, cabbages, plants etc",4,"function"],
["植物","zhi2wu4","plant / vegetation",4,"noun"],["歌声","ge1sheng1","singing voice",4,"noun"],
["歌手","ge1shou3","singer",4,"noun"],["正好","zheng4hao3","just / just right",4,"adj"],
["正常","zheng4chang2","regular / normal",4,"adj"],["正式","zheng4shi4","formal / official",4,"adj"],
["正确","zheng4que4","correct / sound",4,"adj"],["此","ci3","this / these",4,"pronoun"],
["此外","ci3wai4","besides / in addition",4,"function"],["此次","ci3ci4","this time",4,"pronoun"],
["步","bu4","a step / a pace",4,"noun"],["死","si3","to die / impassable",4,"verb"],["母亲","mu3qin1","mother",4,"noun"],
["母女","mu3nv3","mother and daughter",4,"noun"],["母子","mu3zi3","mother and child / parent and subsidiary",4,"noun"],
["毕业生","bi4ye4sheng1","graduate",4,"noun"],["毛巾","mao2jin1","towel",4,"noun"],
["毛衣","mao2yi1","(wool) sweater",4,"noun"],["民族","min2zu2","nationality / ethnic group",4,"noun"],
["气","qi4","gas / air",4,"noun"],["气候","qi4hou4","(meteorology) climate",4,"noun"],
["气温","qi4wen1","air temperature",4,"noun"],["永远","yong3yuan3","forever / eternal",4,"adv"],
["汗","han4","perspiration / sweat",4,"noun"],["江","jiang1","river",4,"noun"],
["污染","wu1ran3","to pollute / to contaminate",4,"verb"],["汤","tang1","soup / hot or boiling water",4,"noun"],
["汽水","qi4shui3","soda pop / carbonated soft drink",4,"noun"],["油","you2","oil / fat",4,"noun"],
["法","fa3","law / method",4,"noun"],["法律","fa3lv4","law",4,"noun"],["活","huo2","to live / alive",4,"verb"],
["活动","huo2dong4","to exercise / to move about",4,"verb"],["活泼","huo2po5","lively / vivacious",4,"adj"],
["流","liu2","to flow / to disseminate",4,"verb"],["流利","liu2li4","fluent",4,"adj"],
["流行","liu2xing2","(of a contagious disease etc) to spread",4,"verb"],["浪漫","lang4man4","romantic",4,"adj"],
["浪费","lang4fei4","to waste / to squander",4,"verb"],["海洋","hai3yang2","ocean",4,"noun"],
["消息","xiao1xi5","(piece of) news / information",4,"noun"],["深","shen1","deep",4,"adj"],
["温度","wen1du4","temperature",4,"noun"],["游玩","you2wan2","to amuse oneself / to have fun",4,"verb"],
["满","man3","to fill / full",4,"verb"],["演","yan3","to perform / to stage",4,"verb"],
["演出","yan3chu1","to act / to perform",4,"verb"],["演员","yan3yuan2","actor / actress",4,"noun"],
["演唱","yan3chang4","to sing / vocal performance",4,"verb"],["激动","ji1dong4","to move emotionally",4,"verb"],
["火","huo3","fire / urgent",4,"noun"],["点名","dian3ming2","roll call / to mention sb by name",4,"verb"],
["点头","dian3tou2","to nod",4,"verb"],["烟","yan1","cigarette or pipe tobacco",4,"noun"],
["烤","kao3","to roast / to grill",4,"verb"],["烦","fan2","to feel vexed / to bother",4,"verb"],
["烦恼","fan2nao3","to be worried / to be distressed",4,"verb"],
["热闹","re4nao5","bustling with noise and excitement",4,"adj"],["然而","ran2er2","however / but",4,"function"],
["熊","xiong2","bear / to scold",4,"noun"],["熟","shu2","ripe / mature",4,"adj"],
["熟悉","shu2xi1","to be familiar with",4,"verb"],["爱心","ai4xin1","compassion / kindness",4,"noun"],
["父亲","fu4qin1","father",4,"noun"],["父女","fu4nv3","father and daughter",4,"noun"],
["父子","fu4zi3","father and son",4,"noun"],["父母","fu4mu3","father and mother / parents",4,"noun"],
["片","pian4","thin piece / flake",4,"function"],["牌","pai2","signboard / plaque",4,"noun"],
["牌子","pai2zi5","sign / trademark",4,"noun"],["牙膏","ya2gao1","toothpaste",4,"noun"],
["特点","te4dian3","characteristic / trait",4,"noun"],["环保","huan2bao3","environmental protection",4,"noun"],
["现有","xian4you3","currently existing",4,"verb"],["现金","xian4jin1","cash",4,"noun"],["球迷","qiu2mi2","fan",4,"noun"],
["球队","qiu2dui4","sports team",4,"noun"],["理发","li3fa4","to get a haircut / to have one's hair done",4,"verb"],
["理想","li3xiang3","an ideal / a dream",4,"noun"],["理解","li3jie3","to comprehend / to understand",4,"verb"],
["琴","qin2","stringed instrument",4,"noun"],["甚至","shen4zhi4","even / so much so that",4,"adv"],
["生","sheng1","to be born / to give birth",4,"verb"],["生命","sheng1ming4","life / living being",4,"noun"],
["生意","sheng1yi4","life force / vitality",4,"noun"],["用于","yong4yu2","to use in / to use on",4,"verb"],
["用来","yong4lai2","to be used for",4,"verb"],["由","you2","to follow / from",4,"verb"],
["由于","you2yu2","due to / as a result of",4,"function"],
["申请","shen1qing3","to apply for sth / application form",4,"verb"],
["电动车","dian4dong4che1","electric vehicle",4,"noun"],["电视剧","dian4shi4ju4","TV series / TV drama",4,"noun"],
["男士","nan2shi4","man / gentleman",4,"noun"],["男性","nan2xing4","the male sex / a male",4,"noun"],
["留","liu2","to leave / to retain",4,"verb"],["留下","liu2xia4","to leave behind / to stay behind",4,"verb"],
["痛","tong4","ache / pain",4,"adj"],["登机","deng1ji1","to board a plane",4,"verb"],
["白酒","bai2jiu3","baijiu, a spirit usually distilled from sorghum",4,"noun"],["皮肤","pi2fu1","skin",4,"noun"],
["皮鞋","pi2xie2","leather shoes",4,"noun"],["盐","yan2","salt",4,"noun"],["盒子","he2zi5","box / case",4,"noun"],
["目前","mu4qian2","at the present time",4,"noun"],["目标","mu4biao1","target / goal",4,"noun"],
["目的","mu4di4","purpose / aim",4,"noun"],["目的地","mu4di4di4","destination",4,"noun"],
["直接","zhi2jie1","direct / immediate",4,"adj"],["相互","xiang1hu4","each other / mutual",4,"adv"],
["相反","xiang1fan3","opposite / contrary",4,"verb"],["相同","xiang1tong2","identical / same",4,"adj"],
["相比","xiang1bi3","to compare",4,"verb"],["省","sheng3","to save / to economize",4,"verb"],
["看法","kan4fa3","way of looking at a thing",4,"noun"],["真正","zhen1zheng4","genuine / real",4,"adj"],
["眼前","yan3qian2","before one's eyes / now",4,"noun"],["眼镜","yan3jing4","spectacles / eyeglasses",4,"noun"],
["着火","zhao2huo3","to catch fire",4,"verb"],["知识","zhi1shi5","knowledge / intellectual",4,"noun"],
["短信","duan3xin4","text message / SMS",4,"noun"],["研究","yan2jiu1","research / a study",4,"noun"],
["研究生","yan2jiu1sheng1","graduate student / postgraduate student",4,"noun"],["破","po4","broken / damaged",4,"adj"],
["硕士","shuo4shi4","master's degree",4,"noun"],["确实","que4shi2","indeed / really",4,"adj"],
["礼貌","li3mao4","courtesy / politeness",4,"noun"],["社会","she4hui4","society",4,"noun"],
["祝","zhu4","to pray for / to wish",4,"verb"],["祝贺","zhu4he4","to congratulate / congratulations",4,"verb"],
["禁止","jin4zhi3","to prohibit / to forbid",4,"verb"],["科学","ke1xue2","science / scientific knowledge",4,"noun"],
["科技","ke1ji4","science and technology",4,"noun"],["秒","miao3","second / arc second",4,"noun"],
["租","zu1","to hire / to rent",4,"verb"],["积极","ji1ji2","active / energetic",4,"adj"],
["积累","ji1lei3","to accumulate / accumulation",4,"verb"],["稍","shao1","somewhat / a little",4,"adv"],
["稍微","shao1wei1","a little bit",4,"adv"],["究竟","jiu1jing4","to go to the bottom of a matter",4,"verb"],
["空","kong1","empty / air",4,"adj"],["空气","kong1qi4","air / atmosphere",4,"noun"],["窗","chuang1","window",4,"noun"],
["竞争","jing4zheng1","to compete / competition",4,"verb"],
["竟然","jing4ran2","unexpectedly / to one's surprise",4,"adv"],["童年","tong2nian2","childhood",4,"noun"],
["笑话","xiao4hua5","joke / jest",4,"noun"],["笔试","bi3shi4","written examination",4,"noun"],
["符合","fu2he2","in accordance with",4,"verb"],["等到","deng3dao4","to wait until / by the time when",4,"verb"],
["答","da2","to answer / to reply",4,"verb"],["答应","da1ying5","to answer / to respond",4,"verb"],
["签证","qian1zheng4","visa / to issue a visa",4,"noun"],["算","suan4","to regard as / to figure",4,"verb"],
["管","guan3","to take care / to control",4,"verb"],["管理","guan3li3","to supervise / to manage",4,"verb"],
["篇","pian1","sheet / piece of writing",4,"function"],["粗","cu1","(of sth long) wide",4,"adj"],
["精彩","jing1cai3","wonderful / marvelous",4,"adj"],["紧张","jin3zhang1","nervous / keyed up",4,"adj"],
["红包","hong2bao1","money wrapped in red as a gift",4,"noun"],["约","yue1","to make an appointment",4,"verb"],
["约会","yue1hui4","appointment / engagement",4,"verb"],["纸巾","zhi3jin1","paper towel / napkin",4,"noun"],
["线上","xian4shang4","online",4,"noun"],["线下","xian4xia4","offline / below the line",4,"noun"],
["组","zu3","to form / to organize",4,"verb"],["细","xi4","thin or slender / finely particulate",4,"adj"],
["细心","xi4xin1","meticulous / careful",4,"noun"],["经历","jing1li4","to experience / to go through",4,"verb"],
["经济","jing1ji4","economy / economic",4,"noun"],["经验","jing1yan4","experience / to go through",4,"noun"],
["结果","jie1guo3","to bear fruit",4,"verb"],["结账","jie2zhang4","to settle accounts",4,"verb"],
["继续","ji4xu4","to continue / to proceed with",4,"verb"],["缺","que1","deficiency / lack",4,"verb"],
["缺少","que1shao3","lack / shortage of",4,"verb"],["缺点","que1dian3","weak point / fault",4,"noun"],
["网友","wang3you3","online friend / netizen",4,"noun"],["网址","wang3zhi3","website / web address",4,"noun"],
["网购","wang3gou4","Internet shopping / to purchase online",4,"noun"],["网页","wang3ye4","web page",4,"noun"],
["美","mei3","beautiful / very satisfactory",4,"adj"],["美丽","mei3li4","beautiful",4,"adj"],
["美好","mei3hao3","beautiful / fine",4,"adj"],["美景","mei3jing3","beautiful scenery",4,"noun"],
["美食","mei3shi2","culinary delicacy / fine food",4,"noun"],["羡慕","xian4mu4","to envy / to admire",4,"verb"],
["翻译","fan1yi4","to translate / to interpret",4,"verb"],["老家","lao3jia1","native place / place of origin",4,"noun"],
["老年","lao3nian2","elderly / old age",4,"noun"],["老是","lao3shi5","always",4,"adv"],["老虎","lao3hu3","tiger",4,"noun"],
["考生","kao3sheng1","exam candidate",4,"noun"],["考虑","kao3lv4","to think over / to consider",4,"verb"],
["者","zhe3","(after a verb or adjective) one who (is) ...",4,"function"],["而","er2","and / as well as",4,"function"],
["耐心","nai4xin1","to be patient / patience",4,"verb"],["职业","zhi2ye4","occupation / profession",4,"noun"],
["联系","lian2xi4","connection / contact",4,"verb"],["聚","ju4","to assemble / to gather",4,"verb"],
["聚会","ju4hui4","party / gathering",4,"verb"],["聚餐","ju4can1","communal meal",4,"noun"],
["肚子","du4zi5","belly / abdomen",4,"noun"],["肯定","ken3ding4","to be certain / to be positive",4,"verb"],
["背","bei4","the back of a body or object",4,"verb"],["背包","bei1bao1","knapsack / rucksack",4,"noun"],
["胳膊","ge1bo5","arm",4,"noun"],["能力","neng2li4","capability / ability",4,"noun"],
["能否","neng2fou3","whether or not / can it or can't it",4,"verb"],
["能够","neng2gou4","to be capable of / to be able to",4,"verb"],["脱","tuo1","to shed / to take off",4,"verb"],
["脾气","pi2qi5","character / temperament",4,"noun"],["自","zi4","self / oneself",4,"function"],
["自习","zi4xi2","to study outside of class time",4,"verb"],["自信","zi4xin4","to have confidence in oneself",4,"verb"],
["自学","zi4xue2","self-study / to study on one's own",4,"verb"],["自然","zi4ran2","nature / natural",4,"noun"],
["至少","zhi4shao3","at least / (to say the) least",4,"adv"],["航班","hang2ban1","(scheduled) flight",4,"noun"],
["艺术","yi4shu4","art",4,"noun"],["节假日","jie2jia4ri4","public holiday",4,"noun"],
["节约","jie2yue1","to economize / to conserve",4,"verb"],["苦","ku3","bitter / hardship",4,"adj"],
["茶叶","cha2ye4","tea / tea leaves",4,"noun"],["获取","huo4qu3","to gain / to get",4,"verb"],
["获奖","huo4jiang3","to win an award",4,"verb"],["获得","huo4de2","to obtain / to receive",4,"verb"],
["落","luo4","to fall or drop / (of the sun) to set",4,"verb"],["著名","zhu4ming2","famous / noted",4,"noun"],
["葡萄","pu2tao5","grape",4,"noun"],["葡萄酒","pu2tao5jiu3","(grape) wine",4,"noun"],
["血","xue4","blood / colloquial pr.",4,"noun"],["街道","jie1dao4","street / subdistrict",4,"noun"],
["表","biao3","exterior surface",4,"noun"],["表现","biao3xian4","to show / to show off",4,"verb"],
["袋子","dai4zi5","bag",4,"noun"],["袜子","wa4zi5","socks / stockings",4,"noun"],
["装","zhuang1","adornment / to adorn",4,"verb"],["西红柿","xi1hong2shi4","tomato",4,"noun"],
["西部","xi1bu4","western part",4,"noun"],["要是","yao4shi5","if",4,"function"],
["观众","guan1zhong4","spectators / audience",4,"noun"],["观看","guan1kan4","to watch / to view",4,"verb"],
["规定","gui1ding4","to stipulate / to specify",4,"verb"],["视频","shi4pin2","video",4,"noun"],
["解释","jie3shi4","explanation / to explain",4,"verb"],["警察","jing3cha2","police / police officer",4,"noun"],
["计划","ji4hua4","plan / project",4,"noun"],["订","ding4","to agree / to conclude",4,"verb"],
["讨厌","tao3yan4","to dislike / to loathe",4,"verb"],["讨论","tao3lun4","to discuss / to talk over",4,"verb"],
["记者","ji4zhe3","reporter / journalist",4,"noun"],["许多","xu3duo1","many / a lot of",4,"function"],
["证","zheng4","to admonish",4,"verb"],["证件","zheng4jian4","certificate / papers",4,"noun"],
["证明","zheng4ming2","proof / certificate",4,"verb"],["试题","shi4ti2","exam question / test topic",4,"noun"],
["话剧","hua4ju4","stage play / modern drama",4,"noun"],["详细","xiang2xi4","detailed / in detail",4,"adj"],
["语法","yu3fa3","grammar",4,"noun"],["误会","wu4hui4","to misunderstand / to mistake",4,"verb"],
["说明","shuo1ming2","to explain / to illustrate",4,"verb"],["说明书","shuo1ming2shu1","(technical) manual",4,"noun"],
["说法","shuo1fa3","to expound Buddhist teachings",4,"verb"],["读者","du2zhe3","reader",4,"noun"],
["课堂","ke4tang2","classroom / class session",4,"noun"],["课程","ke4cheng2","course / academic program",4,"noun"],
["调查","diao4cha2","investigation / inquiry",4,"verb"],["谈","tan2","to speak / to talk",4,"verb"],
["负责","fu4ze2","to be responsible for",4,"verb"],["负责人","fu4ze2ren2","person in charge",4,"noun"],
["责任","ze2ren4","responsibility / blame",4,"noun"],["货","huo4","goods / money",4,"noun"],
["质量","zhi4liang4","(physics) mass / quality",4,"noun"],["购买","gou4mai3","to purchase / to buy",4,"verb"],
["购物","gou4wu4","shopping",4,"verb"],["费","fei4","to cost / to spend",4,"verb"],
["费用","fei4yong4","cost / expenditure",4,"noun"],["资料","zi1liao4","material / resources",4,"noun"],
["赚","zhuan4","to earn / to make a profit",4,"verb"],["赢","ying2","to beat / to win",4,"verb"],
["赢得","ying2de2","to win / to gain",4,"verb"],["赶","gan3","to overtake / to catch up with",4,"verb"],
["赶上","gan3shang4","to keep up with / to catch up with",4,"verb"],["赶快","gan3kuai4","quickly / at once",4,"adv"],
["赶紧","gan3jin3","hurriedly / without delay",4,"adv"],["起到","qi3dao4","to play a role / to have an effect",4,"verb"],
["趟","tang4","classifier for times, round trips or rows",4,"verb"],
["距离","ju4li2","distance / to be apart from",4,"noun"],["路过","lu4guo4","to pass by or through",4,"verb"],
["身","shen1","body / life",4,"noun"],["身份证","shen1fen4zheng4","identity card / ID",4,"noun"],
["躺","tang3","to recline / to lie down",4,"verb"],["车位","che1wei4","parking spot / unloading point",4,"noun"],
["车速","che1su4","vehicle speed",4,"noun"],["转","zhuan3","to turn / to change direction",4,"verb"],
["转发","zhuan3fa1","to transmit / to forward",4,"verb"],["转机","zhuan3ji1","(to take) a turn for the better",4,"noun"],
["轻","qing1","light / easy",4,"adj"],["轻松","qing1song1","light / gentle",4,"adj"],
["输","shu1","to lose / to be beaten",4,"verb"],["辛苦","xin1ku3","exhausting / hard",4,"adj"],
["辣","la4","hot / pungent",4,"adj"],["达到","da2dao4","to reach / to achieve",4,"verb"],
["过程","guo4cheng2","course of events / process",4,"noun"],["进入","jin4ru4","to enter / to join",4,"verb"],
["进行","jin4xing2","(of a process etc) to proceed",4,"verb"],
["远离","yuan3li2","to be far from / to keep away from",4,"verb"],["连","lian2","to link / to join",4,"verb"],
["迟","chi2","late / delayed",4,"adj"],["适合","shi4he2","to fit / to suit",4,"verb"],
["适应","shi4ying4","to adapt / to fit",4,"verb"],["通","tong1","to go through / to know well",4,"verb"],
["通知","tong1zhi1","to notify / to inform",4,"verb"],["通过","tong1guo4","to pass through / to get through",4,"verb"],
["逛","guang4","to stroll / to visit",4,"verb"],["速度","su4du4","speed / rate",4,"noun"],
["道","dao4","road / path",4,"noun"],["道歉","dao4qian4","to apologize",4,"verb"],
["道路","dao4lu4","road / path",4,"noun"],["邀请","yao1qing3","to invite / invitation",4,"verb"],
["郊区","jiao1qu1","suburban district / outskirts",4,"noun"],["部","bu4","ministry / department",4,"function"],
["部门","bu4men2","department / branch",4,"noun"],["酸","suan1","sour / tart",4,"adj"],
["酸奶","suan1nai3","yogurt",4,"noun"],["醒","xing3","to wake up / to be awake",4,"verb"],
["重","zhong4","heavy / serious",4,"adj"],["重点","chong2dian3","to recount / to re-evaluate",4,"verb"],
["重视","zhong4shi4","to attach importance to sth",4,"verb"],["量","liang4","capacity / quantity",4,"noun"],
["钢琴","gang1qin2","piano",4,"noun"],["钥匙","yao4shi5","key",4,"noun"],["错过","cuo4guo4","to miss",4,"verb"],
["镜子","jing4zi5","mirror",4,"noun"],["闻","wen2","to hear / news",4,"verb"],
["阅读","yue4du2","to read / reading",4,"verb"],["队","dui4","squadron / team",4,"noun"],
["队员","dui4yuan2","team member",4,"noun"],["队长","dui4zhang3","captain / team leader",4,"noun"],
["阳光","yang2guang1","sunshine / (of personality) upbeat",4,"noun"],["降","jiang4","to drop / to fall",4,"verb"],
["降价","jiang4jia4","to cut the price / to drive down the price",4,"verb"],
["降低","jiang4di1","to reduce / to lower",4,"verb"],["降温","jiang4wen1","to become cooler",4,"verb"],
["降落","jiang4luo4","to descend / to land",4,"verb"],["院子","yuan4zi5","courtyard / garden",4,"noun"],
["院长","yuan4zhang3","dean / head of institution",4,"noun"],["陪","pei2","to accompany / to keep sb company",4,"verb"],
["随便","sui2bian4","as one wishes / as one pleases",4,"adj"],
["随着","sui2zhe5","along with / in the wake of",4,"function"],
["难受","nan2shou4","to feel unwell / to suffer pain",4,"verb"],["难忘","nan2wang4","unforgettable",4,"adj"],
["难道","nan2dao4","don't tell me ... / could it be that...?",4,"adv"],["零下","ling2xia4","below zero",4,"noun"],
["零花钱","ling2hua1qian2","pocket money / allowance",4,"noun"],["零钱","ling2qian2","change / small change",4,"noun"],
["零食","ling2shi2","snack / nibbles",4,"noun"],["青年","qing1nian2","youth / youthful years",4,"noun"],
["面对","mian4dui4","to face / to confront",4,"verb"],["面试","mian4shi4","to be interviewed / interview",4,"verb"],
["项","xiang4","back of neck / item",4,"function"],["顺便","shun4bian4","conveniently / in passing",4,"noun"],
["顺利","shun4li4","smoothly / without a hitch",4,"adj"],["顺序","shun4xu4","sequence / order",4,"noun"],
["顾客","gu4ke4","customer / client",4,"noun"],["顿","dun4","to stop / to pause",4,"verb"],
["预习","yu4xi2","to prepare a lesson",4,"verb"],["风景","feng1jing3","scenery / landscape",4,"noun"],
["食品","shi2pin3","foodstuff / food",4,"noun"],["食堂","shi2tang2","dining hall / cafeteria",4,"noun"],
["食物","shi2wu4","food",4,"noun"],["馒头","man2tou5","steamed bun",4,"noun"],["首","shou3","head / chief",4,"function"],
["首先","shou3xian1","first / in the first place",4,"adv"],["首都","shou3du1","capital",4,"noun"],
["香","xiang1","fragrant / sweet smelling",4,"noun"],["骄傲","jiao1ao4","pride / arrogance",4,"noun"],
["高于","gao1yu2","greater than / to exceed",4,"verb"],["高价","gao1jia4","high price",4,"noun"],
["高温","gao1wen1","high temperature",4,"noun"],["高考","gao1kao3","college entrance exam",4,"noun"],
["高速","gao1su4","high speed / expressway",4,"adj"],["鲜","xian1","fresh / bright",4,"adj"],
["鲜花","xian1hua1","flower / fresh flowers",4,"noun"],["麻烦","ma2fan5","trouble / inconvenience",4,"noun"],
["鼓励","gu3li4","to encourage",4,"verb"]
];

/* ------------------------------------------------------------
   RELEVEL_V2 - words already in WORDS whose HSK 3.0 band differs from
   the level they currently carry.  [word, current level, HSK 3.0 band]
   ------------------------------------------------------------ */
const RELEVEL_V2=[
["前面",1,2],["后面",1,2],["一下",2,1],["上班",2,1],["两",2,1],["也",2,1],["件",2,1],["休息",2,1],["便宜",2,1],["公司",2,1],["再",2,1],
["到",2,1],["千",2,1],["卖",2,1],["去年",2,1],["可以",2,1],["吧",2,1],["哥哥",2,1],["外",2,1],["大家",2,1],["女",2,1],["好吃",2,1],
["妹妹",2,1],["姐姐",2,1],["孩子",2,1],["它",2,1],["对",2,1],["小时",2,1],["弟弟",2,1],["忙",2,1],["您",2,1],["房间",2,1],["手机",2,1],
["找",2,1],["新",2,1],["日",2,1],["早上",2,1],["时间",2,1],["晚上",2,1],["正在",2,1],["牛奶",2,1],["玩",2,1],["生病",2,1],["男",2,1],
["百",2,1],["真",2,1],["知道",2,1],["穿",2,1],["给",2,1],["要",2,1],["觉得",2,1],["说话",2,1],["课",2,1],["贵",2,1],["起床",2,1],
["还",2,1],["问",2,1],["问题",2,1],["雪",2,1],["零",2,1],["非常",2,1],["鸡蛋",2,1],["宾馆",2,3],["帮助",2,3],["报纸",2,3],["西瓜",2,3],
["铅笔",2,3],["半",3,1],["超市",3,1],["包",3,2],["地",3,2],["地铁",3,2],["帮忙",3,2],["爱好",3,2],["班",3,2],["出现",3,4],["厨房",3,4],
["鼻子",3,4],["包子",4,1],["出发",4,3],["出生",4,3],["安全",4,3],["差不多",4,3],["比如",4,3],["表演",4,3],["遍",4,3]
];
