/* ============================================================
   WORD DATA — [character, pinyin (tone numbers), english, HSK level]
   HSK 1 and 2 are complete standard lists. HSK 3 and 4 are
   PARTIAL placeholder sets — replace with your full word data.
   ============================================================ */
const WORDS=[
/* ---- HSK 1 ---- */
["爱","ai4","to love",1,"verb"],["八","ba1","eight",1,"function"],["爸爸","ba4ba5","dad",1,"noun"],["杯子","bei1zi5","cup",1,"noun"],
["北京","Bei3jing1","Beijing",1,"noun"],["本","ben3","(measure: books)",1,"function"],["不","bu4","no / not",1,"noun"],
["不客气","bu2ke4qi5","you're welcome",1,"noun"],["菜","cai4","dish / vegetable",1,"noun"],["茶","cha2","tea",1,"noun"],
["吃","chi1","to eat",1,"verb"],["出租车","chu1zu1che1","taxi",1,"noun"],["打电话","da3dian4hua4","make a phone call",1,"noun"],
["大","da4","big",1,"adj"],["的","de5","(possessive particle)",1,"function"],["点","dian3","o'clock / dot",1,"noun"],
["电脑","dian4nao3","computer",1,"noun"],["电视","dian4shi4","television",1,"noun"],["电影","dian4ying3","movie",1,"noun"],
["东西","dong1xi5","thing",1,"noun"],["都","dou1","all / both",1,"noun"],["读","du2","to read",1,"verb"],
["对不起","dui4bu5qi3","sorry",1,"noun"],["多","duo1","many / much",1,"adj"],["多少","duo1shao3","how many / much",1,"pronoun"],
["儿子","er2zi5","son",1,"noun"],["二","er4","two",1,"function"],["饭店","fan4dian4","restaurant / hotel",1,"noun"],
["飞机","fei1ji1","airplane",1,"noun"],["分钟","fen1zhong1","minute",1,"noun"],["高兴","gao1xing4","happy / glad",1,"adj"],
["个","ge4","(general measure word)",1,"function"],["工作","gong1zuo4","work / job",1,"noun"],["狗","gou3","dog",1,"noun"],
["汉语","Han4yu3","Chinese language",1,"noun"],["好","hao3","good",1,"noun"],["号","hao4","date / number",1,"noun"],
["喝","he1","to drink",1,"verb"],["和","he2","and",1,"function"],["很","hen3","very",1,"adv"],["后面","hou4mian4","behind",1,"noun"],
["回","hui2","to return",1,"verb"],["会","hui4","can / will",1,"verb"],["几","ji3","how many / several",1,"pronoun"],
["家","jia1","home / family",1,"noun"],["叫","jiao4","to be called",1,"verb"],["今天","jin1tian1","today",1,"noun"],
["九","jiu3","nine",1,"function"],["开","kai1","to open / drive",1,"verb"],["看","kan4","to look / watch",1,"verb"],
["看见","kan4jian4","to see",1,"verb"],["块","kuai4","yuan (money)",1,"noun"],["来","lai2","to come",1,"verb"],
["老师","lao3shi1","teacher",1,"noun"],["了","le5","(completed action particle)",1,"function"],["冷","leng3","cold",1,"adj"],
["里","li3","inside",1,"noun"],["六","liu4","six",1,"function"],["妈妈","ma1ma5","mum",1,"noun"],["吗","ma5","(question particle)",1,"function"],
["买","mai3","to buy",1,"verb"],["猫","mao1","cat",1,"noun"],["没关系","mei2guan1xi5","it's okay",1,"noun"],
["没有","mei2you3","to not have",1,"verb"],["米饭","mi3fan4","cooked rice",1,"noun"],["名字","ming2zi5","name",1,"noun"],
["明天","ming2tian1","tomorrow",1,"noun"],["哪","na3","which",1,"pronoun"],["那","na4","that",1,"pronoun"],
["呢","ne5","(question particle)",1,"function"],["能","neng2","can / be able to",1,"verb"],["你","ni3","you",1,"pronoun"],
["年","nian2","year",1,"noun"],["女儿","nv3er2","daughter",1,"noun"],["朋友","peng2you5","friend",1,"noun"],
["漂亮","piao4liang5","pretty",1,"adj"],["苹果","ping2guo3","apple",1,"noun"],["七","qi1","seven",1,"function"],
["前面","qian2mian4","in front",1,"noun"],["钱","qian2","money",1,"noun"],["请","qing3","please",1,"noun"],
["去","qu4","to go",1,"verb"],["热","re4","hot",1,"adj"],["人","ren2","person",1,"noun"],["认识","ren4shi5","to know (someone)",1,"verb"],
["三","san1","three",1,"function"],["商店","shang1dian4","shop",1,"noun"],["上","shang4","up / on",1,"noun"],
["上午","shang4wu3","morning",1,"noun"],["少","shao3","few / little",1,"adj"],["谁","shei2","who",1,"pronoun"],
["什么","shen2me5","what",1,"pronoun"],["十","shi2","ten",1,"function"],["时候","shi2hou5","time / moment",1,"noun"],
["是","shi4","to be",1,"verb"],["书","shu1","book",1,"noun"],["水","shui3","water",1,"noun"],["水果","shui3guo3","fruit",1,"noun"],
["睡觉","shui4jiao4","to sleep",1,"verb"],["说","shuo1","to speak",1,"verb"],["四","si4","four",1,"function"],
["岁","sui4","years old",1,"adj"],["他","ta1","he / him",1,"pronoun"],["她","ta1","she / her",1,"pronoun"],
["太","tai4","too (excessively)",1,"adv"],["天气","tian1qi4","weather",1,"noun"],["听","ting1","to listen",1,"verb"],
["同学","tong2xue2","classmate",1,"noun"],["喂","wei2","hello (on phone)",1,"noun"],["我","wo3","I / me",1,"pronoun"],
["我们","wo3men5","we / us",1,"pronoun"],["五","wu3","five",1,"function"],["喜欢","xi3huan5","to like",1,"verb"],
["下","xia4","down / under",1,"noun"],["下午","xia4wu3","afternoon",1,"noun"],["下雨","xia4yu3","to rain",1,"verb"],
["先生","xian1sheng5","Mr / sir",1,"noun"],["现在","xian4zai4","now",1,"noun"],["想","xiang3","to want / think",1,"verb"],
["小","xiao3","small",1,"adj"],["小姐","xiao3jie3","Miss",1,"noun"],["些","xie1","some",1,"noun"],["写","xie3","to write",1,"verb"],
["谢谢","xie4xie5","thanks",1,"noun"],["星期","xing1qi1","week",1,"noun"],["学生","xue2sheng5","student",1,"noun"],
["学习","xue2xi2","to study",1,"verb"],["学校","xue2xiao4","school",1,"noun"],["一","yi1","one",1,"function"],
["衣服","yi1fu5","clothes",1,"noun"],["医生","yi1sheng1","doctor",1,"noun"],["医院","yi1yuan4","hospital",1,"noun"],
["椅子","yi3zi5","chair",1,"noun"],["有","you3","to have",1,"verb"],["月","yue4","month / moon",1,"noun"],
["再见","zai4jian4","goodbye",1,"noun"],["在","zai4","at / in",1,"function"],["怎么","zen3me5","how",1,"pronoun"],
["怎么样","zen3me5yang4","how about",1,"pronoun"],["这","zhe4","this",1,"pronoun"],["中国","Zhong1guo2","China",1,"noun"],
["中午","zhong1wu3","noon",1,"noun"],["住","zhu4","to live / reside",1,"verb"],["桌子","zhuo1zi5","table",1,"noun"],
["字","zi4","character / word",1,"noun"],["昨天","zuo2tian1","yesterday",1,"noun"],["坐","zuo4","to sit",1,"verb"],
["做","zuo4","to do / make",1,"verb"],
/* ---- HSK 2 ---- */
["吧","ba5","(suggestion particle)",2,"function"],["白","bai2","white",2,"adj"],["百","bai3","hundred",2,"function"],
["帮助","bang1zhu4","to help",2,"verb"],["报纸","bao4zhi3","newspaper",2,"noun"],["比","bi3","to compare / than",2,"function"],
["别","bie2","don't",2,"noun"],["宾馆","bin1guan3","hotel",2,"noun"],["长","chang2","long",2,"adj"],
["唱歌","chang4ge1","to sing",2,"verb"],["出","chu1","to go out",2,"verb"],["穿","chuan1","to wear",2,"verb"],
["次","ci4","time (occurrence)",2,"noun"],["从","cong2","from",2,"function"],["错","cuo4","wrong",2,"adj"],
["打篮球","da3lan2qiu2","play basketball",2,"noun"],["大家","da4jia1","everyone",2,"pronoun"],["到","dao4","to arrive",2,"verb"],
["得","de5","(structural particle)",2,"function"],["等","deng3","to wait",2,"verb"],["弟弟","di4di5","younger brother",2,"noun"],
["第一","di4yi1","first",2,"function"],["懂","dong3","to understand",2,"verb"],["对","dui4","correct / toward",2,"function"],
["房间","fang2jian1","room",2,"noun"],["非常","fei1chang2","very / extremely",2,"adv"],["服务员","fu2wu4yuan2","waiter",2,"noun"],
["高","gao1","tall / high",2,"adj"],["告诉","gao4su5","to tell",2,"verb"],["哥哥","ge1ge5","older brother",2,"noun"],
["给","gei3","to give",2,"verb"],["公共汽车","gong1gong4qi4che1","bus",2,"noun"],["公司","gong1si1","company",2,"noun"],
["贵","gui4","expensive",2,"adj"],["过","guo4","(experience particle)",2,"function"],["还","hai2","still / also",2,"adv"],
["孩子","hai2zi5","child",2,"noun"],["好吃","hao3chi1","delicious",2,"adj"],["黑","hei1","black",2,"adj"],
["红","hong2","red",2,"adj"],["火车站","huo3che1zhan4","train station",2,"noun"],["机场","ji1chang3","airport",2,"noun"],
["鸡蛋","ji1dan4","egg",2,"noun"],["件","jian4","(measure: clothes/items)",2,"function"],["教室","jiao4shi4","classroom",2,"noun"],
["姐姐","jie3jie5","older sister",2,"noun"],["介绍","jie4shao4","to introduce",2,"verb"],["进","jin4","to enter",2,"verb"],
["近","jin4","near",2,"adj"],["就","jiu4","then / right away",2,"noun"],["觉得","jue2de5","to feel / think",2,"verb"],
["咖啡","ka1fei1","coffee",2,"noun"],["开始","kai1shi3","to begin",2,"verb"],["考试","kao3shi4","exam",2,"noun"],
["可能","ke3neng2","maybe",2,"adv"],["可以","ke3yi3","can / may",2,"verb"],["课","ke4","class / lesson",2,"noun"],
["快","kuai4","fast",2,"adj"],["快乐","kuai4le4","happy",2,"adj"],["累","lei4","tired",2,"adj"],
["离","li2","away from",2,"function"],["两","liang3","two (+ measure word)",2,"function"],["零","ling2","zero",2,"function"],
["路","lu4","road",2,"noun"],["旅游","lv3you2","to travel",2,"verb"],["卖","mai4","to sell",2,"verb"],
["慢","man4","slow",2,"adj"],["忙","mang2","busy",2,"adj"],["每","mei3","every",2,"noun"],
["妹妹","mei4mei5","younger sister",2,"noun"],["门","men2","door",2,"noun"],["面条","mian4tiao2","noodles",2,"noun"],
["男","nan2","male",2,"adj"],["您","nin2","you (polite)",2,"pronoun"],["牛奶","niu2nai3","milk",2,"noun"],
["女","nv3","female",2,"adj"],["旁边","pang2bian1","beside",2,"noun"],["跑步","pao3bu4","to run / jog",2,"verb"],
["便宜","pian2yi5","cheap",2,"adj"],["票","piao4","ticket",2,"noun"],["妻子","qi1zi5","wife",2,"noun"],
["起床","qi3chuang2","to get up",2,"verb"],["千","qian1","thousand",2,"function"],["铅笔","qian1bi3","pencil",2,"noun"],
["晴","qing2","sunny",2,"adj"],["去年","qu4nian2","last year",2,"noun"],["让","rang4","to let / allow",2,"verb"],
["日","ri4","day / sun",2,"noun"],["上班","shang4ban1","to go to work",2,"verb"],["身体","shen1ti3","body / health",2,"noun"],
["生病","sheng1bing4","to get sick",2,"verb"],["生日","sheng1ri4","birthday",2,"noun"],["时间","shi2jian1","time",2,"noun"],
["事情","shi4qing5","matter / affair",2,"noun"],["手表","shou3biao3","wristwatch",2,"noun"],["手机","shou3ji1","mobile phone",2,"noun"],
["说话","shuo1hua4","to talk",2,"verb"],["送","song4","to give / deliver",2,"verb"],["虽然","sui1ran2","although",2,"function"],
["它","ta1","it",2,"pronoun"],["踢足球","ti1zu2qiu2","play football",2,"noun"],["题","ti2","question / problem",2,"noun"],
["跳舞","tiao4wu3","to dance",2,"verb"],["外","wai4","outside",2,"noun"],["完","wan2","to finish",2,"verb"],
["玩","wan2","to play",2,"verb"],["晚上","wan3shang5","evening",2,"noun"],["往","wang3","toward",2,"function"],
["为什么","wei4shen2me5","why",2,"pronoun"],["问","wen4","to ask",2,"verb"],["问题","wen4ti2","question / issue",2,"noun"],
["西瓜","xi1gua1","watermelon",2,"noun"],["希望","xi1wang4","to hope",2,"verb"],["洗","xi3","to wash",2,"verb"],
["小时","xiao3shi2","hour",2,"noun"],["笑","xiao4","to laugh / smile",2,"verb"],["新","xin1","new",2,"adj"],
["姓","xing4","surname",2,"noun"],["休息","xiu1xi5","to rest",2,"verb"],["雪","xue3","snow",2,"noun"],
["颜色","yan2se4","colour",2,"noun"],["眼睛","yan3jing5","eyes",2,"noun"],["羊肉","yang2rou4","mutton",2,"noun"],
["药","yao4","medicine",2,"noun"],["要","yao4","to want / will",2,"verb"],["也","ye3","also",2,"adv"],
["一起","yi4qi3","together",2,"adv"],["一下","yi2xia4","a bit / briefly",2,"noun"],["已经","yi3jing1","already",2,"adv"],
["意思","yi4si5","meaning",2,"noun"],["阴","yin1","cloudy",2,"adj"],["因为","yin1wei4","because",2,"function"],
["游泳","you2yong3","to swim",2,"verb"],["右边","you4bian5","right side",2,"noun"],["鱼","yu2","fish",2,"noun"],
["远","yuan3","far",2,"adj"],["运动","yun4dong4","sport / exercise",2,"noun"],["再","zai4","again",2,"adv"],
["早上","zao3shang5","morning",2,"noun"],["丈夫","zhang4fu5","husband",2,"noun"],["找","zhao3","to look for",2,"verb"],
["着","zhe5","(continuous particle)",2,"function"],["真","zhen1","really",2,"noun"],["正在","zheng4zai4","in the middle of",2,"adv"],
["知道","zhi1dao4","to know",2,"verb"],["准备","zhun3bei4","to prepare",2,"verb"],["走","zou3","to walk / leave",2,"verb"],
["最","zui4","most",2,"noun"],["左边","zuo3bian5","left side",2,"noun"],
/* ---- HSK 3 (PARTIAL — replace with your full list) ---- */
["阿姨","a1yi2","aunt",3,"noun"],["矮","ai3","short (height)",3,"adj"],["爱好","ai4hao4","hobby",3,"noun"],
["安静","an1jing4","quiet",3,"adj"],["把","ba3","(object marker)",3,"function"],["班","ban1","class / team",3,"noun"],
["搬","ban1","to move (house)",3,"verb"],["办法","ban4fa3","method / way",3,"noun"],["办公室","ban4gong1shi4","office",3,"noun"],
["半","ban4","half",3,"noun"],["帮忙","bang1mang2","to help out",3,"verb"],["包","bao1","bag",3,"noun"],
["饱","bao3","full (eaten)",3,"adj"],["北方","bei3fang1","the north",3,"noun"],["被","bei4","(passive marker)",3,"function"],
["鼻子","bi2zi5","nose",3,"noun"],["比较","bi3jiao4","relatively / compare",3,"noun"],["比赛","bi3sai4","competition",3,"noun"],
["笔记本","bi3ji4ben3","notebook",3,"noun"],["必须","bi4xu1","must",3,"noun"],["变化","bian4hua4","change",3,"noun"],
["别人","bie2ren2","other people",3,"noun"],["冰箱","bing1xiang1","fridge",3,"noun"],["不但","bu2dan4","not only",3,"function"],
["菜单","cai4dan1","menu",3,"noun"],["参加","can1jia1","to participate",3,"verb"],["草","cao3","grass",3,"noun"],
["层","ceng2","floor / layer",3,"noun"],["差","cha4","lacking / poor",3,"adj"],["超市","chao1shi4","supermarket",3,"noun"],
["衬衫","chen4shan1","shirt",3,"noun"],["成绩","cheng2ji4","grades / result",3,"noun"],["城市","cheng2shi4","city",3,"noun"],
["迟到","chi2dao4","to be late",3,"verb"],["出现","chu1xian4","to appear",3,"verb"],["厨房","chu2fang2","kitchen",3,"noun"],
["除了","chu2le5","except / besides",3,"function"],["船","chuan2","boat",3,"noun"],["春","chun1","spring",3,"noun"],
["词典","ci2dian3","dictionary",3,"noun"],["聪明","cong1ming5","clever",3,"adj"],["打扫","da3sao3","to clean",3,"verb"],
["打算","da3suan4","to plan",3,"verb"],["带","dai4","to bring",3,"verb"],["担心","dan1xin1","to worry",3,"verb"],
["蛋糕","dan4gao1","cake",3,"noun"],["当然","dang1ran2","of course",3,"adv"],["地","de5","(adverbial particle)",3,"function"],
["灯","deng1","lamp / light",3,"noun"],["地方","di4fang5","place",3,"noun"],["地铁","di4tie3","subway",3,"noun"],
["地图","di4tu2","map",3,"noun"],["电梯","dian4ti1","lift / elevator",3,"noun"],["电子邮件","dian4zi3you2jian4","email",3,"noun"],
["东","dong1","east",3,"noun"],["冬","dong1","winter",3,"noun"],["动物","dong4wu4","animal",3,"noun"],
["短","duan3","short (length)",3,"adj"],["段","duan4","section / paragraph",3,"noun"],["锻炼","duan4lian4","to work out",3,"verb"],
/* ---- HSK 4 (PARTIAL — replace with your full list) ---- */
["爱情","ai4qing2","(romantic) love",4,"function"],["安排","an1pai2","to arrange",4,"verb"],["安全","an1quan2","safe / safety",4,"adj"],
["按时","an4shi2","on time",4,"adv"],["按照","an4zhao4","according to",4,"function"],["百分之","bai3fen1zhi1","percent",4,"noun"],
["棒","bang4","great / awesome",4,"noun"],["包子","bao1zi5","steamed bun",4,"noun"],["保护","bao3hu4","to protect",4,"verb"],
["保证","bao3zheng4","to guarantee",4,"verb"],["抱","bao4","to hug",4,"verb"],["抱歉","bao4qian4","sorry / apologetic",4,"noun"],
["倍","bei4","times (multiple)",4,"noun"],["本来","ben3lai2","originally",4,"adv"],["笨","ben4","stupid",4,"noun"],
["比如","bi3ru2","for example",4,"noun"],["毕业","bi4ye4","to graduate",4,"verb"],["遍","bian4","(measure: times through)",4,"function"],
["标准","biao1zhun3","standard",4,"noun"],["表格","biao3ge2","form / table",4,"noun"],["表示","biao3shi4","to express",4,"verb"],
["表演","biao3yan3","to perform",4,"verb"],["表扬","biao3yang2","to praise",4,"verb"],["饼干","bing3gan1","biscuit",4,"noun"],
["并且","bing4qie3","moreover",4,"function"],["博士","bo2shi4","PhD / doctor",4,"noun"],["不得不","bu4de2bu4","to have to",4,"verb"],
["不管","bu4guan3","no matter",4,"adv"],["不过","bu2guo4","however",4,"function"],["不仅","bu4jin3","not only",4,"function"],
["部分","bu4fen5","part / section",4,"noun"],["擦","ca1","to wipe",4,"verb"],["猜","cai1","to guess",4,"verb"],
["材料","cai2liao4","material",4,"noun"],["参观","can1guan1","to visit (place)",4,"verb"],["餐厅","can1ting1","restaurant",4,"noun"],
["厕所","ce4suo3","toilet",4,"noun"],["差不多","cha4bu5duo1","almost / about",4,"adv"],["长城","Chang2cheng2","the Great Wall",4,"noun"],
["场","chang3","(measure: events)",4,"function"],["超过","chao1guo4","to exceed",4,"verb"],["成功","cheng2gong1","to succeed",4,"verb"],
["成为","cheng2wei2","to become",4,"verb"],["诚实","cheng2shi2","honest",4,"adj"],["乘坐","cheng2zuo4","to ride / take",4,"verb"],
["吃惊","chi1jing1","to be shocked",4,"verb"],["重新","chong2xin1","again / anew",4,"adv"],["抽烟","chou1yan1","to smoke",4,"verb"],
["出差","chu1chai1","business trip",4,"noun"],["出发","chu1fa1","to set off",4,"verb"],["出生","chu1sheng1","to be born",4,"verb"],
["窗户","chuang1hu5","window",4,"noun"],["词语","ci2yu3","words / terms",4,"noun"],["从来","cong2lai2","always / (never)",4,"adv"],
["粗心","cu1xin1","careless",4,"adj"],["存","cun2","to save / deposit",4,"verb"],["错误","cuo4wu4","mistake",4,"noun"],
["答案","da2an4","answer",4,"noun"],["打扮","da3ban4","to dress up",4,"verb"],["打扰","da3rao3","to disturb",4,"verb"],
["打印","da3yin4","to print",4,"verb"]
,
/* ---- MASTER (level 5): rare characters, trap readings, literary chengyu ---- */
["饕餮","tao1tie4","mythical gluttonous beast; glutton",5,"noun"],
["魑魅魍魉","chi1mei4wang3liang3","demons and monsters of every kind",5,"noun"],
["耄耋","mao4die2","advanced old age (one's 80s–90s)",5,"noun"],
["龃龉","ju3yu3","discord; friction",5,"noun"],
["踟蹰","chi2chu2","to hesitate; waver",5,"verb"],
["彳亍","chi4chu4","to stroll haltingly",5,"verb"],
["囹圄","ling2yu3","prison (literary)",5,"noun"],
["貔貅","pi2xiu1","mythical wealth-attracting beast",5,"noun"],
["觊觎","ji4yu2","to covet",5,"verb"],
["龌龊","wo4chuo4","filthy; sordid",5,"adj"],
["旮旯","ga1la2","nook; out-of-the-way corner",5,"noun"],
["邋遢","la1ta5","slovenly; unkempt",5,"adj"],
["熨帖","yu4tie1","fitting; just right",5,"adj"],
["拮据","jie2ju1","hard up; short of money",5,"adj"],
["桎梏","zhi4gu4","shackles; fetters",5,"noun"],
["缱绻","qian3quan3","tenderly attached (literary)",5,"adj"],
["旖旎","yi3ni3","charming; enchanting (scenery)",5,"adj"],
["蹉跎","cuo1tuo2","to idle away (time)",5,"verb"],
["婆娑","po2suo1","swaying; whirling",5,"adj"],
["逶迤","wei1yi2","winding; meandering",5,"adj"],
["璀璨","cui3can4","dazzling; resplendent",5,"adj"],
["圭臬","gui1nie4","criterion; standard (literary)",5,"noun"],
["造诣","zao4yi4","(scholarly) attainment",5,"noun"],
["商榷","shang1que4","open to deliberation",5,"verb"],
["掣肘","che4zhou3","to impede; hold back",5,"verb"],
["妊娠","ren4shen1","pregnancy; gestation",5,"noun"],
["症结","zheng1jie2","crux (of a problem)",5,"noun"],
["埋怨","man2yuan4","to blame; complain",5,"verb"],
["参差","cen1ci1","uneven; irregular",5,"adj"],
["龟裂","jun1lie4","to crack (of parched earth or skin)",5,"verb"],
["痼疾","gu4ji2","chronic ailment",5,"noun"],
["齉","nang4","to speak with a blocked nose",5,"verb"],
["爨","cuan4","to cook over a fire (archaic)",5,"verb"],
["龘","da2","the appearance of dragons in flight",5,"noun"],
["虚与委蛇","xu1yu3wei1yi2","to feign politeness",5,"idiom"],
["暴虎冯河","bao4hu3ping2he2","reckless bravery",5,"idiom"],
["沆瀣一气","hang4xie4yi2qi4","to collude; be in cahoots",5,"idiom"],
["暴殄天物","bao4tian3tian1wu4","to squander heaven's gifts",5,"idiom"],
["饮鸩止渴","yin3zhen4zhi3ke3","to drink poison to quench thirst",5,"idiom"],
["鳞次栉比","lin2ci4zhi4bi3","packed row upon row (of buildings)",5,"idiom"],
["佶屈聱牙","ji2qu1ao2ya2","convoluted and hard to read",5,"idiom"],
["踽踽独行","ju3ju3du2xing2","to walk alone in solitude",5,"idiom"],
["铩羽而归","sha1yu3er2gui1","to return defeated",5,"idiom"],
["醍醐灌顶","ti2hu2guan4ding3","sudden enlightenment",5,"idiom"],
["韬光养晦","tao1guang1yang3hui4","to hide one's talents and bide time",5,"idiom"],
["罄竹难书","qing4zhu2nan2shu1","crimes too numerous to record",5,"idiom"],
["良莠不齐","liang2you3bu4qi2","a mix of good and bad",5,"idiom"],
["味同嚼蜡","wei4tong2jiao2la4","dry and dull as chewing wax",5,"idiom"],
["高屋建瓴","gao1wu1jian4ling2","from a commanding strategic height",5,"idiom"],
["焚膏继晷","fen2gao1ji4gui3","to study day and night",5,"idiom"],
["管窥蠡测","guan3kui1li2ce4","a narrow, shallow view",5,"idiom"],
["胼手胝足","pian2shou3zhi1zu2","work-calloused hands and feet",5,"idiom"],
["筚路蓝缕","bi4lu4lan2lv3","to endure hardships pioneering",5,"idiom"],
["宵衣旰食","xiao1yi1gan4shi2","diligent from before dawn until late",5,"idiom"],
["睚眦必报","ya2zi4bi4bao4","to avenge the smallest slight",5,"idiom"],
["怙恶不悛","hu4e4bu4quan1","unrepentantly evil",5,"idiom"],
["一蹴而就","yi2cu4er2jiu4","to succeed in a single step",5,"idiom"],
["鞭辟入里","bian1pi4ru4li3","penetrating; incisive",5,"idiom"],
["荷枪实弹","he4qiang1shi2dan4","armed with loaded rifles",5,"idiom"],
["拾级而上","she4ji2er2shang4","to ascend step by step",5,"idiom"],

/* ---- MASTER II (level 7): literary register, classical allusion, abstract/philosophical
   vocabulary — the kind that trips up native speakers in essays and formal prose ---- */
["之乎者也","zhi1hu1zhe3ye3","stilted, archaic-sounding language",7,"idiom"],
["文以载道","wen2yi3zai4dao4","literature should convey moral truth",7,"idiom"],
["形而上","xing2er2shang4","metaphysical",7,"adj"],
["形而下","xing2er2xia4","physical; concrete (opp. of metaphysical)",7,"adj"],
["不刊之论","bu4kan1zhi1lun4","an irrefutable statement",7,"idiom"],
["振聋发聩","zhen4long2fa1kui4","a wake-up call; startling truth",7,"idiom"],
["空谷足音","kong1gu3zu2yin1","a rare and welcome visitor/event",7,"idiom"],
["曲高和寡","qu3gao1he4gua3","too refined to be popular",7,"idiom"],
["附庸风雅","fu4yong1feng1ya3","to affect cultural refinement",7,"idiom"],
["东施效颦","dong1shi1xiao4pin2","clumsy imitation that backfires",7,"idiom"],
["买椟还珠","mai3du2huan2zhu1","to miss the point; value the wrong thing",7,"idiom"],
["叶公好龙","ye4gong1hao4long2","professed love that crumbles when real",7,"idiom"],
["杞人忧天","qi3ren2you1tian1","needless anxiety over the impossible",7,"idiom"],
["塞翁失马","sai4weng1shi1ma3","a blessing in disguise",7,"idiom"],
["朝三暮四","zhao1san1mu4si4","fickle; playing word games to deceive",7,"idiom"],
["邯郸学步","han2dan1xue2bu4","losing one's own identity imitating others",7,"idiom"],
["刻舟求剑","ke4zhou1qiu2jian4","rigidly failing to adapt to change",7,"idiom"],
["南辕北辙","nan2yuan2bei3zhe2","actions that contradict one's goal",7,"idiom"],
["望洋兴叹","wang4yang2xing1tan4","to feel humbled before something vast",7,"idiom"],
["越俎代庖","yue4zu3dai4pao2","to overstep one's role; meddle",7,"idiom"],
["物是人非","wu4shi4ren2fei1","things unchanged, but people are gone",7,"idiom"],
["世事无常","shi4shi4wu2chang2","the impermanence of worldly affairs",7,"idiom"],
["沧海桑田","cang1hai3sang1tian2","great changes over time",7,"idiom"],
["白驹过隙","bai2ju1guo4xi4","time flies swiftly",7,"idiom"],
["韶光易逝","shao2guang1yi4shi4","beautiful time passes quickly",7,"idiom"],
["物换星移","wu4huan4xing1yi2","the passage of time; seasons changing",7,"idiom"],
["寄人篱下","ji4ren2li2xia4","to live under another's roof, dependent",7,"idiom"],
["形单影只","xing2dan1ying3zhi1","utterly alone; solitary",7,"idiom"],
["顾影自怜","gu4ying3zi4lian2","to feel sorry for oneself",7,"idiom"],
["自怨自艾","zi4yuan4zi4yi4","to reproach and blame oneself",7,"idiom"],
["咎由自取","jiu4you2zi4qu3","to bring trouble on oneself",7,"idiom"],
["自食其果","zi4shi2qi2guo3","to reap what one sows",7,"idiom"],
["殊途同归","shu1tu2tong2gui1","different paths, same destination",7,"idiom"],
["大相径庭","da4xiang1jing4ting2","widely divergent; poles apart",7,"idiom"],
["南辕北辙式","nan2yuan2bei3zhe2shi4","(lit. style) working against one's aim",7,"adj"],
["言犹在耳","yan2you2zai4er3","the words still ring in one's ears",7,"idiom"],
["余音绕梁","yu2yin1rao4liang2","lingering, unforgettable impression",7,"idiom"],
["字字珠玑","zi4zi4zhu1ji1","every word a pearl; exquisite writing",7,"idiom"],
["洛阳纸贵","luo4yang2zhi3gui4","a work so popular it causes a sensation",7,"idiom"],
["江郎才尽","jiang1lang2cai2jin4","to have exhausted one's creative talent",7,"idiom"],
["妙笔生花","miao4bi3sheng1hua1","a gifted, flowering pen; brilliant writing",7,"idiom"],
["画龙点睛","hua4long2dian3jing1","the crucial finishing touch",7,"idiom"],
["入木三分","ru4mu4san1fen1","penetrating and incisive (of writing/views)",7,"idiom"],
["言外之意","yan2wai4zhi1yi4","the implied meaning beyond the words",7,"noun"],
["弦外之音","xian2wai4zhi1yin1","an implied, unspoken meaning",7,"noun"],
["微言大义","wei1yan2da4yi4","profound meaning in few words",7,"idiom"],
["咬文嚼字","yao3wen2jiao2zi4","to fuss pedantically over wording",7,"idiom"],
["无病呻吟","wu2bing4shen1yin2","affected sentimentality; feigned suffering",7,"idiom"],
["矫揉造作","jiao3rou2zao4zuo4","affected; artificial in manner",7,"idiom"],
["言不由衷","yan2bu4you2zhong1","insincere words; not from the heart",7,"idiom"],
["虚与委蛇","xu1yu3wei1yi2","to feign politeness insincerely",7,"idiom"],
["阳奉阴违","yang2feng4yin1wei2","outward compliance, secret defiance",7,"idiom"],
["口是心非","kou3shi4xin1fei1","saying one thing, meaning another",7,"idiom"],
["言而无信","yan2er2wu2xin4","to break one's word",7,"idiom"],
["言必有中","yan2bi4you3zhong4","every word hits the mark",7,"idiom"],
["一语中的","yi4yu3zhong4di4","a remark that hits the nail on the head",7,"idiom"],
["一针见血","yi4zhen1jian4xie3","incisive; straight to the point",7,"idiom"],
["切中肯綮","qie4zhong4ken3qing4","to hit the crux of the matter exactly",7,"idiom"],
["不落窠臼","bu4luo4ke1jiu4","original; not following convention",7,"idiom"],
["独树一帜","du2shu4yi2zhi4","to establish a school of one's own",7,"idiom"],
["别具匠心","bie2ju4jiang4xin1","showing ingenious, original craftsmanship",7,"idiom"]
];

/* HSK-style fill-in-the-blank practice questions.
   Format: [level, sentence with ___, answer, [3 distractors], pinyin, english]
   Only one option fits grammatically and semantically — distractors are
   deliberately from other word classes, HSK-exam style. */
const SENTQ=[
/* ---- HSK 1 ---- */
[1,"我想喝___。","水",["狗","写","冷"],"Wo3 xiang3 he1 shui3.","I want to drink some water."],
[1,"他是我的___。","老师",["苹果","下雨","很"],"Ta1 shi4 wo3 de5 lao3shi1.","He is my teacher."],
[1,"今天天气很___。","好",["猫","读","岁"],"Jin1tian1 tian1qi4 hen3 hao3.","The weather is very good today."],
[1,"我们在饭店___饭。","吃",["睡","开","听"],"Wo3men5 zai4 fan4dian4 chi1 fan4.","We eat at the restaurant."],
[1,"你___什么名字？","叫",["吃","坐","下"],"Ni3 jiao4 shen2me5 ming2zi5?","What is your name?"],
[1,"我不___说汉语。","会",["岁","块","号"],"Wo3 bu2 hui4 shuo1 Han4yu3.","I can't speak Chinese."],
[1,"明天我去___买东西。","商店",["睡觉","漂亮","昨天"],"Ming2tian1 wo3 qu4 shang1dian4 mai3 dong1xi5.","Tomorrow I'll go to the shop to buy things."],
[1,"请问，现在几___了？","点",["狗","家","菜"],"Qing3wen4, xian4zai4 ji3 dian3 le5?","Excuse me, what time is it now?"],
[1,"我爸爸是___，他在医院工作。","医生",["学校","米饭","杯子"],"Wo3 ba4ba5 shi4 yi1sheng1, ta1 zai4 yi1yuan4 gong1zuo4.","My dad is a doctor; he works at a hospital."],
[1,"我喜欢看这本___。","书",["水","人","天"],"Wo3 xi3huan5 kan4 zhe4 ben3 shu1.","I like reading this book."],
[1,"他今年二十___。","岁",["点","块","本"],"Ta1 jin1nian2 er4shi2 sui4.","He is twenty this year."],
[1,"星期天我在家看___。","电视",["医院","名字","下雨"],"Xing1qi1tian1 wo3 zai4 jia1 kan4 dian4shi4.","On Sunday I watch TV at home."],
[1,"外面很冷，今天___了。","下雨",["打电话","认识","谢谢"],"Wai4mian4 hen3 leng3, jin1tian1 xia4yu3 le5.","It's cold outside — it rained today."],
[1,"他在___工作，他是老师。","学校",["杯子","米饭","苹果"],"Ta1 zai4 xue2xiao4 gong1zuo4, ta1 shi4 lao3shi1.","He works at a school; he's a teacher."],
[1,"喂，你好，李___在吗？","先生",["椅子","米饭","时候"],"Wei2, ni3 hao3, Li3 xian1sheng5 zai4 ma5?","Hello, is Mr Li there?"],
[1,"对不起！——___。","没关系",["谢谢","喂","什么"],"Dui4bu5qi3! — Mei2guan1xi5.","Sorry! — It's okay."],
[1,"我认识他，他是我同学的___。","朋友",["电影","苹果","商店"],"Wo3 ren4shi5 ta1, ta1 shi4 wo3 tong2xue2 de5 peng2you5.","I know him — he's my classmate's friend."],
[1,"她有三个___。","女儿",["天气","明天","名字"],"Ta1 you3 san1 ge4 nv3er2.","She has three daughters."],
/* ---- HSK 2 ---- */
[2,"这件衣服太___了，我不买。","贵",["懂","阴","忙"],"Zhe4 jian4 yi1fu5 tai4 gui4 le5, wo3 bu4 mai3.","This piece of clothing is too expensive — I'm not buying it."],
[2,"我每天早上七点___。","起床",["出","姓","贵"],"Wo3 mei3tian1 zao3shang5 qi1 dian3 qi3chuang2.","I get up at seven every morning."],
[2,"他跑得很___。","快",["红","阴","千"],"Ta1 pao3 de5 hen3 kuai4.","He runs very fast."],
[2,"弟弟正在房间里___。","睡觉",["便宜","晴","远"],"Di4di5 zheng4zai4 fang2jian1 li3 shui4jiao4.","My little brother is sleeping in the room."],
[2,"从我家到公司很___，我走路上班。","近",["贵","白","高"],"Cong2 wo3 jia1 dao4 gong1si1 hen3 jin4, wo3 zou3lu4 shang4ban1.","It's very close from my home to the company — I walk to work."],
[2,"明天我们一起去___吧。","游泳",["姓","懂","错"],"Ming2tian1 wo3men5 yi4qi3 qu4 you2yong3 ba5.","Let's go swimming together tomorrow."],
[2,"你___什么？我姓王。","姓",["卖","穿","等"],"Ni3 xing4 shen2me5? Wo3 xing4 Wang2.","What's your surname? My surname is Wang."],
[2,"今天是我的___，我二十岁了。","生日",["手机","面条","门"],"Jin1tian1 shi4 wo3 de5 sheng1ri4, wo3 er4shi2 sui4 le5.","Today is my birthday — I'm twenty."],
[2,"医生说他___了，不能上班。","生病",["跳舞","便宜","晴"],"Yi1sheng1 shuo1 ta1 sheng1bing4 le5, bu4 neng2 shang4ban1.","The doctor said he's sick and can't go to work."],
[2,"这个西瓜真___！","好吃",["忙","远","累"],"Zhe4 ge4 xi1gua1 zhen1 hao3chi1!","This watermelon is really delicious!"],
[2,"请再说一___，我没听懂。","次",["件","块","岁"],"Qing3 zai4 shuo1 yi2 ci4, wo3 mei2 ting1 dong3.","Please say it one more time — I didn't understand."],
[2,"我们坐___去机场。","出租车",["手表","鸡蛋","报纸"],"Wo3men5 zuo4 chu1zu1che1 qu4 ji1chang3.","We take a taxi to the airport."],
[2,"外面下___了，很冷。","雪",["鱼","药","票"],"Wai4mian4 xia4 xue3 le5, hen3 leng3.","It's snowing outside — it's very cold."],
[2,"哥哥比我___两岁。","大",["白","远","新"],"Ge1ge5 bi3 wo3 da4 liang3 sui4.","My older brother is two years older than me."],
[2,"我___了一个小时公共汽车。","等",["懂","笑","姓"],"Wo3 deng3 le5 yi2 ge4 xiao3shi2 gong1gong4qi4che1.","I waited an hour for the bus."],
[2,"她唱___唱得非常好。","歌",["药","鱼","门"],"Ta1 chang4 ge1 chang4 de5 fei1chang2 hao3.","She sings very well."],
/* ---- HSK 3 ---- */
[3,"请大家___，老师来了。","安静",["聪明","饱","矮"],"Qing3 da4jia1 an1jing4, lao3shi1 lai2 le5.","Everyone quiet please — the teacher is here."],
[3,"我打算去北京参加___。","比赛",["冰箱","鼻子","菜单"],"Wo3 da3suan4 qu4 Bei3jing1 can1jia1 bi3sai4.","I plan to go to Beijing to take part in a competition."],
[3,"我每天坐___上班，很快。","地铁",["蛋糕","衬衫","草"],"Wo3 mei3tian1 zuo4 di4tie3 shang4ban1, hen3 kuai4.","I take the subway to work every day — it's fast."],
[3,"他很___，什么都学得很快。","聪明",["矮","饱","短"],"Ta1 hen3 cong1ming5, shen2me5 dou1 xue2 de5 hen3 kuai4.","He's very clever — he learns everything quickly."],
[3,"我吃___了，不想再吃了。","饱",["差","层","段"],"Wo3 chi1 bao3 le5, bu4 xiang3 zai4 chi1 le5.","I'm full — I don't want to eat any more."],
[3,"别___，医生说没什么问题。","担心",["打扫","搬","迟到"],"Bie2 dan1xin1, yi1sheng1 shuo1 mei2 shen2me5 wen4ti2.","Don't worry — the doctor said there's no problem."],
[3,"周末我要___房间。","打扫",["出现","变化","迟到"],"Zhou1mo4 wo3 yao4 da3sao3 fang2jian1.","I'm going to clean my room at the weekend."],
[3,"对不起，我___了，路上车太多。","迟到",["参加","打算","搬"],"Dui4bu5qi3, wo3 chi2dao4 le5, lu4 shang4 che1 tai4 duo1.","Sorry I'm late — there was too much traffic."],
/* ---- HSK 4 ---- */
[4,"请你___完成这个工作。","按时",["抱歉","粗心","表扬"],"Qing3 ni3 an4shi2 wan2cheng2 zhe4 ge4 gong1zuo4.","Please finish this work on time."],
[4,"我们必须___环境。","保护",["打印","猜","存"],"Wo3men5 bi4xu1 bao3hu4 huan2jing4.","We must protect the environment."],
[4,"他工作很___，常常出错误。","粗心",["诚实","棒","标准"],"Ta1 gong1zuo4 hen3 cu1xin1, chang2chang2 chu1 cuo4wu4.","He's careless at work and often makes mistakes."],
[4,"他大学___以后，成为了一名医生。","毕业",["打扮","抽烟","擦"],"Ta1 da4xue2 bi4ye4 yi3hou4, cheng2wei2 le5 yi4 ming2 yi1sheng1.","After graduating from university, he became a doctor."],
[4,"我不知道这个问题的___。","答案",["窗户","饼干","倍"],"Wo3 bu4 zhi1dao4 zhe4 ge4 wen4ti2 de5 da2an4.","I don't know the answer to this question."],
[4,"明天经理要去上海___。","出差",["吃惊","表演","存"],"Ming2tian1 jing1li3 yao4 qu4 Shang4hai3 chu1chai1.","Tomorrow the manager is going to Shanghai on a business trip."],
[4,"请不要在这里___，对身体不好。","抽烟",["保证","猜","打印"],"Qing3 bu2 yao4 zai4 zhe4li3 chou1yan1, dui4 shen1ti3 bu4 hao3.","Please don't smoke here — it's bad for your health."],
[4,"他从来不说假话，非常___。","诚实",["笨","粗心","抱歉"],"Ta1 cong2lai2 bu4 shuo1 jia3hua4, fei1chang2 cheng2shi2.","He never tells lies — he's very honest."]
];

